<?php

require_once('tcpdf/tcpdf.php');
$schemeType = $this->result['shipment'][0]['scheme_type'];
$pdfNew = new Zend_Pdf();
$extractor = new Zend_Pdf_Resource_Extractor();
$font = Zend_Pdf_Font::fontWithName(Zend_Pdf_Font::FONT_HELVETICA);
$shipmentCode='';

$dtsResults = array();
foreach ($this->possibleDtsResults as $pr) {
    $dtsResults[$pr['id']] = ucfirst(strtolower($pr['response']));
}

if (sizeof($this->result['shipment']) > 0) {
	if (!file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports') &&
        !is_dir(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports')) {
		mkdir(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports');
    }

    class MYPDF extends TCPDF {
        public $scheme_name = '';

        public function setSchemeName($header, $schemeName, $logo,$logoRight,$comingFrom,$schemeType) {
            $this->scheme_name = $schemeName;
            $this->header = $header;
            $this->logo = $logo;
            $this->logoRight = $logoRight;
            $this->comingFrom = $comingFrom;
            $this->schemeType = $schemeType;
        }

        //Page header
        public function Header() {
            if($this->schemeType != 'tb') {
                if (trim($this->logo) != "") {
                    if (file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logo)) {
                        $image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logo;
                        $this->Image($image_file, 10, 10, 25, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
                    }
                }
                if (trim($this->logoRight) != "") {
                    if (file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logoRight)) {
                        $image_file = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'logo' . DIRECTORY_SEPARATOR . $this->logoRight;
                        $this->Image($image_file, 180, 10, 20, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
                    }
                }
            }

            // Set font
            $this->SetFont('Helvetica', '', 8);

            if($this->schemeType != 'tb') {
                $this->header = str_replace("<div", "<span", trim($this->header));
                $this->header = str_replace("</div>", "</span><br/>", $this->header);
            }

            $html = $this->header;

            if($this->schemeType != 'tb') {
                $this->writeHTMLCell(0, 0, 25, 10, $html, 0, 0, 0, true, 'C', true);
            }
            if ($this->schemeType == 'vl') {
                $html='<h3 style="font-weight: bold;text-align:center;">Proficiency Testing Program for HIV-1 Viral Load Using Dried Tube Specimen</h3>';
            } else if($this->schemeType == 'eid') {
                //HIV-1 Proficiency Testing Program for Early Infant Diagnosis using Dried Blood Spot.
                $html='<h3 style="font-weight: bold;text-align:center;">HIV-1 Proficiency Testing Program for Early Infant Diagnosis using Dried Blood Spot</h3>';
            } else if($this->schemeType == 'tb') {
                $html = '<h3 style="background-color:#000000;color:#ffffff;font-weight: bold;text-align:center;">';
                $html .= '<br />XPERT MTB/RIF ASSAY PROFICIENCY TEST PROGRAM PARTICIPANT’S RESULTS SUMMARY<br /></h3>';
            } else {
                $html='<h3 style="font-weight: bold;text-align:center;">Proficiency Testing Program for Anti-HIV Antibodies Diagnostics using '.$this->scheme_name.'</h3>';
            }
            if($this->schemeType != 'tb') {
                $this->writeHTMLCell(0, 0, 35, 30, $html, 0, 0, 0, true, 'J', true);
                $html = '<hr/>';
                $this->writeHTMLCell(0, 0, 10, 45, $html, 0, 0, 0, true, 'J', true);
            } else {
                $this->writeHTMLCell(0, 10, 15, 20, $html, 0, 0, 0, true, 'J', true);
            }
        }

        // Page footer
        public function Footer() {
            $finalizeReport="";
            if (trim($this->comingFrom)=="finalize") {
                $finalizeReport=' - FINALIZED';
            }
            // Position at 15 mm from bottom
            $this->SetY(-15);
            // Set font
            $this->SetFont('Helvetica', 'I', 8);
            // Page number
            $this->Cell(0, 10, "Report generated at :".date("d-M-Y H:i:s").$finalizeReport, 0, false, 'C', 0, '', 0, false, 'T', 'M');
        }
    }

    $totalPages = count($this->result['shipment']);
    $j = 1;

    $tbResultValueMapping = array(
        'detected' => 'Detected',
        'high' => 'High',
        'medium' => 'Medium',
        'low' => 'Low',
        'veryLow' => 'Very Low',
        'notDetected' => 'Not Detected',
        'detected' => 'Detected',
        'noResult' => 'No Result',
        'na' => 'N/A',
        'invalid' => 'Invalid',
        'error' => 'Error',
        '' => ''
    );

    foreach ($this->result['shipment'] as $result) {
        if (!file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR.$result['shipment_code']) &&
            !is_dir(UPLOAD_PATH . DIRECTORY_SEPARATOR .'reports'. DIRECTORY_SEPARATOR.$result['shipment_code'])) {
            mkdir(UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR.$result['shipment_code']);
        }

        // create new PDF document
        $pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

        $pdf->setSchemeName($this->header,$result['scheme_name'],
            $this->logo, $this->logoRight, $this->comingFrom, $schemeType);

        // set default header data
        $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE,
            PDF_HEADER_STRING);

        // set header and footer fonts
        $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
        $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

        // set default monospaced font
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

        // set margins
        if ($schemeType == 'tb') {
            $pdf->SetMargins(PDF_MARGIN_LEFT, 35, PDF_MARGIN_RIGHT);
            $pdf->SetHeaderMargin(1);
            $pdf->SetFooterMargin(1);
        } else {
            $pdf->SetMargins(PDF_MARGIN_LEFT, 50, PDF_MARGIN_RIGHT);
            $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
            $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
        }

        // set auto page breaks
        $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

        // set image scale factor
        $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

        // set some language-dependent strings (optional)
        if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
            require_once(dirname(__FILE__).'/lang/eng.php');
            $pdf->setLanguageArray($l);
        }

        // ---------------------------------------------------------

        // set font
        $pdf->SetFont('Helvetica', '', 11);

        // add a page
        $pdf->AddPage();

        // ---------------------------------------------------------

        if (trim($result['shipment_date']) != "") {
            $result['shipment_date'] = $this->dateFormat($result['shipment_date']);
        }
        if (trim($result['lastdate_response']) != "") {
            $result['lastdate_response'] = $this->dateFormat($result['lastdate_response']);
        }

        $config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV);
        $responseDate = "";
        $shipmentTestDate = "";
        $shipmentScore = 0;
        $documentationScore = 0;
        $score = 0;

        if (isset($result['responseResult'][0]['responseDate']) &&
            trim($result['responseResult'][0]['responseDate'])!="") {
            $splitDate = explode(" ",$result['responseResult'][0]['responseDate']);
            $responseDate = $this->dateFormat($splitDate[0]);
        }
        $attributes='';
        if (isset($result['responseResult'][0]['attributes'])) {
            $attributes = json_decode($result['responseResult'][0]['attributes'], true);
        }

        $sampleRehydrationDate = "";
        if (isset($attributes['sample_rehydration_date']) &&
            trim($attributes['sample_rehydration_date'])!="") {
            $sampleRehydrationDate = $this->dateFormat($attributes['sample_rehydration_date']);
        }
        $shipmentReceiptDate = "";
        if (isset($result['responseResult'][0]['shipment_receipt_date']) && trim($result['responseResult'][0]['shipment_receipt_date'])!="") {
            $shipmentReceiptDate = $this->dateFormat($result['responseResult'][0]['shipment_receipt_date']);
        }

        if (isset($result['responseResult'][0]['shipment_test_date']) && trim($result['responseResult'][0]['shipment_test_date']) != "") {
            $shipmentTestDate = $this->dateFormat($result['responseResult'][0]['shipment_test_date']);
        }

        //Comment Details
        if ($schemeType != 'vl' && $schemeType != 'eid' && $schemeType != 'tb') {
            $labInfo='<table cellpadding="2">';
            $labInfo.='<tr>';
            $labInfo.='	<td><strong>Participant Code</strong> <br>'.$result['unique_identifier'].'</td>';
            $labInfo.='	<td><strong>Performing Participant</strong>  <br>'.$result['first_name']." ".$result['last_name'].'</td>';
            $labInfo.='	<td><strong>PT Panel Name and Date</strong> <br>'.$result['distribution_code'].'('.$result['shipment_date'].')</td>';
            $labInfo.='</tr>';
            $labInfo.='<tr>';
            $labInfo.='	<td><strong>Shipment Date</strong> <br>'.$result['shipment_date'].'</td>';
            $labInfo.='	<td><strong>Shipment Code</strong> <br>'.$result['shipment_code'].'</td>';
            $labInfo.='	<td><strong>Shipment Type</strong>  <br>'.$result['scheme_name']." ".$result['last_name'].'</td>';
            $labInfo.='</tr>';
            $labInfo.='<tr>';
            $labInfo.='	<td><strong>Panel Receipt Date</strong> <br>'.$shipmentReceiptDate.'</td>';
            $labInfo.='	<td><strong>Rehydration Date</strong> <br>'.$sampleRehydrationDate.'</td>';
            $labInfo.='	<td><strong>Result Due Date</strong> <br>'.$result['lastdate_response'].'</td>';
            $labInfo.='</tr>';
            $labInfo.='<tr>';
            $labInfo.='	<td><strong>Response Date</strong> <br>'.$responseDate.'</td>';
            $labInfo.='	<td><strong>Shipment Test Date</strong> <br>'.$shipmentTestDate.'</td>';
            $labInfo.='	<td>';
            if (isset($attributes['algorithm'])) {
                $labInfo.='	<strong>Algorithm</strong> <br>'.ucfirst($attributes['algorithm']);
            }
            $labInfo.=' </td>';
            $labInfo.='</tr>';
            $labInfo.='<tr>';
            $labInfo.='	<td>';
            $labInfo.='	<strong>Supervisor Name</strong> <br>'.($result['participant_supervisor']);
            $labInfo.=' </td>';
            $labInfo.='	<td>';
            if (isset($this->haveCustom) && $this->haveCustom == 'yes') {
                $labInfo.='	<strong>'.$this->customField1.'</strong> <br>'.$this->shipment['custom_field_1'];
            }
            $labInfo.=' </td>';
            $labInfo.='	<td>';
            if (isset($this->haveCustom) && $this->haveCustom == 'yes') {
                $labInfo.='	<strong>'.$this->customField2.'</strong> <br>'.$this->shipment['custom_field_2'];
            }
            $labInfo.=' </td>';
            $labInfo.='</tr>';
            $labInfo.='</table>';
            $pdf->writeHTML($labInfo, true, false, true, false, '');
        } else if ($schemeType == 'eid') {
            $labInfo='<table cellpadding="2">';
            $labInfo.='<tr>';
            $labInfo.='	<td><strong>PT Panel Name and Date</strong> <br>'.$result['distribution_code'].'('.$result['shipment_date'].')</td>';
            $labInfo.='	<td><strong>PT Panel Received</strong> <br>'.$shipmentReceiptDate.'</td>';
            $labInfo.='</tr>';
            $labInfo.='<tr>';
            $labInfo.='	<td><strong>Extraction Assay </strong> <br>'.$result['extractionAssayVal'].'</td>';
            $labInfo.='	<td><strong>PT Panel Tested </strong> <br>'.$shipmentTestDate.'</td>';
            $labInfo.='</tr>';
            $labInfo.='<tr>';
            $labInfo.='	<td><strong>Detection Assay </strong> <br>'.$result['detectionAssayVal'].'</td>';
            $labInfo.='	<td><strong>Results Submitted Date</strong> <br>'.$responseDate.'</td>';
            $labInfo.='</tr>';
            $labInfo.='<tr>';
            $labInfo.='	<td><strong>Lab Id</strong> <br>'.$result['unique_identifier'].'</td>';
            $labInfo.='</tr>';
            $labInfo.='</table>';
            $pdf->writeHTML($labInfo, true, false, true, false, '');
        }  else if ($schemeType == 'tb') {
            $labInfo = '<h3 style="width:100%;text-align:center;">'.$result['shipment_code'].'</h3>';
            $labInfo .= '<p style="font-size:10pt;width:100%;text-align:center;">International Laboratory Branch, Division of Global HIV and TB, Centers for Disease Control and Prevention</p>';
            $labInfo .= '<table cellpadding="2" style="width:100%;font-size:8pt;">';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:10%;"></td>';
            $labInfo .= '	     <td style="border-top:solid 10px #000000;border-bottom:solid 10px #000000;background-color:#777777;color:#ffffff;text-align:center;width:20%;"><strong>Country</strong></td>';
            $labInfo .= '	     <td style="border-top:solid 10px #000000;border-bottom:solid 10px #000000;background-color:#777777;color:#ffffff;text-align:center;width:40%;"><strong>Testing Site</strong></td>';
            $labInfo .= '	     <td style="border-top:solid 10px #000000;border-bottom:solid 10px #000000;background-color:#777777;color:#ffffff;text-align:center;width:20%;"><strong>PT-ID Number</strong></td>';
            $labInfo .= '	     <td style="width:10%;"></td>';
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td></td>';
            $labInfo .= '	     <td style="text-align:center;border-bottom:solid 10px #000000;">'.$result['country_name'].'</td>';
            $labInfo .= '	     <td style="text-align:center;border-bottom:solid 10px #000000;">'.$result['first_name']." ".$result['last_name'];
            if ($result['is_excluded'] == 'yes') {
                $labInfo .= ' <span style="color:#ff0000;">(Excluded)</span>';
            }
            $labInfo .= '</td>';
            $labInfo .= '	     <td style="text-align:center;border-bottom:solid 10px #000000;">'.$result['unique_identifier'].'</td>';
            $labInfo .= '	     <td></td>';
            $labInfo .= '    </tr>';
            $labInfo .= '</table><br /><br />';
            $labInfo .= '<table cellpadding="3" style="width:100%;font-size:8pt;">';
            $labInfo .= '    <tr style="background-color:#777777;color:#ffffff;">';
            $labInfo .= '	     <td style="text-align:center;border-top:solid 10px #000000;border-bottom:solid 10px #000000;" colspan="'.(count($this->result['tbReportSummary']) + 1).'"><strong>Summary of All Reporting Sites</strong></td>';
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;"></td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;"><strong>'.$sampleSummary['sample_label'].'</strong>';
                if ($sampleSummary['ref_is_excluded'] == 'yes') {
                    if ($sampleSummary['ref_is_exempt'] == 'yes') {
                        $labInfo .= '<br /><span style="color:#ffa500;">(Exempt)</span>';
                    } else {
                        $labInfo .= '<br /><span style="color:#ff0000;">(Excluded)</span>';
                    }
                }
                $labInfo .= '</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;">Total number of reporting sites</td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;">'.$sampleSummary['no_of_responses'].'</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="background-color:#cccccc;width:100%;" colspan="'.(count($this->result['tbReportSummary']) + 1).'"><strong>TB Detection</strong></td>';
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;">Sites detecting TB (%)</td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;">'.$sampleSummary['mtb_detected'].' ('.round(($sampleSummary['mtb_detected'] / $sampleSummary['no_of_responses']) * 100, 1).'%)</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;">Sites not detecting TB (%)</td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;">'.$sampleSummary['mtb_not_detected'].' ('.round(($sampleSummary['mtb_not_detected'] / $sampleSummary['no_of_responses']) * 100, 1).'%)</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;">Sites reporting uninterpretable TB result*(%)</td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;">'.$sampleSummary['mtb_uninterpretable'].' ('.round(($sampleSummary['mtb_uninterpretable'] / $sampleSummary['no_of_responses']) * 100, 1).'%)</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;">Sites not reporting TB detection result (%)</td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;">'.$sampleSummary['mtb_result_not_reported'].' ('.round(($sampleSummary['mtb_result_not_reported'] / $sampleSummary['no_of_responses']) * 100, 1).'%)</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="background-color:#cccccc;width:100%;" colspan="'.(count($this->result['tbReportSummary']) + 1).'"><strong>RIF Detection</strong></td>';
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;">Sites detecting Rif resistance (%)</td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;">'.$sampleSummary['rif_detected'].' ('.round(($sampleSummary['rif_detected'] / $sampleSummary['no_of_responses']) * 100, 1).'%)</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;">Sites not detecting Rif resistance (%)</td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;">'.$sampleSummary['rif_not_detected'].' ('.round(($sampleSummary['rif_not_detected'] / $sampleSummary['no_of_responses']) * 100, 1).'%)</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;">Sites reporting indeterminate Rif result (%)</td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;">'.$sampleSummary['rif_indeterminate'].' ('.round(($sampleSummary['rif_indeterminate'] / $sampleSummary['no_of_responses']) * 100, 1).'%)</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;">Sites reporting uninterpretable Rif result*(%)</td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;">'.$sampleSummary['rif_uninterpretable'].' ('.round(($sampleSummary['rif_uninterpretable'] / $sampleSummary['no_of_responses']) * 100, 1).'%)</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:40%;border-bottom:solid 10px #000000;">Sites not reporting Rif detection result (%)</td>';
            foreach ($this->result['tbReportSummary'] as $sampleSummary) {
                $labInfo .= '	     <td style="width:'.(60 / count($this->result['tbReportSummary'])).'%;text-align:center;border-bottom:solid 10px #000000;">'.$sampleSummary['rif_result_not_reported'].' ('.round(($sampleSummary['rif_result_not_reported'] / $sampleSummary['no_of_responses']) * 100, 1).'%)</td>';
            }
            $labInfo .= '    </tr>';
            $labInfo .= '    <tr>';
            $labInfo .= '	     <td style="width:100%;" colspan="'.(count($this->result['tbReportSummary']) + 1).'">* Uninterpretable result = invalid, error, or no result</td>';
            $labInfo .= '    </tr>';
            $labInfo .= '</table><br />';
            $pdf->writeHTML($labInfo, true, false, true, false, '');
        } else {
            $labInfo='<table cellpadding="2">';
            $labInfo.='<tr>';
            $labInfo.='	<td><strong>PT Panel </strong> <br>'.$result['distribution_code'].'('.$result['shipment_date'].')</td>';
            $labInfo.='	<td><strong>Date PT Panel Received</strong> <br>'.$shipmentReceiptDate.'</td>';
            $labInfo.='</tr>';
            $labInfo.='<tr>';
            $labInfo.='	<td><strong>Your Lab Id</strong> <br>'.$result['unique_identifier'].'</td>';
            $labInfo.='	<td><strong>Date PT Panel Tested</strong> <br>'.$shipmentTestDate.'</td>';
            $labInfo.='</tr>';
            $labInfo.='</table>';
            $pdf->writeHTML($labInfo, true, false, true, false, '');
        }

        if (isset($result['responseResult']) && sizeof($result['responseResult']) > 0) {
            if ($schemeType != 'vl' && $schemeType != 'eid' && $schemeType != 'tb') {
                $labRes = '<span style="font-weight: bold;font-size:13px;">Your laboratory test results : <br/></span><table border="1" style="font-size:13px;">';
                $labRes .='<tr style="background-color:#dbe4ee;"><td></td><td style="text-align:center;font-weight:bold;">Test-1</td><td style="text-align:center;font-weight:bold;">Test-2</td><td style="text-align:center;font-weight:bold;">Test-3</td><td colspan="4" style="border:none;"></td></tr>';
                $labRes .='<tr><td style="text-align:center;font-weight:bold;background-color:#dbe4ee;">Kit Name</td><td>'.$result['responseResult'][0]['testkit1'].'</td><td>'.$result['responseResult'][0]['testkit2'].'</td><td>'.$result['responseResult'][0]['testkit3'].'</td><td colspan="4"></td></tr>';
                $labRes .='<tr><td style="text-align:center;font-weight:bold;background-color:#dbe4ee;">Lot No.</td><td>'.$result['responseResult'][0]['lot_no_1'].'</td><td>'.$result['responseResult'][0]['lot_no_2'].'</td><td>'.$result['responseResult'][0]['lot_no_3'].'</td><td colspan="4"></td></tr>';
                $labRes .='<tr><td style="text-align:center;font-weight:bold;background-color:#dbe4ee;">Expiry Date</td><td>'.$this->dateFormat($result['responseResult'][0]['exp_date_1']).'</td><td>'.$this->dateFormat($result['responseResult'][0]['exp_date_2']).'</td><td>'.$this->dateFormat($result['responseResult'][0]['exp_date_3']).'</td><td colspan="4"></td></tr>';
                $labRes .='<tr style="background-color:#dbe4ee;">
                                <td style="text-align:center;font-weight:bold;">Specimen Panel ID </td>
                                <td style="text-align:center;font-weight:bold;">Result-1</td>
                                <td style="text-align:center;font-weight:bold;">Result-2</td>
                                <td style="text-align:center;font-weight:bold;">Result-3</td>
                                <td style="text-align:center;font-weight:bold;">Expected Result</td>
                                <td style="text-align:center;font-weight:bold;">Your Result</td>
    
                                <td style="text-align:center;font-weight:bold;" colspan="2">Score</td>
                            </tr>';

                $nonMandatorySamples = array();
                $controlSamples = array();
                $correctSamples = array();
                $totalProperSamples = 0;
                $correctSamplesCount = 0;
                $wrongSamples = array();
                $otherSamples = array();
                $allSamples = array();

                foreach ($result['responseResult'] as $response) {
                    $allSamples[] = $response['sample_label'];
                    if ($response['control'] == 1) {
                        $controlSamples[] = $response['sample_label'];
                    }
                    if ($response['mandatory'] == 0) {
                        $nonMandatorySamples[] = $response['sample_label'];
                    } else if ($response['calculated_score'] == 'Pass') {
                        $correctSamples[] = $response['sample_label'];
                    } else if($response['calculated_score'] == 'Fail') {
                        $wrongSamples[] = $response['sample_label'];
                    } else {
                        $otherSamples[] = $response['sample_label'];
                    }
                }

                $correctSamplesCount = count($correctSamples);
                $totalProperSamples = $correctSamplesCount + count($wrongSamples);
                $maxDocumentationPoints = (isset($config->evaluation->dts->documentationScore) && $config->evaluation->dts->documentationScore > 0) ? ($config->evaluation->dts->documentationScore) : 0;
                $maximumResponseScore = 100 - $maxDocumentationPoints;
                $scorePerCorrectSample = round($maximumResponseScore/(count($allSamples)-count($nonMandatorySamples) - count($controlSamples)),2);

                foreach ($result['responseResult'] as $response) {
                    if ($response['calculated_score'] == 'Pass') {
                        $img = UPLOAD_PATH . '/../images/check.jpg';
                        $score = ($response['control'] == 0) ? $scorePerCorrectSample : "N.A.";
                    } else if ($response['calculated_score'] == 'Fail') {
                        $img = UPLOAD_PATH . '/../images/cross.jpg';
                        $score = ($response['control'] == 0) ? 0 : "N.A.";
                    } else {
                        $img = UPLOAD_PATH . '/../images/minus.jpg';
                        $score = "N.A.";
                    }
                    $labRes.='<tr>
                                  <td style="text-align:center;">'.$response['sample_label'].'</td>
                                  <td>'.(isset($response['test_result_1']) && $response['test_result_1'] !="" ? $dtsResults[$response['test_result_1']] : "").'</td>
                                  <td>'.(isset($response['test_result_2']) && $response['test_result_2'] !="" ? $dtsResults[$response['test_result_2']] : "").'</td>
                                  <td>'.(isset($response['test_result_3']) && $response['test_result_3'] !="" ? $dtsResults[$response['test_result_3']] : "").'</td>
                                  <td>'.ucfirst(strtolower($response['referenceResult'])).'</td>
                                  <td>'.ucfirst(strtolower($response['labResult'])).'</td>
                                  <td style="text-align:center;"><img style="width:11px;" src="'.$img.'" /></td>
                                  <td style="text-align:center;">'.$score.'</td>
                              </tr>';
                }
                $labRes.='</table>';

                $pdf->SetLeftMargin(15);
                $pdf->writeHTML($labRes, true, false, true, false, '');
                if (count($nonMandatorySamples) > 0) {
                    $nmsTable="The following samples have been excluded from this evaluation : ".implode(", ",$nonMandatorySamples);
                    $nmsTable.="<br/>";
                    $pdf->writeHTML($nmsTable, true, false, true, false, '');
                }
                //Let us now calculate documentation score
                $documentationScore = 0;
                $documentationScorePerItem = (isset($config->evaluation->dts->documentationScore) && $config->evaluation->dts->documentationScore > 0) ? ($config->evaluation->dts->documentationScore / 5) : 0;
                $attributes = json_decode($result['attributes'], true);

                $img = array();
                $imgPass = UPLOAD_PATH . '/../images/check.jpg';
                $imgFail = UPLOAD_PATH . '/../images/cross.jpg';

                $docRes='<span style="font-weight:bold;font-size:13px;">Your documentation score :</span> <br/>
                        <table border="1" style="font-size:13px;width:100%;">
                            <tr style="background-color:#dbe4ee;">
                                <td style="text-align:center;font-weight:bold;width:75%">Documentation Item</td>
                                <td style="text-align:center;font-weight:bold;width:25%" colspan="2">Score</td>
                            </tr>';

                if (strtolower($result['responseResult'][0]['supervisor_approval']) == 'yes' && trim($result['responseResult'][0]['participant_supervisor']) != "") {
                    $scoreDoc =  $documentationScorePerItem;
                    $img = $imgPass;
                } else {
                    $scoreDoc = 0;
                    $img = $imgFail;
                }

                $docRes.='<tr>
                              <td style="text-align:left;font-weight:bold;">Supervisor Approval</td>
                              <td style="text-align:center;"><img style="width:11px;" src="'.$img.'" /></td>
                              <td style="text-align:center;">'.$scoreDoc.'</td>
                          </tr>';

                if (isset($result['responseResult'][0]['shipment_receipt_date']) && trim($result['responseResult'][0]['shipment_receipt_date']) != "") {
                    $scoreDoc =  $documentationScorePerItem;
                    $img = $imgPass;
                } else {
                    $scoreDoc = 0;
                    $img = $imgFail;
                }

                $docRes.='<tr>
                              <td style="text-align:left;font-weight:bold;">Panel/Shipment Receipt Date Specified</td>
                              <td style="text-align:center;"><img style="width:11px;" src="'.$img.'" /></td>
                              <td style="text-align:center;">'.$scoreDoc.'</td>
                          </tr>';

                if (isset($attributes['sample_rehydration_date']) && trim($attributes['sample_rehydration_date']) != "") {
                    $scoreDoc =  $documentationScorePerItem;
                    $img = $imgPass;
                } else {
                    $scoreDoc = 0;
                    $img = $imgFail;
                }


                $docRes.='<tr>
                              <td style="text-align:left;font-weight:bold;">Reporting of the Sample Rehydration Date</td>
                              <td style="text-align:center;"><img style="width:11px;" src="'.$img.'" /></td>
                              <td style="text-align:center;">'.$scoreDoc.'</td>
                          </tr>';


                if (isset($result['responseResult'][0]['shipment_test_date']) && trim($result['responseResult'][0]['shipment_test_date']) != "") {
                    $scoreDoc =  $documentationScorePerItem;
                    $img = $imgPass;
                } else {
                    $scoreDoc = 0;
                    $img = $imgFail;
                }

                $docRes.='<tr>
                              <td style="text-align:left;font-weight:bold;">Reporting of the Shipment Test Date</td>
                              <td style="text-align:center;"><img style="width:11px;" src="'.$img.'" /></td>
                              <td style="text-align:center;">'.$scoreDoc.'</td>
                          </tr>';

                $config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV);
                $sampleRehydrationDate = new DateTime($attributes['sample_rehydration_date']);
                $testedOnDate = new DateTime($result['responseResult'][0]['shipment_test_date']);
                $interval = $sampleRehydrationDate->diff($testedOnDate);

                // Testing should be done within 24*($config->evaluation->dts->sampleRehydrateDays) hours of rehydration.
                $sampleRehydrateDays = $config->evaluation->dts->sampleRehydrateDays;
                $rehydrateHours = $sampleRehydrateDays*24;

                if ($interval->days > $sampleRehydrateDays) {
                    $scoreDoc = 0;
                    $img = $imgFail;
                } else {
                    $scoreDoc =  $documentationScorePerItem;
                    $img = $imgPass;
                }

                $docRes.='<tr>
                              <td style="text-align:left;font-weight:bold;">Testing to be done within '.$rehydrateHours.' hours of rehydration.</td>
                              <td style="text-align:center;"><img style="width:11px;" src="'.$img.'" /></td>
                              <td style="text-align:center;">'.$scoreDoc.'</td>
                          </tr>';
                $docRes.='</table>';

                $pdf->writeHTML($docRes, true, false, true, false, '');

                if (isset($result['responseResult'][0]['failure_reason']) && $result['responseResult'][0]['failure_reason'] != "" && $result['responseResult'][0]['failure_reason'] != "[]" && $result['responseResult'][0]['failure_reason'] != null) {
                    $failRes = '<span style="font-weight:bold;font-size:13px;">Suggested Corrective actions for your response :</span> <br/>';
                    $failRes .= '<table border="1" style="font-size:13px;">';
                    $failRes.= '<tr style="background-color:#dbe4ee;"><td style="text-align:center;font-weight:bold;">Failure Reasons (or) Warnings</td><td style="text-align:center;font-weight:bold;">Corrective Actions (if any)</td></tr>';
                    $warnings = json_decode($result['responseResult'][0]['failure_reason'],true);
                    foreach ($warnings as $warning) {
                        $failRes.= '<tr>';
                        $failRes.= '<td> '.(isset($warning['warning']) ? $warning['warning'] : "").' </td>';
                        $failRes.= '<td> '.(isset($warning['correctiveAction']) ? $warning['correctiveAction'] : "").' </td>';
                        $failRes.= '</tr>';
                    }
                    $failRes.= '</table>';
                    $pdf->writeHTML($failRes, true, false, true, false, '');
                }
            } else if ($schemeType=='eid') {
                $n=count($result['responseResult']);
                $labRes = '<span style="font-weight: bold;font-size:13px;">Your laboratory test results : <br/></span>';
                $labRes .= '<table border="1" style="font-size:13px;">';
                $labRes .= '<tr style="background-color:#dbe4ee;">';
                $labRes .= '<td colspan="'.($n+2).'" style="text-align:center;font-weight:bold;">Sample ID</td>';
                $labRes .= '</tr>';
                $labRes.='<tr style="background-color:#dbe4ee;">';
                $labRes.='<td></td>';
                //Sample codes
                foreach ($result['responseResult'] as $response) {
                    $labRes.='<td style="text-align:center;font-weight:bold;">'.$response['sample_label'].'</td>';
                }
                $labRes.='<td style="text-align:center;font-weight:bold;">Score(%)</td>';
                $labRes.='</tr>';
                $labRes.='<tr>';
                $labRes.='<td>Expected Result</td>';
                foreach ($result['responseResult'] as $response) {
                    $labRes.='<td style="text-align:left;">'.$response['referenceResult'].'</td>';
                }
                $labRes.='<td rowspan="2" style="text-align:center;"><br>'.$result['shipment_score'].'</td>';
                $labRes.='</tr>';
                $labRes.='<tr>';
                $labRes.='<td>Your Results</td>';
                foreach ($result['responseResult'] as $response) {
                    $labRes.='<td style="text-align:left;">'.$response['labResult'].'</td>';
                }
                $labRes.='</tr>';
                $labRes .= '</table>';
                $pdf->SetLeftMargin(15);
                $pdf->writeHTML($labRes, true, false, true, false, '');
            } else if ($schemeType == 'tb') {
                $labRes = '<table cellpadding="1" style="width:100%;font-size:8pt;">';
                $labRes .= '    <tr style="background-color:#777777;color:#ffffff;">';
                $labRes .= '	     <td style="text-align:center;border-top:solid 10px #000000;border-bottom:solid 10px #000000;" colspan="4"><strong>Site Results</strong></td>';
                $labRes .= '    </tr>';
                $labRes .= '    <tr>';
                $labRes .= '	     <td style="width:46%;border-bottom:solid 10px #000000;"></td>';
                $labRes .= '	     <td style="width:22%;border-bottom:solid 10px #000000;text-align:center;"><strong>MTB Detected</strong></td>';
                $labRes .= '	     <td style="width:22%;border-bottom:solid 10px #000000;text-align:center;"><strong>RIF Resistance</strong></td>';
                $labRes .= '	     <td style="width:10%;border-bottom:solid 10px #000000;text-align:center;"><strong>Score</strong></td>';
                $labRes .= '    </tr>';
                $scoreTotal = 0;
                $maxScoreTotal = 0;
                foreach ($result['responseResult'] as $response) {
                    $labRes .= '    <tr>';
                    $labRes .= '	     <td style="background-color:#cccccc;width:100%;" colspan="4"><strong>Sample ID: '.$response['sample_label'].'</strong></td>';
                    $labRes .= '    </tr>';
                    $labRes .= '    <tr>';
                    $labRes .= '	     <td style="width:46%;">Expected Results</td>';
                    $labRes .= '	     <td style="width:22%;text-align:center;">'.$tbResultValueMapping[$response['expected_mtb_detected']].'</td>';
                    $labRes .= '	     <td style="width:22%;text-align:center;">'.$tbResultValueMapping[$response['expected_rif_resistance']].'</td>';
                    $labRes .= '	     <td style="width:10%;"></td>';
                    $labRes .= '    </tr>';
                    $labRes .= '    <tr>';
                    $labRes .= '	     <td style="width:46%;">Consensus Results</td>';
                    $labRes .= '	     <td style="width:22%;text-align:center;">'.$tbResultValueMapping[$response['consensus_mtb_detected']].'</td>';
                    $labRes .= '	     <td style="width:22%;text-align:center;">'.$tbResultValueMapping[$response['consensus_rif_resistance']].'</td>';
                    $labRes .= '	     <td style="width:10%;">';
                    if ($response['ref_is_excluded'] == 'yes') {
                        if ($response['ref_is_exempt'] == 'yes') {
                            $labRes .= '<span style="color:#ffa500;">(Exempt)</span>';
                        } else {
                            $labRes .= '<span style="color:#ff0000;">(Excluded)</span>';
                        }
                    }
                    $labRes .= '</td>';
                    $labRes .= '    </tr>';
                    $labRes .= '    <tr>';
                    $labRes .= '	     <td style="width:46%;"><strong>'.$result['first_name']." ".$result['last_name'].'</strong></td>';
                    if ($response['mtb_detected'] == 'error') {
                        $labRes .= '	     <td style="width:22%;text-align:center;"><strong>Error: '.$response['error_code'].'</strong></td>';
                        $labRes .= '	     <td style="width:22%;text-align:center;"></td>';
                    } else {
                        $labRes .= '	     <td style="width:22%;text-align:center;"><strong>'.$tbResultValueMapping[$response['mtb_detected']].'</strong></td>';
                        $labRes .= '	     <td style="width:22%;text-align:center;"><strong>'.$tbResultValueMapping[$response['rif_resistance']].'</strong></td>';
                    }
                    $labRes .= '	     <td style="width:10%;text-align:center;"><strong>'.$response['score'].'</strong></td>';
                    $labRes .= '    </tr>';
                }
                $labRes .= '    <tr>';
                $labRes .= '	     <td style="width:46%;border-top: solid 10px #000000;"></td>';
                $labRes .= '	     <td style="width:22%;border-top: solid 10px #000000;border-bottom: solid 10px #000000;text-align:center;"><strong>Percentage</strong></td>';
                $labRes .= '	     <td style="width:22%;border-top: solid 10px #000000;border-bottom: solid 10px #000000;text-align:center;"><strong>Satisfactory/Unsatisfactory</strong></td>';
                $labRes .= '	     <td style="width:10%;border-top: solid 10px #000000;"></td>';
                $labRes .= '    </tr>';
                $labRes .= '    <tr>';
                $labRes .= '	     <td style="width:46%;background-color:#B6DDE8;border-bottom: solid 10px #000000;border-right: solid 10px #ffffff;"><strong>FINAL SCORE</strong></td>';
                $labRes .= '	     <td style="width:22%;background-color:#B6DDE8;border-top: solid 10px #000000;border-bottom: solid 10px #000000;text-align:center;"><strong>'.round(($result['shipment_score'] / $result['max_shipment_score']) * 100, 1).'</strong></td>';
                $labRes .= '	     <td style="width:22%;background-color:#B6DDE8;border-top: solid 10px #000000;border-bottom: solid 10px #000000;text-align:center;"><strong>'.($result['submission_score_status'] == 'fail' ? 'Unsatisfactory' : 'Satisfactory').'</strong></td>';
                $labRes .= '	     <td style="width:10%;border-top: solid 10px #000000;"></td>';
                $labRes .= '    </tr>';
                $labRes .= '</table>';
                if ((isset($result['eval_comment']) && $result['eval_comment'] !== '') ||
                    (isset($result['optional_eval_comment']) && $result['optional_eval_comment'] !== '') ||
                    (isset($result['shipment_comment']) && $result['shipment_comment'] !== '')) {
                    $labRes .= '<br /><br />';
                    $labRes .= '<table cellpadding="2" style="width:100%;font-size:8pt;">';
                    $labRes .= '    <tr style="background-color:#777777;color:#ffffff;">';
                    $labRes .= '	     <td style="text-align:center;border-top:solid 10px #000000;border-bottom:solid 10px #000000;"><strong>Comments</strong></td>';
                    $labRes .= '    </tr>';
                    if (isset($result['eval_comment']) && $result['eval_comment'] !== '') {
                        $labRes .= '    <tr>';
                        $labRes .= '	     <td>'.$result['eval_comment'].'</td>';
                        $labRes .= '    </tr>';
                    }
                    if (isset($result['optional_eval_comment']) && $result['optional_eval_comment'] !== '') {
                        $labRes .= '    <tr>';
                        $labRes .= '	     <td>'.$result['optional_eval_comment'].'</td>';
                        $labRes .= '    </tr>';
                    }
                    if (isset($result['shipment_comment']) && $result['shipment_comment'] !== '') {
                        $labRes .= '    <tr>';
                        $labRes .= '	     <td>'.$result['shipment_comment'].'</td>';
                        $labRes .= '    </tr>';
                    }
                    $labRes .= '</table>';
                }
                if (isset($result['corrective_actions']) && count($result['corrective_actions'])  > 0) {
                    $labRes .= '<br />';
                    $labRes .= '<table cellspacing="1" cellpadding="2" style="width:100%;font-size:8pt;">';
                    $labRes .= '    <tr style="background-color:#777777;color:#ffffff;">';
                    $labRes .= '	     <td style="text-align:center;border-top:solid 10px #000000;border-bottom:solid 10px #000000;" colspan="2"><strong>Corrective Actions Checklist</strong></td>';
                    $labRes .= '    </tr>';
                    foreach ($result['corrective_actions'] as $correctiveAction) {
                        $labRes .= '    <tr>';
                        $labRes .= '	     <td style="border:solid 10px #000000;width:17px;"></td>';
                        $labRes .= '	     <td>'.$correctiveAction.'</td>';
                        $labRes .= '    </tr>';
                    }
                    $labRes .= '</table>';
                }
                $pdf->writeHTML($labRes, true, false, true, false, '');
            } else {
                //Vl report
                $labRes='<h5>'.$result['responseResult'][0]['vl_assay'];
                if (isset($attributes['vl_assay']) && $attributes['vl_assay']==6) {
                    $labRes.=" - ".$attributes['other_assay'];
                }
                $labRes.='</h5>';
                if ($result['responseResult'][0]['no_of_participants'] > 7) {
                    $labRes.='<table border="1" style="text-align:center;font-weight:bold;width:650px;font-size:13px;">
                                  <tr>
                                      <td style="background-color:#dbe4ee;">Specimen ID </td>
                                      <td style="background-color:#dbe4ee;">Your Results<br/>(log<sub>10</sub> copies/ml)</td>
                                      <td style="background-color:#dbe4ee;">Mean<br/>(log<sub>10</sub> copies/ml)</td>
                                      <td style="background-color:#dbe4ee;">S.D.</td>
                                      <td style="background-color:#dbe4ee;"># of Labs</td>
                                      <td style="background-color:#dbe4ee;">Lowest <br/> Acceptable Limit</td>
                                      <td style="background-color:#dbe4ee;">Highest <br/> Acceptable Limit</td>
                                      <td style="background-color:#dbe4ee;">Your Grade</td>
                                  </tr>';
                    if ($result['is_excluded'] == 'yes') {
                        foreach ($result['responseResult'] as $response) {
                            $labRes.='<tr>
                                          <td style="text-align:center;">'.$response['sample_label'].'</td>
                                          <td>'.$response['reported_viral_load'].'</td>
                                          <td>'.number_format(round($response['mean'],2),2,'.','').'</td>
                                          <td>'.number_format(round($response['sd'],2),2,'.','').'</td>
                                          <td>'.$response['no_of_participants'].'</td>
                                          <td>'.number_format(round($response['low'],2),2,'.','').'</td>
                                          <td>'.number_format(round($response['high'],2),2,'.','').'</td>
                                          <td>Manual Exclusion</td>
                                      </tr>';
                        }
                    } else {
                        foreach($result['responseResult'] as $response){
                            $labRes.='<tr>
                                          <td style="text-align:center;">'.$response['sample_label'].'</td>
                                          <td>'.$response['reported_viral_load'].'</td>
                                          <td>'.number_format(round($response['mean'],2),2,'.','').'</td>
                                          <td>'.number_format(round($response['sd'],2),2,'.','').'</td>
                                          <td>'.$response['no_of_participants'].'</td>
                                          <td>'.number_format(round($response['low'],2),2,'.','').'</td>
                                          <td>'.number_format(round($response['high'],2),2,'.','').'</td>
                                          <td>'.$response['grade'].'</td>
                                      </tr>';
                        }
                    }
                    $labRes.='</table>';
                } else {
                    $labRes.='<table border="1" style="text-align:center;font-weight:bold;width:650px;font-size:13px;">
                                  <tr>
                                      <td style="background-color:#dbe4ee;">Specimen ID </td>
                                      <td style="background-color:#dbe4ee;">Your Results<br/>(log<sub>10</sub> copies/ml)</td>
                                      <td style="background-color:#dbe4ee;"># of Labs</td>
                                      <td style="background-color:#dbe4ee;">Your Grade</td>
                                  </tr>';
                    foreach ($result['responseResult'] as $response) {
                        $labRes.='<tr>
                                      <td style="text-align:center;">'.$response['sample_label'].'</td>
                                      <td>'.$response['reported_viral_load'].'</td>
                                      <td>'.$response['no_of_participants'].'</td>
                                      <td>Not Evaluated</td>
                                  </tr>';
                    }
                    $labRes.='</table>';
                    $labRes.='<h5>'.$result['responseResult'][0]['vl_assay'].' Platforms were not analyzed or graded</h5>';
                }

                $pdf->SetLeftMargin(15);
                $pdf->writeHTML($labRes, true, false, true, false, '');
                $footerHead='<h5>0.00 = Target Not Detected or less than lower limit of detection</h5><br/>';
                $pdf->writeHTML($footerHead, true, false, true, false, '');
            }
        }

        if ($schemeType != 'tb') {
            if (trim($result['shipment_score']) != "") {
                if ($result['shipment_score'] != 0) {
                    $shipmentScore = ($result['shipment_score'] / $result['shipment_score']) * 100;
                } else {
                    $result['shipment_score'] = 0;
                }
            }
            $score = ($shipmentScore / (isset($result['responseResult']) ? count($result['responseResult']) : 1)) * 100;

            if (trim($result['shipment_comment']) != "" || trim($result['evaluationComments']) != "" || trim($result['optional_eval_comment']) != "") {
                $comment = '<br/><br/><table border="1" style="width:100%;font-size:13px;" cellpadding="3">';
                if (trim($result['evaluationComments']) != "") {
                    $comment .= '<tr>';
                    $comment .= '<td style="font-weight:bold;width:30%;">Evaluation Comments </td>';
                    $comment .= '<td style="width:70%;">' . $result['evaluationComments'] . '</td>';
                    $comment .= '</tr>';
                }
                if (trim($result['optional_eval_comment']) != "") {
                    $comment .= '<tr>';
                    $comment .= '<td style="font-weight:bold;width:30%;">Specific Comments/Feedback</td>';
                    $comment .= '<td style="width:70%;">' . $result['optional_eval_comment'] . '</td>';
                    $comment .= '</tr>';
                }
                if (trim($result['shipment_comment']) != "") {
                    $comment .= '<tr>';
                    $comment .= '<td style="font-weight:bold;" colspan="2">' . $result['shipment_comment'] . '</td>';
                    $comment .= '</tr>';
                }
                $comment .= '</table>';
                $pdf->writeHTML($comment, true, false, true, false, '');
            }
            if ($schemeType == 'vl') {
                $html = '<p>Thank you for participating in the HIV Viral Load Proficiency Testing Program.</p>';
            } else if ($schemeType == 'eid') {
                $html = '<p>Thank you for participating in HIV-1 Proficiency Testing Program for Early Infant Diagnosis using Dried Blood Spot.</p>';
            } else {
                $html = '<p>Thank you for participating in the ' . ($result['scheme_name']) . ' Proficiency Testing Program.</p>';
            }
            $pdf->writeHTML($html, true, false, true, false, '');
        }

        if (ob_get_contents()) {
            ob_end_clean();
        }
        //Close and output PDF document
        if (isset($result['last_name']) && trim($result['last_name'])!="") {
            $result['last_name']="_".$result['last_name'];
        }

        $fileName = $result['first_name'].$result['last_name']."-".$result['map_id'].".pdf";
        $fileName = preg_replace('/[^A-Za-z0-9.]/', '-', $fileName);
        $fileName = str_replace(" ", "-", $fileName);
        $filePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR .$result['shipment_code']. DIRECTORY_SEPARATOR .$fileName;
        $created = $pdf->Output($filePath, "F");

        $loadpdf = Zend_Pdf::load($filePath);

        foreach ($loadpdf->pages as $page) {
            $pdfExtract = $extractor->clonePage($page);
            $pdfNew->pages[] = $pdfExtract;
        }
        $shipmentCode=$result['shipment_code'];
        $j++;
    }

    //$mergePdf = $shipmentCode."-bulk-participant-report.pdf";
    $mergePdf = $shipmentCode."-".$this->bulkfileNameVal."-bulk-participant-report.pdf";
    $mergeFilePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR .$shipmentCode. DIRECTORY_SEPARATOR .$mergePdf;
    $pdfNew ->save($mergeFilePath);

    foreach ($this->result['dmResult'] as $key=>$dmRes) {
        $pdfNew->pages=array();
        $expRes=explode(",",$dmRes);
        $resCount=count($expRes);
        if ($resCount>0) {
            foreach ($expRes as $res) {
                $expStrRes=explode("#",$res);
                $dmFileName=$expStrRes[0].$key.".pdf";
                $participantFileName=$expStrRes[2].".pdf";
                $participantFileName = preg_replace('/[^A-Za-z0-9.]/', '-', $participantFileName);
                $participantFileName = str_replace(" ", "-", $participantFileName);
                $filePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR .$shipmentCode. DIRECTORY_SEPARATOR .$participantFileName;

                $loadpdf = Zend_Pdf::load($filePath);
                foreach ($loadpdf->pages as $page) {
                    $pdfExtract = $extractor->clonePage($page);
                    $pdfNew->pages[] = $pdfExtract;
                }
            }
        }

        $dmFileName = preg_replace('/[^A-Za-z0-9.]/', '-', $dmFileName);
        $dmFileName = str_replace(" ", "-", $dmFileName);

        $mergePdf = $shipmentCode."-".$dmFileName;
        $mergeFilePath = UPLOAD_PATH . DIRECTORY_SEPARATOR . 'reports'. DIRECTORY_SEPARATOR .$shipmentCode. DIRECTORY_SEPARATOR .$mergePdf;
        $pdfNew ->save($mergeFilePath);
    }

    //============================================================+
    // END OF FILE
    //============================================================+
    echo "success";
}