<link rel="stylesheet" href="<?php echo $this->baseUrl('css/daterangepicker.css'); ?>" type="text/css" media="all">
<style>
    @media print {
        .dontPrint, #testKitTable_filter, #testKitTable_info{
            display:none;
        }
    }
</style>
<legend><h3>Submission Score History</h3></legend>
<table style="margin:20px 0;" class="table table-bordered">
    <tr>
        <td style="width:150px;text-align: center;font-weight:bold;">
            Pick a Date Range
        </td>
        <td style="width:100px;text-align: center;font-weight:bold;">
            Report Type
        </td>
        <td id="reportTypeFilter" style="width:200px;text-align: center;font-weight:bold;">
            Participant
        </td>
        <td class="dontPrint" style="width:115px;text-align: center;font-weight:bold;">Action</td>
    </tr>
    <tr>
        <td>
            <input type="text" id="dateRange" name="dateRange" class="form-control input-sm" readonly="readonly"
                   style="background: #fff" placeholder ="Click here to pick a Date Range" />
        </td>
        <td>
            <select id="reportType" name="reportType" class="form-control input-sm">
                <option value='participant'>Participant</option>
                <option value='country'>Country</option>
            </select>
        </td>
        <td>
            <select id="reportTypeFilter" name="reportTypeFilter" class="form-control input-sm" disabled></select>
        </td>
        <td class="dontPrint">
            <button class="btn btn-success btn-sm" onclick="drawTable()">
                <span>Get Report</span>
            </button>
            <button class="btn btn-danger btn-sm" onclick="document.location.href = document.location">
                <span>Reset</span>
            </button>
            <button class="btn btn-primary btn-sm" onclick="GetPrint()">
                <span>Print</span>
            </button>
        </td>
    </tr>
</table>
<br />
<div id="scoresChart"></div>
<br />
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover hide"
       id="scoresTable">
    <thead>
    <tr>
        <th style="text-align: center;">Shipment Code</th>
        <th style="text-align: center;">Score</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td colspan="10" class="dataTables_empty">Loading data from server</td>
    </tr>
    </tbody>
</table>
<script type="text/javascript" src="<?php echo $this->baseUrl('js/daterangepicker.js'); ?>"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/drilldown.js"></script>
<script type="text/javascript">
  var startDate = "";
  var endDate = "";
  var reportType = "";
  var paginate = true;

  $(document).ready(function() {
    $('#dateRange').daterangepicker({
        format: 'DD-MMM-YYYY',
        ranges: {
          'Last 60 Days': [moment().subtract('days', 59), moment()],
          'Last 90 Days': [moment().subtract('days', 89), moment()],
          'Last 180 Days': [moment().subtract('days', 179), moment()],
          'Last 12 Months': [moment().subtract('month', 12), moment()],
          'Last 18 Months': [moment().subtract('month', 18), moment()],
        }
      }, function(start, end) {
        startDate = start.format('YYYY-MM-DD');
        endDate = end.format('YYYY-MM-DD');
        getReportTypeFilters();
      });
    $('#reportType').on('change', function () {
      reportType = this.value;
      getReportTypeFilters();
    });
  });

  function getReportTypeFilters() {
    if (startDate && endDate && reportType) {
      $.blockUI();
      $.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'common', 'action' => 'get-submission-score-history-report-filters')); ?>",
        {
          startDate: startDate,
          endDate: endDate,
          reportType: reportType,
          format: "html"
        }, function (data) {
          if (data) {
            $("#reportTypeFilter").html(data);
            $("#reportTypeFilter").removeAttr('disabled');
          }
          $.unblockUI();
        });
    } else {
      $("#reportTypeFilter").html('');
      $("#reportTypeFilter").attr('disabled', 'disabled');
    }
  }

  function drawTable(callBack) {
    if (!$("#dateRange").val() || !reportType || $("#reportTypeFilter").val() == "") {
      alert("Please pick date range and a report type to proceed");
      return false;
    }
    $("#scoresTable").removeClass("hide");
    $.blockUI();
    showPieChart(reportType, $("#reportTypeFilter").val());
    $('#scoresTable').dataTable({
      "oLanguage": {
        "sLengthMenu": "_MENU_ records per page",
        "sEmptyTable": "No data to show"
      },
      "bPaginate": paginate,
      "bJQueryUI": false,
      "bAutoWidth": false,
      "bInfo": true,
      "bScrollCollapse": true,
      "sPaginationType": "bootstrap",
      "bRetrieve": false,
      "bDestroy": true,
      "aoColumns": [
        {"sClass": ""},
        {"sClass": "center"}
      ],
      "aaSorting": [[1, "desc"]],
      "bProcessing": true,
      "bServerSide": true,
      "sAjaxSource": "<?php echo $this->url(array('module' => 'reports', 'controller' => 'tb-submission-score-history', 'action' => 'index', 'format' => 'html')); ?>",
      "fnServerParams": function (aoData) {
        aoData.push({"name": "reportType", "value": reportType});
        aoData.push({"name": "reportTypeFilter", "value": $("#reportTypeFilter").val()});
      },
      "fnServerData": function (sSource, aoData, fnCallback) {
        $.ajax({
          "dataType": 'json',
          "type": "POST",
          "url": sSource,
          "data": aoData,
          "success": function(data) {
            fnCallback(data);
            $.unblockUI();
            if (callBack) {
              callBack();
            }
          }
        });
      }
    });
  }

  function showPieChart(reportType, reportTypeFilter) {
    $.post("<?php echo $this->url(array('module' => 'reports', 'controller' => 'tb-submission-score-history', 'action' => 'submissions-count')); ?>",
      { shipmentId: shipmentId, format: "html" },
      function (data) {
        $("#countriesChart").html(data);
        $.unblockUI();
      });
  }

  function GetPrint() {
    paginate = false;
    drawTable(function () {
      setTimeout(function () {
        $('.dataTables_filter').addClass("dontPrint");
        window.print();
      }, 1000);
    });
  }
</script>
