<style>
    .circleContainer {
        position: relative;
        width: 1075px;
        height: 1075px;
    }

    .segmentContainer {
        position: absolute;
        height: 535px;
        width: 535px;
        overflow: hidden;
        -webkit-transition: 0.25s ease-in-out;
        -moz-transition: 0.25s ease-in-out;
        -o-transition: 0.25s ease-in-out;
        transition: 0.25s ease-in-out;
    }

    .segmentContainer.left {
        left: 0;
    }

    .segmentContainer.right {
        left: 540px;
    }

    .segmentContainer.top {
        top: 0;
    }

    .segmentContainer.bottom {
        top: 540px;
    }

    .popOutPanel {
        border: solid 0.3em #000000;
        border-radius: 2em;
        position: absolute;
        height: 525px;
        width: 525px;
        overflow: hidden;
        padding: 1em;
        -webkit-transition: 0.25s ease-in-out;
        -moz-transition: 0.25s ease-in-out;
        -o-transition: 0.25s ease-in-out;
        transition: 0.25s ease-in-out;
    }

    .popOutPanel.top {
        top: 0px;
    }

    .popOutPanel.bottom {
        top: 550px;
    }

    .popOutPanel.left {
        left: 0px;
    }

    .popOutPanel.right {
        left: 550px;
    }

    .segmentContainer .circleSegment {
        position: absolute;
        border-radius: 50%;
        width: 160%;
        height: 160%;
        border: solid 0.4em rgb(249, 249, 249);
        -webkit-transition: 0.25s ease-in-out;
        -moz-transition: 0.25s ease-in-out;
        -o-transition: 0.25s ease-in-out;
        transition: 0.25s ease-in-out;
    }

    .segmentContainer:hover .circleSegment {
        -webkit-transform: scale(1.05);
        -moz-transform: scale(1.05);
        -o-transform: scale(1.05);
        -ms-transform: scale(1.05);
        transform: scale(1.05);
    }

    .segmentContainer.top.left > .circleSegment {
        background-color: #ED7D31;
        top: 20%;
        right: -80%;
    }

    .segmentContainer.top.right > .circleSegment {
        background-color: #D17B5C;
        top: 20%;
        left: -80%;
    }

    .segmentContainer.bottom.left > .circleSegment {
        background-color: #A5A5A5;
        top: -80%;
        right: -80%;
    }

    .segmentContainer.bottom.right > .circleSegment {
        background-color: #B98A82;
        top: -80%;
        left: -80%;
    }

    .popOutPanel.top.left {
        border-color: #ED7D31;
    }

    .popOutPanel.top.right {
        border-color: #D17B5C;
    }

    .popOutPanel.bottom.left {
        border-color: #A5A5A5;
    }

    .popOutPanel.bottom.right {
        border-color: #B98A82;
    }

    .segmentContainer > .circleSegment > div {
        width: 15em;
        height: 20em;
        position: relative;
    }

    .segmentContainer > .circleSegment > div > h3 {
        text-transform: uppercase;
        position: absolute;
        left: 0;
        width: 100%;
        text-align: center;
        color: #fff;
    }

    .segmentContainer.left > .circleSegment > div {
        float: right;
        margin-right: 36em;
    }

    .segmentContainer.right > .circleSegment > div {
        float: left;
        margin-left: 32em;
    }

    .segmentContainer.top > .circleSegment > div {
        margin-top: 6em;
    }

    .segmentContainer.bottom > .circleSegment > div {
        margin-top: 34em;
    }

    .segmentContainer.top > .circleSegment > div > h3 {
        bottom: 0;
    }

    .segmentContainer.bottom > .circleSegment > div > h3 {
        top: 0;
    }

    .segmentContainer.bottom > .circleSegment > div > img {
        margin-top: 2em;
    }

    .centerCycle {
        position: absolute;
        width: 133px;
        height: 132px;
        left: 476px;
        top: 460px;
    }

    .segmentContainer.active {
        left: 0;
        top: 540px;
    }

    .segmentContainer.top.right.active {
        left: 100px !important;
        top: 440px !important;
    }

    .segmentContainer.top.left.active {
        top: 440px !important;
    }

    .segmentContainer.bottom.right.active {
        left: 100px !important;
    }

    .popOutPanel.active {
        left: 125px;
        top: 50px;
        width: 900px;
        height: 975px;
    }

    .popOutPanel .textShifter {
        border-radius: 50%;
        width: 160%;
        height: 160%;
        background-color: rgb(249, 249, 249);
        margin: 0;
        clear: both;
        visibility: hidden;
        opacity: 0;
        -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
        filter: alpha(opacity=0);
    }

    .popOutPanel.left .textShifter {
        float: right;
        margin-right: -80%;
    }

    .popOutPanel.right .textShifter {
        float: left;
        margin-left: -77%;
    }

    .popOutPanel.top .textShifter {
        vertical-align: bottom;
        margin-top: 20%;
    }

    .popOutPanel.bottom .textShifter {
        margin-top: -80%;
    }

    .popOutPanel.top.left .textShifter {
        shape-outside: ellipse(50% 50% at 50% 60%);
        -webkit-clip-path: ellipse(50% 50% at 50% 60%);
        clip-path: ellipse(50% 50% at 50% 60%);
        -webkit-shape-outside: ellipse(50% 50% at 50% 60%);
    }

    .popOutPanel.top.right .textShifter {
        shape-outside: ellipse(50% 50% at 50% 60%);
        -webkit-clip-path: ellipse(50% 50% at 50% 60%);
        clip-path: ellipse(50% 50% at 50% 60%);
        -webkit-shape-outside: ellipse(50% 50% at 50% 60%);
    }

    .popOutPanel.bottom.left .textShifter {
        shape-outside: ellipse(100% 100% at 100% 0);
        -webkit-clip-path: ellipse(100% 100% at 100% 0);
        clip-path: ellipse(100% 100% at 100% 0);
        -webkit-shape-outside: ellipse(100% 100% at 100% 0);
    }

    .popOutPanel.bottom.right .textShifter {
        shape-outside: ellipse(100% 100% at 0 0);
        -webkit-clip-path: ellipse(100% 100% at 0 0);
        clip-path: ellipse(100% 100% at 0 0);
        -webkit-shape-outside: ellipse(100% 100% at 0 0);
    }

    .popOutPanel.active .textShifter {
        float: left !important;
        vertical-align: bottom !important;
        margin-top: 65% !important;
        margin-bottom: 0 !important;
        margin-left: -110% !important;
        margin-right: 0 !important;
        shape-outside: ellipse(50% 50% at 50% 60%) !important;
        -webkit-clip-path: ellipse(50% 50% at 50% 60%) !important;
        clip-path: ellipse(50% 50% at 50% 60%) !important;
        -webkit-shape-outside: ellipse(50% 50% at 50% 60%) !important;
    }
</style>
<div class="circleContainer">
    <div class="popOutPanel top left">
        <div class="textShifter"></div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
    </div>
    <div class="popOutPanel top right">
        <div class="textShifter"></div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
    </div>
    <div class="popOutPanel bottom left">
        <div class="textShifter"></div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
    </div>
    <div class="popOutPanel bottom right">
        <div class="textShifter"></div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
    </div>
    <div class="segmentContainer top left">
        <div class="circleSegment">
            <div>
                <img src="/images/assessment.png" alt="Assessment" title="Assessment" />
                <h3>Assessment</h3>
            </div>
        </div>
    </div>
    <div class="segmentContainer top right">
        <div class="circleSegment">
            <div>
                <img src="/images/processes_programs.png" alt="Processes/Programs" title="Processes/Programs" />
                <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Processes/Programs</h3>
            </div>
        </div>
    </div>
    <div class="segmentContainer bottom left">
        <div class="circleSegment">
            <div>
                <h3>Progress/Improvements</h3>
                <img src="/images/progress_improvements.png" alt="Progress/Improvements" title="Progress/Improvements" />
            </div>
        </div>
    </div>
    <div class="segmentContainer bottom right">
        <div class="circleSegment">
            <div>
                <h3>Results</h3>
                <img src="/images/results.png" alt="Results" title="Results" />
            </div>
        </div>
    </div>
    <div class="centerCycle">
        <img src="/images/top_cycle.png" />
        <br />
        <br />
        <img src="/images/bottom_cycle.png" />
    </div>
    <!-- Add back arrow -->
</div>
<script>
  $(document).ready(function() {
    $('.segmentContainer').click(function () {
      var clickedSegment = this;
      var popOutPanelSelector = '.' + $(clickedSegment).attr('class').replace('segmentContainer', 'popOutPanel').replace(/\s/g, '.');
      var clickedSegmentActive = $(clickedSegment).hasClass('active');
      $('.segmentContainer').removeClass('active');
      $('.popOutPanel').removeClass('active');
      if (!clickedSegmentActive) {
        $(clickedSegment).addClass('active');
        $(popOutPanelSelector).addClass('active');
        $('.centerCycle').hide();
        $('.segmentContainer').each(function (index, segment) {
          var loopPopOutPanelSelector = '.' + $(segment).attr('class').replace('segmentContainer', 'popOutPanel').replace(/\s/g, '.').replace('.active', '');
          if (loopPopOutPanelSelector !== popOutPanelSelector) {
            $(loopPopOutPanelSelector).hide();
          }
          if (segment !== clickedSegment) {
            $(segment).hide();
          }
        })
      } else {
        $('.centerCycle').show();
        $('.segmentContainer').show();
        $('.popOutPanel').show();
      }
    })
  })
</script>
