<style>
    .circleContainer {
        position: relative;
        width: 100%;
        padding-top: 100%;
    }

    .segmentContainer {
        position: absolute;
        overflow: hidden;
        -webkit-transition: 0.25s ease-in-out;
        -moz-transition: 0.25s ease-in-out;
        -o-transition: 0.25s ease-in-out;
        transition: 0.25s ease-in-out;
    }

    .segmentContainer.left {
        left: 0;
        right: 49.8%;
    }

    .segmentContainer.right {
        left: 50.2%;
        right: 0;
    }

    .segmentContainer.top {
        top: 0;
        bottom: 49.8%;
    }

    .segmentContainer.bottom {
        top: 50.2%;
        bottom: 0;
    }

    .popOutPanel {
        border: solid 0.3em #000000;
        border-radius: 2em;
        position: absolute;
        height: 49%;
        width: 49%;
        overflow: hidden;
        padding: 1em;
        -webkit-transition: 0.25s ease-in-out;
        -moz-transition: 0.25s ease-in-out;
        -o-transition: 0.25s ease-in-out;
        transition: 0.25s ease-in-out;
    }

    .popOutPanel.top {
        top: 0;
        bottom: 49%;
    }

    .popOutPanel.bottom {
        top: 51%;
        bottom: 0;
    }

    .popOutPanel.left {
        left: 0;
        right: 49%;
    }

    .popOutPanel.right {
        left: 51%;
        right: 0;
    }

    .segmentContainer .circleSegment {
        position: absolute;
        border-radius: 50%;
        width: 160%;
        height: 160%;
        border: solid 0.4em rgb(249, 249, 249);
        -webkit-transition: 0.25s ease-in-out;
        -moz-transition: 0.25s ease-in-out;
        -o-transition: 0.25s ease-in-out;
        transition: 0.25s ease-in-out;
    }

    .segmentContainer:hover .circleSegment {
        -webkit-transform: scale(1.05);
        -moz-transform: scale(1.05);
        -o-transform: scale(1.05);
        -ms-transform: scale(1.05);
        transform: scale(1.05);
    }

    .segmentContainer.top.left > .circleSegment {
        background-color: #ED7D31;
        top: 20%;
        right: -80%;
    }

    .segmentContainer.top.right > .circleSegment {
        background-color: #D17B5C;
        top: 20%;
        left: -80%;
    }

    .segmentContainer.bottom.left > .circleSegment {
        background-color: #A5A5A5;
        top: -80%;
        right: -80%;
    }

    .segmentContainer.bottom.right > .circleSegment {
        background-color: #B98A82;
        top: -80%;
        left: -80%;
    }

    .popOutPanel.top.left {
        border-color: #ED7D31;
    }

    .popOutPanel.top.right {
        border-color: #D17B5C;
    }

    .popOutPanel.bottom.left {
        border-color: #A5A5A5;
    }

    .popOutPanel.bottom.right {
        border-color: #B98A82;
    }

    .segmentContainer > .circleSegment > div {
        width: 22%;
        height: 30%;
        position: relative;
    }

    .segmentContainer > .circleSegment > div > h3 {
        text-transform: uppercase;
        position: absolute;
        left: 0;
        width: 100%;
        text-align: center;
        color: #fff;
        white-space: nowrap;
        word-break: keep-all;
    }

    .segmentContainer.left > .circleSegment > div {
        float: right;
        margin-right: 65%;
    }

    .segmentContainer.right > .circleSegment > div {
        float: left;
        margin-left: 55%;
    }

    .segmentContainer.top > .circleSegment > div {
        margin-top: 12%;
    }

    .segmentContainer.bottom > .circleSegment > div {
        margin-top: 54%;
    }

    .segmentContainer.top > .circleSegment > div > h3 {
        bottom: 0;
    }

    .segmentContainer.bottom > .circleSegment > div > h3 {
        top: 0;
    }

    .segmentContainer > .circleSegment > div > img {
        height: 80%;
    }

    .segmentContainer.top > .circleSegment > div > img {
        margin-bottom: 10%;
    }

    .segmentContainer.bottom > .circleSegment > div > img {
        margin-top: 25%;
    }

    @media only screen and (max-width: 768px) {
        .segmentContainer > .circleSegment > div > h3 {
            font-size: 1em;
            margin: 0;
            white-space: pre-wrap;
        }

        .segmentContainer > .circleSegment > div > img {
            height: 60%;
        }

        .segmentContainer.top > .circleSegment > div > img {
            margin-bottom: 50%;
        }

        .segmentContainer.bottom > .circleSegment > div > img {
            margin-top: 50%;
        }
    }

    .centerCycle {
        position: absolute;
        width: 12%;
        height: 12%;
        left: 44%;
        top: 44%;
    }

    .centerCycle img {
        width: 90%;
        height: 40%;
        margin: 5%;
    }

    .segmentContainer.active {
        top: 50%;
        bottom: 0;
        right: 50%;
        left: 0;
    }

    .popOutPanel.active {
        left: 12%;
        top: 5%;
        width: 84%;
        height: 91%;
    }

    .popOutPanel .textShifter {
        border-radius: 50%;
        width: 160%;
        height: 160%;
        margin: 0;
        clear: both;
        background-color: rgb(249, 249, 249);
        visibility: hidden;
        opacity: 0;
        -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
        filter: alpha(opacity=0);
    }

    .popOutPanel.left .textShifter {
        float: right;
        margin-right: -80%;
    }

    .popOutPanel.right .textShifter {
        float: left;
        margin-left: -77%;
    }

    .popOutPanel.top .textShifter {
        vertical-align: bottom;
        margin-top: 20%;
    }

    .popOutPanel.bottom .textShifter {
        margin-top: -80%;
    }

    .popOutPanel.top.left .textShifter {
        shape-outside: ellipse(50% 50% at 50% 60%);
        -webkit-clip-path: ellipse(50% 50% at 50% 60%);
        clip-path: ellipse(50% 50% at 50% 60%);
        -webkit-shape-outside: ellipse(50% 50% at 50% 60%);
    }

    .popOutPanel.top.right .textShifter {
        shape-outside: ellipse(50% 50% at 50% 60%);
        -webkit-clip-path: ellipse(50% 50% at 50% 60%);
        clip-path: ellipse(50% 50% at 50% 60%);
        -webkit-shape-outside: ellipse(50% 50% at 50% 60%);
    }

    .popOutPanel.bottom.left .textShifter {
        shape-outside: ellipse(100% 100% at 100% 0);
        -webkit-clip-path: ellipse(100% 100% at 100% 0);
        clip-path: ellipse(100% 100% at 100% 0);
        -webkit-shape-outside: ellipse(100% 100% at 100% 0);
    }

    .popOutPanel.bottom.right .textShifter {
        shape-outside: ellipse(100% 100% at 0 0);
        -webkit-clip-path: ellipse(100% 100% at 0 0);
        clip-path: ellipse(100% 100% at 0 0);
        -webkit-shape-outside: ellipse(100% 100% at 0 0);
    }

    .popOutPanel.active .textShifter {
        float: left !important;
        vertical-align: bottom !important;
        margin-top: 65% !important;
        margin-bottom: 0 !important;
        margin-left: -110% !important;
        margin-right: 0 !important;
        shape-outside: ellipse(50% 50% at 50% 60%) !important;
        -webkit-clip-path: ellipse(50% 50% at 50% 60%) !important;
        clip-path: ellipse(50% 50% at 50% 60%) !important;
        -webkit-shape-outside: ellipse(50% 50% at 50% 60%) !important;
    }
</style>
<div class="circleContainer">
    <div class="popOutPanel top left">
        <div class="textShifter"></div>
        <ul>
            <li>XMPEP DTS Testing Instructions</li>
        </ul>


        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>


    </div>
    <div class="popOutPanel top right">
        <div class="textShifter"></div>
        <ul>
            <li>
                Planning for country transition to Xpert MTB RIF Ultra cartridges
            </li>
            <li>
                FIND Implementation Guidance & Support
            </li>
            <li>
                FIND Roadmap to GeneXpert Implementation
            </li>
            <li>
                FIND Tuberculosis SOPs
            </li>
        </ul>


        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>


    </div>
    <div class="popOutPanel bottom left">
        <div class="textShifter"></div>
        <ul>
            <li>
                Corrective Action form
            </li>
            <li>
                Practical Guide to Implementing a Quality Assurance System for Xpert
            </li>
            <li>
                FIND TB Training Materials & Job Aids
            </li>
            <li>
                GLI Training Package (Technical Modules for Xpert MTB RIF Ultra)
            </li>
            <li>
                Cepheid GeneXpert Resources
            </li>
        </ul>


        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>


    </div>
    <div class="popOutPanel bottom right">
        <div class="textShifter"></div>
        <ul>
            <li>How to use ePT</li>
        </ul>


        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p>
        <p>Sed ut perspiciatis unde omnis.</p>
        <p>But I must explain to you how all this mistaken idea of denouncing pleasure</p>


    </div>
    <div class="segmentContainer top left">
        <div class="circleSegment">
            <div>
                <img src="/images/assessment.png" alt="Assessment" title="Assessment" />
                <h3>Assessment</h3>
            </div>
        </div>
    </div>
    <div class="segmentContainer top right">
        <div class="circleSegment">
            <div>
                <img src="/images/processes_programs.png" alt="Processes/Programs" title="Processes/Programs" />
                <h3>Processes/&#8203;Programs</h3>
            </div>
        </div>
    </div>
    <div class="segmentContainer bottom left">
        <div class="circleSegment">
            <div>
                <h3>Progress/&#8203;Improvements</h3>
                <img src="/images/progress_improvements.png" alt="Progress/Improvements" title="Progress/Improvements" />
            </div>
        </div>
    </div>
    <div class="segmentContainer bottom right">
        <div class="circleSegment">
            <div>
                <h3>Results</h3>
                <img src="/images/results.png" alt="Results" title="Results" />
            </div>
        </div>
    </div>
    <div class="centerCycle">
        <img src="/images/top_cycle.png" />
        <img src="/images/bottom_cycle.png" />
    </div>
    <!-- Add back arrow -->
</div>
<script>
  $(document).ready(function() {
    $('.segmentContainer').click(function () {
      var clickedSegment = this;
      var popOutPanelSelector = '.' + $(clickedSegment).attr('class').replace('segmentContainer', 'popOutPanel').replace(/\s/g, '.');
      var clickedSegmentActive = $(clickedSegment).hasClass('active');
      $('.segmentContainer').removeClass('active');
      $('.popOutPanel').removeClass('active');
      if (!clickedSegmentActive) {
        $(clickedSegment).addClass('active');
        $(popOutPanelSelector).addClass('active');
        $('.centerCycle').hide();
        $('.segmentContainer').each(function (index, segment) {
          var loopPopOutPanelSelector = '.' + $(segment).attr('class').replace('segmentContainer', 'popOutPanel').replace(/\s/g, '.').replace('.active', '');
          if (loopPopOutPanelSelector !== popOutPanelSelector) {
            $(loopPopOutPanelSelector).hide();
          }
          if (segment !== clickedSegment) {
            $(segment).hide();
          }
        })
      } else {
        $('.centerCycle').show();
        $('.segmentContainer').show();
        $('.popOutPanel').show();
      }
    })
  })
</script>
