<legend><h3>Monthly Indicators</h3></legend>
<table style="margin:20px 0;" class="table table-bordered">
    <tr>
        <td colspan="2" style="text-align: center;font-weight:bold;">
            Filters
        </td>
    </tr>
    <tr>
        <td style="width:60px;text-align: center;font-weight:bold;">
            Country
        </td>
        <td style="width:100px;">
            <select id="countryId" name="countryId"  class="form-control input-sm">
                <option value=''>-- All Countries --</option>
                <?php foreach ($this->countriesList as $country) { ?>
                <option value='<?php echo $country['id'] ?>'><?php echo $country['iso_name'] ?></option>
                <?php } ?>
            </select>
        </td>
    </tr>
    <tr>
        <td style="text-align: center;font-weight:bold;">
            Month
        </td>
        <td>
            <select id="month" name="month"  class="form-control input-sm">
                <?php foreach ($this->monthsList as $month) { ?>
                <option value='<?php echo $month['value'] ?>'><?php echo $month['text'] ?></option>
                <?php } ?>
            </select>
        </td>
    </tr>
    <tr>
        <td colspan="2" class="dontPrint" style="text-align: right;">
            <button class="btn btn-success btn-sm" onclick="drawTable()">
                <span>Get Report</span>
            </button>
            <button class="btn btn-danger btn-sm" onclick="document.location.href = document.location">
                <span>Reset</span>
            </button>
        </td>
    </tr>
</table>
<br />
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover hide"
       id="generatedReportsTable">
    <thead>
    <tr>
        <th>Generated Report</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td id="generatedReportLink" class="dataTables_empty">Generating Report...</td>
    </tr>
    </tbody>
</table>
<script type="text/javascript">
  function drawTable() {
    $("#generatedReportsTable").removeClass("hide");
    $.blockUI();
      $.ajax({
          "dataType": 'json',
          "type": "POST",
          "url": "<?php echo $this->url(array('module' => 'reports', 'controller' => 'monthly-indicators', 'action' => 'index', 'format' => 'html')); ?>",
          "data": {
              "countryId": $("#countryId").val(),
              "month": $("#month").val()
          },
          "success": function(data) {
              $.unblockUI();
              if (data["report-name"]) {
                  var reportLink = '<a href="<?php echo $this->baseUrl("/uploads/generated-reports/") ?>' + data["report-name"] + '" target="_BLANK">' + data["report-name"] + '</a>';
                  $("#generatedReportLink").html(reportLink);
                  window.open('<?php echo $this->baseUrl("/uploads/generated-reports/") ?>' + data["report-name"]);
              }
          }
      });
  }
</script>
