<h4 style="height: 60px;">
    <span style="font-size: 16px; font-style: italic;letter-spacing: 2px;font-weight: bold;">
        <span class="text-success"><?php echo $this->numberOfInserts; ?>&nbsp;new</span>,&nbsp;
        <span class="text-info"><?php echo $this->numberOfUpdates; ?>&nbsp;changed</span>&nbsp;&amp;&nbsp;
        <?php echo $this->numberOfUnchanged; ?>&nbsp;unchanged&nbsp;participants in worksheet.
    </span>
    <a id="importParticipantsConfirmAnchor" href="#" class="btn btn-success" style="float: right;"><i class="icon-check"></i>&nbsp;Confirm&nbsp;Import</a>
</h4>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="participantImportTable">
    <thead>
    <tr>
        <th class="hidden"></th>
        <th>Participant ID</th>
        <th>Lab Name/Participant Name</th>
        <th>Region</th>
        <th>Country</th>
        <th>Phone</th>
        <th>Username</th>
        <th>Password</th>
        <th>Status</th>
        <th>Import Action</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $insertStyle = 'class="text-success"';
    $updateStyle = 'class="text-info"';
    $unchangedStyle = 'class="text-primary"';
    foreach($this->tempParticipants as $tempParticipant) { ?>
    <tr>
        <td class="hidden"><?php echo $tempParticipant["sorting_unique_identifier"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : $unchangedStyle; ?>><?php echo $tempParticipant["unique_identifier"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_lab_name"] ? $updateStyle : $unchangedStyle); ?>><?php echo $tempParticipant["lab_name"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_region"] ? $updateStyle : $unchangedStyle); ?>><?php echo $tempParticipant["region"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_country"] ? $updateStyle : $unchangedStyle); ?>><?php echo $tempParticipant["country"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_phone_number"] ? $updateStyle : $unchangedStyle); ?>><?php echo $tempParticipant["phone_number"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_username"] ? $updateStyle : $unchangedStyle); ?>><?php echo $tempParticipant["username"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_password"] ? $updateStyle : $unchangedStyle); ?>><?php echo $tempParticipant["password"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_status"] ? $updateStyle : $unchangedStyle); ?>><?php echo ucwords($tempParticipant["status"]); ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update"] ? $updateStyle : $unchangedStyle); ?>><?php echo ucwords($tempParticipant["import_action"]); ?></td>
    </tr>
    <?php
    } ?>
    </tbody>
</table>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function() {
        oTable = $('#participantImportTable').dataTable( {
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "sPaginationType": "bootstrap",
            "aoColumns": [
                { "aTargets": [ 0 ], "sClass": "hidden"  },
                { "sClass": "center", "iDataSort": 0 },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" }
            ],
            "aaSorting": [[ 0, "asc" ]]
        });
    });
</script>