<?php if ($this->error) { ?>
<div class="alert alert-danger">
    <h4><?php echo $this->error; ?></h4>
</div>
<a href="/admin/participants"><i class="icon-arrow-left"></i>&nbsp;go back</a>
<?php } else { ?>
<h4 style="height: 60px;">
    <span style="font-size: 16px; font-style: italic;letter-spacing: 2px;font-weight: bold;">
        <span class="text-success"><?php echo $this->numberOfInserts; ?> new</span>, <span class="text-info"><?php echo $this->numberOfUpdates; ?> changed</span> &amp; <?php echo $this->numberOfUnchanged; ?> unchanged participant users in worksheet.
        <br />
        Create <span class="text-success"><?php echo $this->numberOfUserInserts; ?>&nbsp;new users</span> to existing participants.
        <br />
        Link <span class="text-info"><?php echo $this->numberOfUserLinks; ?>&nbsp;existing users</span> to existing participants.
    </span>
    <a id="importParticipantsConfirmAnchor" href="<?php echo $this->url(array("module" => "admin", "controller" => "participants", "action" => "confirm-import"), 'default', true) ?>" class="btn btn-success" style="float: right;"><i class="icon-check"></i>&nbsp;Confirm&nbsp;Import</a>
</h4>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="participantImportTable">
    <thead>
    <tr>
        <th class="hidden"></th>
        <th>PT ID</th>
        <th>Lab Name</th>
        <th>Region</th>
        <th>Country</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Username</th>
        <th>Password</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $insertStyle = 'class="text-success"';
    $updateStyle = 'class="text-info"';
    $unchangedStyle = 'class="text-primary"';
    $removeStyle = 'class="text-danger" style="text-decoration: line-through;"';
    foreach($this->tempParticipants as $tempParticipant) { ?>
    <tr>
        <td class="hidden"><?php echo $tempParticipant["sorting_unique_identifier"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : $unchangedStyle; ?>><?php echo $tempParticipant["unique_identifier"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_lab_name"] ? $updateStyle : $unchangedStyle); ?>><?php echo $tempParticipant["lab_name"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_region"] ? (!$tempParticipant["region"] && $tempParticipant["old_region"] ? $removeStyle : $updateStyle) : $unchangedStyle); ?>><?php echo !$tempParticipant["region"] && $tempParticipant["old_region"] ? $tempParticipant["old_region"] : $tempParticipant["region"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_country"] ? $updateStyle : $unchangedStyle); ?>><?php echo $tempParticipant["country"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_phone_number"] ? (!$tempParticipant["phone_number"] && $tempParticipant["old_phone"] ? $removeStyle : $updateStyle) : $unchangedStyle); ?>><?php echo !$tempParticipant["phone_number"] && $tempParticipant["old_phone"] ? $tempParticipant["old_phone"] : $tempParticipant["phone_number"]; ?></td>
        <td <?php echo $tempParticipant["insert"] ? $insertStyle : ($tempParticipant["update_email"] ? (!$tempParticipant["email"] && $tempParticipant["old_email"] ? $removeStyle : $updateStyle) : $unchangedStyle); ?>><?php echo !$tempParticipant["email"] && $tempParticipant["old_email"] ? $tempParticipant["old_email"] : $tempParticipant["email"]; ?></td>
        <td <?php echo $tempParticipant["insert_user"] ? $insertStyle : ($tempParticipant["update_username"] || $tempParticipant["insert_user_link"] ? (!$tempParticipant["username"] && $tempParticipant["old_username"] ? $removeStyle : $updateStyle) : $unchangedStyle); ?>><?php echo !$tempParticipant["username"] && $tempParticipant["old_username"] ? $tempParticipant["old_username"] : $tempParticipant["username"]; ?></td>
        <td <?php echo $tempParticipant["insert_user"] ? $insertStyle : ($tempParticipant["update_password"] ? $updateStyle : $unchangedStyle); ?>><?php echo $tempParticipant["password"]; ?></td>
        <td <?php echo $tempParticipant["insert_user"] ? $insertStyle : ($tempParticipant["update_dm_status"] || $tempParticipant["update_participant_status"] ? $updateStyle : $unchangedStyle); ?>><?php echo ucwords($tempParticipant["status"]); ?></td>
        <td <?php echo $tempParticipant["insert"] || $tempParticipant["insert_user"] ? $insertStyle : ($tempParticipant["update"] || $tempParticipant["insert_user_link"] ? $updateStyle : $unchangedStyle); ?>><?php echo ucwords($tempParticipant["import_action"]); ?></td>
    </tr>
    <?php
    } ?>
    </tbody>
</table>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function() {
        oTable = $('#participantImportTable').dataTable( {
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "sPaginationType": "bootstrap",
            "aoColumns": [
                { "aTargets": [ 0 ], "sClass": "hidden"  },
                { "sClass": "center", "iDataSort": 0 },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" },
                { "sClass": "" }
            ],
            "aaSorting": [[ 0, "asc" ]]
        });
        $("#importParticipantsConfirmAnchor").on('click', function() {
            $.blockUI();
        })
    });
</script>
<?php } ?>