<?php
$adminSession = new Zend_Session_Namespace('administrators'); ?>
<h4 style="width:100%;height:60px;border-bottom:1px solid #777;">
    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">List of All PE Participants</div>
    <div style="margin-top:10px; float: right;">
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'add'), 'default', true); ?>" class="btn btn-primary"><i class="icon-user"></i>&nbsp;Add New Participant</a>
        <?php
        if ($adminSession->is_ptcc_coordinator == 0) { ?>
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'download-import-template'), 'default', true); ?>" class="btn btn-warning" style="margin-left: 10px;"><i class="icon-table"></i>&nbsp;Download Import Template</a>
        <a id="importParticipantsExcelAnchor" href="#" class="btn btn-success" style="margin-left: 10px;"><i class="icon-table"></i>&nbsp;Import Participants</a>
        <?php
        } ?>
    </div>
</h4>
<a href="/admin/participants/pending" class="btn btn-warning">Show only Pending Participants</a>
<br/>
<br/>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="participantsTable">
    <thead>
    <tr>
        <th class="hidden"></th>
        <th>Participant ID</th>
        <th>Lab Name/Participant Name</th>
        <th>Country</th>
        <th>Cell/Mobile</th>
        <th>Phone</th>
        <th>Affiliation</th>
        <th>Email</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td colspan="10" class="dataTables_empty">Loading data from server</td>
    </tr>
    </tbody>
</table>
<?php
if ($adminSession->is_ptcc_coordinator == 0) { ?>
<form name="participantImportForm" id="participantImportForm" enctype="multipart/form-data" action="<?php echo $this->url(array("module" => "admin", "controller" => "participants", "action" => "import"), 'default', true) ?>" method="post">
    <input type="file" id="importParticipantsExcelFile" name="importParticipantsExcelFile" style="visibility: hidden; width: 1px; height: 1px; display: none;" accept=".xlsx,.xls" />
</form>
    <?php
} ?>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function() {
        oTable = $('#participantsTable').dataTable( {
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": true,
            "bdestroy": false,
            "aoColumns": [
                { "aTargets": [ 0 ], "sClass": "hidden"  },
                { "sClass":"center", "iDataSort": 0 },
                { "sClass":"" },
                { "sClass":"center" },
                { "sClass":"center" },
                { "sClass":"center" },
                { "sClass":"center" },
                { "sClass":"" },
                { "sClass":"center" },
                { "sClass":"center", "bSortable":false }
            ],
            "aaSorting": [[ 0, "asc" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'participants', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
        <?php
        if ($adminSession->is_ptcc_coordinator == 0) { ?>
        $('#importParticipantsExcelAnchor').on('click', function() {
            $('#importParticipantsExcelFile').trigger('click');
        });
        $('#importParticipantsExcelFile').on('change', function () {
            $.blockUI();
            $('#participantImportForm').submit();
        });
        <?php
        } ?>
    });
</script>