<?php
$shipmentData = $this->shipmentData;
$vHelper = $this->getHelper('DateFormat');
$dtFormat=  $vHelper->getDateFormat(); ?>
<link rel="stylesheet" href="<?php echo $this->baseUrl("css/bootstrap-modal.css"); ?>" type="text/css" media="all">
<style type="text/css">
	.modal-scrollable {
		z-index: 1000 !important;
	}
	.modal-backdrop {
		z-index: 900 !important;
	}
	#mbd {
        overflow-y:scroll;
        max-height:100%;
    }
</style>
<div class="well">
	<fieldset>
		<legend>Update Shipment Sample Details - <?php echo $shipmentData['shipment']['shipment_code']; ?></legend>
        <form class="form-horizontal" name="shipmentForm" id="shipmentForm" method="post"
              action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment', 'action' => 'edit')); ?>"
              autocomplete="off">
            <div class="form-group">
                <label class="col-lg-3 control-label">Distribution Code </label>
                <div class="col-lg-5">
					<input type='text' disabled='disabled' class ='form-control'
                           value='<?php echo $shipmentData['shipment']['distribution_code']; ?>' />
				</div>
				<input type="hidden" name="shipmentId" id="shipmentId"
                       value="<?php echo $shipmentData['shipment']['shipment_id']; ?>" class="isRequired"
                       title="Please choose a Scheme Type on the top of this page" />
				<input type="hidden" name="selectedDistribution" id="selectedDistribution" class=""
                       value="<?php echo $this->selectedDistribution; ?>" />
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Shipment Code </label>
                <div class="col-lg-5">
					<input type='text' name="shipmentCode" id="shipmentCode" class ='form-control isRequired' value='<?php echo $shipmentData['shipment']['shipment_code']; ?>' title="Please enter the Shipment Code" />
				</div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Result Due Date</label>
                <div class="col-lg-5">
                    <input type='text' readonly='readonly' name="lastDate" id="lastDate"
                           class='form-control datepicker isRequired'
                           value='<?php echo $this->dateFormat($shipmentData['shipment']['lastdate_response']); ?>'
                           title="Please choose the last response date" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Is Official</label>
                <div class="col-lg-5">
                    <select name="isOfficial" class="isRequired form-control"
                            title="Official?"
                            placeholder="Official?">
                        <option value="yes" <?php echo ($shipmentData['shipment']['is_official'] == "1" ? "selected='selected'" : ""); ?>>
                            Yes
                        </option>
                        <option value="no" <?php echo ($shipmentData['shipment']['is_official'] == "0" ? "selected='selected'" : ""); ?>>
                            No
                        </option>
                    </select>
                </div>
            </div>
            <div class="form-group" id="sampleFormFragment">
                <table style="width: 1050px;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix">
                    <tbody>
                    <?php $counter = 1;
                    foreach ($shipmentData['reference'] as $reference) { ?>
                        <tr align="center">
                            <th style="text-align: center;vertical-align:middle;" colspan="11">Sample <?php echo $counter; ?></th>
                        </tr>
                        <tr align="center">
                            <th style="width:18%;text-align: center;vertical-align:middle;">Name</th>
                            <th style="width:9%;vertical-align:middle;">MTB/RIF</th>
                            <th style="width:12%;vertical-align:middle;">MTB Detected</th>
                            <th style="width:14%;vertical-align:middle;">Rif Resistance</th>
                            <th style="width:7%;text-align: center;vertical-align:middle;">Probe D</th>
                            <th style="width:12%;text-align: center;vertical-align:middle;">Probe C</th>
                            <th style="width:7%;text-align: center;vertical-align:middle;">Probe E</th>
                            <th style="width:7%;text-align: center;vertical-align:middle;">Probe B</th>
                            <th style="width:7%;text-align: center;vertical-align:middle;">SPC</th>
                            <th style="width:7%;text-align: center;vertical-align:middle;">Probe A</th>
                        </tr>
                        <tr>
                            <td>
                                <input type="text" name="sampleName[]" class="isRequired input-sm form-control"
                                       value="<?php echo $reference['sample_label']; ?>" />
                            </td>
                            <td>
                                <select name="mtb_rif_excluded[]" class="isRequired form-control input-sm"
                                        title="Do you wish to exclude this sample from evaluation and scoring of MTB/Rif submissions?"
                                        placeholder="Do you wish to exclude this sample from evaluation and scoring of MTB/Rif submissions?"
                                        onChange="changeExcluded(this, '<?php echo $counter; ?>')">
                                    <option value="yes_not_exempt" <?php echo ($reference['mtb_rif_is_excluded'] == 'yes' && $reference['mtb_rif_is_exempt'] == 'no' ? "selected='selected'" : ""); ?>>
                                        Exclude MTB/Rif Results from Evaluation
                                    </option>
                                    <option value="yes_exempt" <?php echo ($reference['mtb_rif_is_excluded'] == 'yes' && $reference['mtb_rif_is_exempt'] == 'yes' ? "selected='selected'" : ""); ?>>
                                        Score 100% for all MTB/Rif Submissions
                                    </option>
                                    <option value="no" <?php echo ($reference['mtb_rif_is_excluded'] == 'no' ? "selected='selected'" : ""); ?>>
                                        Don't Exclude MTB/Rif Submissions
                                    </option>
                                </select>
                            </td>
                            <td>
                                <select name="mtbDetectedMtbRif[]" class="isRequired form-control input-sm"
                                        title="Please enter the MTB Detected for this sample"
                                        placeholder="Please enter the MTB Detected for this sample">
                                    <option value="">-- Select --</option>
                                    <option value="high" <?php echo ($reference['mtb_rif_mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>
                                        High
                                    </option>
                                    <option value="medium" <?php echo ($reference['mtb_rif_mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>
                                        Medium
                                    </option>
                                    <option value="low" <?php echo ($reference['mtb_rif_mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>
                                        Low
                                    </option>
                                    <option value="veryLow" <?php echo ($reference['mtb_rif_mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>
                                        Very Low
                                    </option>
                                    <option value="notDetected" <?php echo ($reference['mtb_rif_mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                        Not Detected
                                    </option>
                                    <option value="noResult" <?php echo ($reference['mtb_rif_mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>
                                        No Result
                                    </option>
                                    <option value="invalid" <?php echo ($reference['mtb_rif_mtb_detected'] == 'invalid' ? "selected='selected'" : ""); ?>>
                                        Invalid
                                    </option>
                                    <option value="error" <?php echo ($reference['mtb_rif_mtb_detected'] == 'error' ? "selected='selected'" : ""); ?>>
                                        Error
                                    </option>
                                </select>
                            </td>
                            <td>
                                <select name="rifResistanceMtbRif[]" class="isRequired form-control input-sm"
                                        title="Please enter the Rif Resistance for this sample"
                                        placeholder="Please enter the Rif Resistance for this sample">
                                    <option value="">-- Select --</option>
                                    <option value="detected" <?php echo ($reference['mtb_rif_rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>
                                        Detected
                                    </option>
                                    <option value="notDetected"  <?php echo ($reference['mtb_rif_rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                        Not Detected
                                    </option>
                                    <option value="indeterminate"  <?php echo ($reference['mtb_rif_rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>
                                        RIF Indeterminate
                                    </option>
                                    <option value="na"  <?php echo ($reference['mtb_rif_rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>
                                        N/A
                                    </option>
                                </select>
                            </td>
                            <td>
                                <input type="text" name="probeMtbRifD[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['mtb_rif_probe_d']; ?>" />
                            </td>
                            <td>
                                <input type="text" name="probeMtbRifC[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['mtb_rif_probe_c']; ?>" />
                            </td>
                            <td>
                                <input type="text" name="probeMtbRifE[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['mtb_rif_probe_e']; ?>" />
                            </td>
                            <td>
                                <input type="text" name="probeMtbRifB[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['mtb_rif_probe_b']; ?>" />
                            </td>
                            <td>
                                <input type="text" name="probeMtbRifSpc[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['mtb_rif_probe_spc']; ?>" />
                            </td>
                            <td>
                                <input type="text" name="probeMtbRifA[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['mtb_rif_probe_a']; ?>" />
                            </td>
                        </tr>
                        <tr>
                            <th style="text-align: center;vertical-align:middle;">Content</th>
                            <th style="vertical-align:middle;">MTB Ultra</th>
                            <th style="vertical-align:middle;">MTB Detected</th>
                            <th style="vertical-align:middle;">Rif Resistance</th>
                            <th style="text-align: center;vertical-align:middle;">SPC</th>
                            <th style="text-align: center;vertical-align:middle;">IS1081-IS6110</th>
                            <th style="text-align: center;vertical-align:middle;">rpoB1</th>
                            <th style="text-align: center;vertical-align:middle;">rpoB2</th>
                            <th style="text-align: center;vertical-align:middle;">rpoB3</th>
                            <th style="text-align: center;vertical-align:middle;">rpoB4</th>
                        </tr>
                        <tr>
                            <td>
                                <select name="sampleContent[]" class="form-control input-sm"
                                        title="Please enter the organism used for this sample"
                                        placeholder="Please enter the organism used for this sample">
                                    <option value="">-- Select --</option>
                                    <option value="0.85% Saline, CDC-ILB in-house prepared" <?php echo ($reference['sample_content'] == '0.85% Saline, CDC-ILB in-house prepared' ? "selected='selected'" : ""); ?>>0.85% Saline, CDC-ILB in-house prepared</option>
                                    <option value="M. kansasii, ATCC 12478" <?php echo ($reference['sample_content'] == 'M. kansasii, ATCC 12478' ? "selected='selected'" : ""); ?>>M. kansasii, ATCC 12478</option>
                                    <option value="M. gordonae, ATCC 14470" <?php echo ($reference['sample_content'] == 'M. gordonae, ATCC 14470' ? "selected='selected'" : ""); ?>>M. gordonae, ATCC 14470</option>
                                    <option value="M. fortuitum, ATCC 6841" <?php echo ($reference['sample_content'] == 'M. fortuitum, ATCC 6841' ? "selected='selected'" : ""); ?>>M. fortuitum, ATCC 6841</option>
                                    <option value="M. intracellularae, ATCC 13950" <?php echo ($reference['sample_content'] == 'M. intracellularae, ATCC 13950' ? "selected='selected'" : ""); ?>>M. intracellularae, ATCC 13950</option>
                                    <option value="M. bovis, ATCC 35729" <?php echo ($reference['sample_content'] == 'M. bovis, ATCC 35729' ? "selected='selected'" : ""); ?>>M. bovis, ATCC 35729</option>
                                    <option value="M. tuberculosis, H37Rv ATCC 27294" <?php echo ($reference['sample_content'] == 'M. tuberculosis, H37Rv ATCC 27294' ? "selected='selected'" : ""); ?>>M. tuberculosis, H37Rv ATCC 27294</option>
                                    <option value="M. tuberculosis, ATCC 35810" <?php echo ($reference['sample_content'] == 'M. tuberculosis, ATCC 35810' ? "selected='selected'" : ""); ?>>M. tuberculosis, ATCC 35810</option>
                                    <option value="M. tuberculosis, ATCC 35811" <?php echo ($reference['sample_content'] == 'M. tuberculosis, ATCC 35811' ? "selected='selected'" : ""); ?>>M. tuberculosis, ATCC 35811</option>
                                    <option value="H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (S522L)" <?php echo ($reference['sample_content'] == 'H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (S522L)' ? "selected='selected'" : ""); ?>>H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (S522L)</option>
                                    <option value="H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (H526Y)" <?php echo ($reference['sample_content'] == 'H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (H526Y)' ? "selected='selected'" : ""); ?>>H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (H526Y)</option>
                                    <option value="H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (S531L)" <?php echo ($reference['sample_content'] == 'H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (S531L)' ? "selected='selected'" : ""); ?>>H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (S531L)</option>
                                    <option value="H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (H526D)" <?php echo ($reference['sample_content'] == 'H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (H526D)' ? "selected='selected'" : ""); ?>>H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (H526D)</option>
                                    <option value="M. tuberculosis, WHO strain 2116, mutation in the rpoB gene (A516V)" <?php echo ($reference['sample_content'] == 'M. tuberculosis, WHO strain 2116, mutation in the rpoB gene (A516V)' ? "selected='selected'" : ""); ?>>M. tuberculosis, WHO strain 2116, mutation in the rpoB gene (A516V)</option>
                                    <option value="M. tuberculosis, WHO strain 3201, mutation in the rpoB gene (H526T)" <?php echo ($reference['sample_content'] == 'M. tuberculosis, WHO strain 3201, mutation in the rpoB gene (H526T)' ? "selected='selected'" : ""); ?>>M. tuberculosis, WHO strain 3201, mutation in the rpoB gene (H526T)</option>
                                </select>
                            </td>
                            <td>
                                <select name="ultra_excluded[]" class="isRequired form-control input-sm"
                                        title="Do you wish to exclude this sample from evaluation and scoring of ultra submissions?"
                                        placeholder="Do you wish to exclude this sample from evaluation and scoring of ultra submissions?"
                                        onChange="changeExcluded(this, '<?php echo $counter; ?>')">
                                    <option value="yes_not_exempt" <?php echo ($reference['ultra_is_excluded'] == 'yes' && $reference['ultra_is_exempt'] == 'no' ? "selected='selected'" : ""); ?>>
                                        Exclude Ultra Results from Evaluation
                                    </option>
                                    <option value="yes_exempt" <?php echo ($reference['ultra_is_excluded'] == 'yes' && $reference['ultra_is_exempt'] == 'yes' ? "selected='selected'" : ""); ?>>
                                        Score 100% for all Ultra Submissions
                                    </option>
                                    <option value="no" <?php echo ($reference['ultra_is_excluded'] == 'no' ? "selected='selected'" : ""); ?>>
                                        Don't Exclude Ultra Submissions
                                    </option>
                                </select>
                            </td>
                            <td>
                                <select name="mtbDetectedUltra[]" class="isRequired form-control input-sm"
                                        title="Please enter the MTB Detected for this sample"
                                        placeholder="Please enter the MTB Detected for this sample">
                                    <option value="">-- Select --</option>
                                    <option value="high" <?php echo ($reference['ultra_mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>
                                        High
                                    </option>
                                    <option value="medium" <?php echo ($reference['ultra_mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>
                                        Medium
                                    </option>
                                    <option value="low" <?php echo ($reference['ultra_mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>
                                        Low
                                    </option>
                                    <option value="veryLow" <?php echo ($reference['ultra_mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>
                                        Very Low
                                    </option>
                                    <option value="trace" <?php echo ($reference['ultra_mtb_detected'] == 'trace' ? "selected='selected'" : ""); ?>>
                                        Trace
                                    </option>
                                    <option value="notDetected" <?php echo ($reference['ultra_mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                        Not Detected
                                    </option>
                                    <option value="noResult" <?php echo ($reference['ultra_mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>
                                        No Result
                                    </option>
                                    <option value="invalid" <?php echo ($reference['ultra_mtb_detected'] == 'invalid' ? "selected='selected'" : ""); ?>>
                                        Invalid
                                    </option>
                                    <option value="error" <?php echo ($reference['ultra_mtb_detected'] == 'error' ? "selected='selected'" : ""); ?>>
                                        Error
                                    </option>
                                </select>
                            </td>
                            <td>
                                <select name="rifResistanceUltra[]" class="isRequired form-control input-sm"
                                        title="Please enter the Rif Resistance for this sample"
                                        placeholder="Please enter the Rif Resistance for this sample">
                                    <option value="">-- Select --</option>
                                    <option value="detected" <?php echo ($reference['ultra_rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>
                                        Detected
                                    </option>
                                    <option value="notDetected"  <?php echo ($reference['ultra_rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                        Not Detected
                                    </option>
                                    <option value="indeterminate"  <?php echo ($reference['ultra_rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>
                                        RIF Indeterminate
                                    </option>
                                    <option value="na"  <?php echo ($reference['ultra_rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>
                                        N/A
                                    </option>
                                </select>
                            </td>
                            <td>
                                <input type="text" name="probeUltraSpc[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['ultra_probe_spc']; ?>" />
                            </td>
                            <td>
                                <input type="text" name="probeUltraIS1081IS6110[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['ultra_probe_is1081_is6110']; ?>" />
                            </td>
                            <td>
                                <input type="text" name="probeUltraRpoB1[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['ultra_probe_rpo_b1']; ?>" />
                            </td>
                            <td>
                                <input type="text" name="probeUltraRpoB2[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['ultra_probe_rpo_b2']; ?>" />
                            </td>
                            <td>
                                <input type="text" name="probeUltraRpoB3[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['ultra_probe_rpo_b3']; ?>" />
                            </td>
                            <td>
                                <input type="text" name="probeUltraRpoB4[]" class="form-control input-sm oneDecimal"
                                       title="Please enter all Ct values for each sample"
                                       placeholder="Please enter all Ct values for each sample"
                                       value="<?php echo $reference['ultra_probe_rpo_b4']; ?>" />
                            </td>
                        </tr>
                        <tr id="excludedReasonRow<?php echo $counter; ?>" style="display: <?php echo ($reference['mtb_rif_is_excluded'] == 'yes' || $reference['mtb_rif_is_exempt'] == 'yes' || $reference['ultra_is_excluded'] == 'yes' || $reference['ultra_is_exempt'] == 'yes') ? 'table-row' : 'none'?>;">
                            <td colspan="2">
                                <label for="excludedReason[]">Excluded Reason</label>
                            </td>
                            <td colspan="9">
                                <input type="text" name="excludedReason[]" class="form-control input-sm"
                                       title="Please enter the reason that this sample was excluded. This will appear on reports that are sent back out to participants"
                                       placeholder="Reason for exclusion" value="<?php echo $reference['excluded_reason']; ?>" />
                            </td>
                        </tr>
                        <?php
                        $counter++;
                    } ?>
                    </tbody>
                </table>
                <br />
            </div>
            <div style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary btn-sm" type="button"
                       onclick="validateNow();return false;" tabindex="7" value="Update Shipment" />
                <input class="btn btn-danger btn-sm" type="button" onclick="window.history.go(-1);"
                       tabindex="8" value="Cancel"/>
            </div>
        </form>
    </fieldset>
</div>
<script>
  var duplicated = false;
  function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
    if (obj.val() == "" || obj.val() == null) {
      return;
    }
    $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", { tableName: tableName, fieldName: fieldName, value: obj.val(), fnct: fnct, format: "html" },
      function (data) {
        if (data > 0) {
          alert(msg, "err");
          duplicated = true;
          obj.focus();
        } else {
          duplicated = false;
        }
    });
  }

  <?php
  $vHelper = $this->getHelper('DateFormat');
  $dtFormat=  $vHelper->getDateFormat(); ?>
  $(document).ready(function(){
    $(".datepicker" ).datepicker({dateFormat: '<?php echo $dtFormat;?>'});
    $("body").on("change",'select.controlOrNot',function(){
      var scoreElem = $(this).parent().parent().find('.score');
      if ($(this).val() == 1) {
        $(scoreElem).val(0);
        $(scoreElem).attr('readonly','readonly');
      } else {
        $(scoreElem).removeAttr('readonly');
      }
    });
  });

  function validateNow() {
    checkDuplicate('shipment', 'shipment_code', $("#shipmentCode"),
      '<?php echo "shipment_id##" . $shipmentData['shipment']['shipment_id']; ?>',
      'This Code already exists for another Shipment. Please try something else.');
    var flag = deforayValidator.init({
      formId: 'shipmentForm'
    });
    if (flag && !duplicated) {
      $.blockUI();
      document.getElementById('shipmentForm').submit();
    }
  }

  function changeExcluded(excludedDropDown, rowNumber) {
    var excludedReasonRow = $("#excludedReasonRow" + rowNumber);
    if ($(excludedDropDown).val() === 'no') {
      excludedReasonRow.css('display', 'none');
      excludedReasonRow.find('intput').val('');
    } else {
      excludedReasonRow.css('display', 'table-row');
    }
  }
</script>
