<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.dataTables.css"); ?>" type="text/css" media="all">

<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">
        Shipments
    </div>
    <div style="margin-top:10px;">
        <a class="btn btn-primary" onclick="newShipment();"  style="float:right;">
            <i class="icon-plus"></i>
            &nbsp;&nbsp;Create Panel
        </a>
    </div>
</h4>
<input type="hidden" id="scheme" name="scheme" value="<?php echo $this->schemes[0]['scheme_id']; ?>"  >
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover"
       id="shipmentTable">
    <thead>
        <tr>
            <th>Shipment Code</th>
            <th>Scheme Type</th>
            <th>PE Survey Code</th>
            <th>PE Survey Date</th>
            <th>Result Due Date</th>
            <th>No. of Samples</th>
            <th>No. of Participants Selected</th>
            <th>Response Switch</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="10" class="dataTables_empty">Loading data from server</td>
        </tr>
    </tbody>
</table>
<br />
<br />
<br />
<div style="display:none;clear:both;padding:30px;" id="configShipment">
    <fieldset>
        <legend style="font-size:17px;">Add Shipment Details</legend>
        <form class="form-horizontal" name="shipmentForm" id="shipmentForm" method="post" action="<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment', 'action' => 'add')); ?>" autocomplete="off">
            <div class="form-group">
               
                <input type="hidden" name="selectedDistribution" id="selectedDistribution" class="" value="<?php echo $this->selectedDistribution; ?>"/>
            </div>
            <div id="isFollowUpContainer" class="form-group" style="display: none;">
                <div class="col-lg-5 col-lg-offset-3">
                    <input type="checkbox" id="isFollowUp" name="isFollowUp" onchange="isFollowChanged()"/>
                    <label class="control-label" for="isFollowUp">Is Follow Up From Previous Shipment</label>
                </div>
            </div>
            <div id="followsUpFromContainer" class="form-group" style="display: none;">
                <label class="col-lg-3 control-label" for="followsUpFrom">Follows Up From <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <select id="followsUpFrom" name="followsUpFrom" class="form-control input-sm" title="Please select a a shipment that this shipment follows up on">
                        <option value="">--Select--</option>
                        <?php
                        foreach ($this->tbShipments as $tbShipment) { ?>
                        <option value="<?php echo $tbShipment['shipment_id']; ?>">
                            <?php echo $tbShipment['distribution_code'] . " / " . $tbShipment['shipment_code'] . " due on " . $this->dateFormat($tbShipment['lastdate_response']); ?>
                        </option>
                        <?php
                        } ?>
                    </select>
                </div>
            </div>
            <div id="followsUpAutoEnrollContainer" class="form-group" style="display: none;">
                <div class="col-lg-5 col-lg-offset-3">
                    <input type="checkbox" id="autoEnroll" name="autoEnroll" />
                    <label class="control-label" for="autoEnroll">Enroll All Participants from Previous Shipment</label>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Shipment Code <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="text" id="shipmentCode" name="shipmentCode" size="50" maxlength="45" 
                            onblur="checkDuplicate('shipment', 'shipment_code', $('#shipmentCode'), null, 'This Code already exists for another Shipment. Please try something else.')"
                           class="isRequired form-control input-sm"
                           title="Please enter the shipment code here"
                           placeholder="Please enter the shipment code here"
                           value="<?php if(isset($distributionCode)){ echo $distributionCode; }?>"
                           onchange="SetShipmentCode()"
                    />
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Result Due Date <span class="mandatory">*</span></label>
                <div class="col-lg-5">
                    <input type="text" id="lastDate" name="lastDate" size="50" maxlength="45" readonly="readonly"
                           class="isRequired form-control input-sm datepicker"
                           title="Please enter the last date here"
                           placeholder="Please enter the last date here"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Is Official</label>
                <div class="col-lg-5">
                    <select name="isOfficial" id="isOfficial" class="isRequired form-control input-sm"
                            title="Official?"
                            placeholder="Official?">
                        <option value="yes" selected>Yes</option>
                        <option value="no">No</option>
                    </select>
                </div>
            </div>
            <div class="form-group" id="sampleFormFragment">
            </div>
            <div style="margin: 0px auto 0px auto; text-align: center;" align="center">
                <input name="submitbtn" class="btn btn-primary btn-sm" type="button" onclick="validateNow();
                        return false;"
                       tabindex="7" value="Add Shipment"/>
                <input class="btn btn-danger btn-sm" type="button" onclick="document.location.href = document.location;"
                       tabindex="8" value="Cancel"/>
            </div>
        </form>
    </fieldset>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

</div>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var counter=0;
    var oTable = null;
    var duplicated = false;
    function SetShipmentCode() {
        var shipmentCode=document.getElementById('shipmentCode').value;
        $("input[name='sampleName[]']").each(function(index){
            counter+=1;
            if($(this).val()<0)
                $(this).val(shipmentCode+"-"+counter);
        });
    }

    function checkDuplicate(tableName, fieldName, obj, fnct, msg) {
        if (obj.val() == "" || obj.val() == null) {
            return;
        }
        $.post("<?php echo $this->url(array('module' => 'default', 'controller' => 'common', 'action' => 'check-duplicate')); ?>", {tableName: tableName, fieldName: fieldName, value: obj.val(), fnct: fnct, format: "html"},
        function (data) {
            if (data > 0) {
                alert(msg, "err");
                duplicated = true;
                obj.focus();
            } else {
                duplicated = false;
            }
        });
    }



    $(document).ready(function () {
        $("body").on("change", 'select.controlOrNot', function () {
            var scoreElem = $(this).parent().parent().find('.score');
            if ($(this).val() == 1) {
                $(scoreElem).val(0);
                $(scoreElem).attr('readonly', 'readonly');
            } else {
                $(scoreElem).removeAttr('readonly');
            }
        });
        drawTable();
        $(".datepicker").datepicker({dateFormat: '<?php echo $this->defaultDateFormat(); ?>'});
    });

  function validateNow() {
        checkDuplicate('shipment', 'shipment_code', $('#shipmentCode'), null, 'This Code already exists for another Shipment. Please try something else.');
        flag = deforayValidator.init({
            formId: 'shipmentForm'
        });
        if (flag && !duplicated) {
            $.blockUI();
            document.getElementById('shipmentForm').submit();
        }
    }
    function responseSwitch(switchStatus,sid) {
        if (window.confirm("Are you sure you wish to switch this shipment "+switchStatus+" ?")) {
            $.blockUI();
            $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment', 'action' => 'response-switch')); ?>", {sid: sid,switchStatus: switchStatus, format: "html"},
            function (data) {
                alert(data);
                drawTable();
                $.unblockUI();
            });
        } else {
            drawTable();
        }
    }
    function removeShipment(sidEncoded, sid) {
        if (window.confirm("Are you sure you wish to delete? This cannot be undone!")) {
            $.blockUI();
            $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment', 'action' => 'remove')); ?>", {sid: sidEncoded, format: "html"},
            function (data) {
                if (data) {
                    alert(data);
                } else {
                    $('#followsUpFrom option[value="' + sid + '"]').remove();
                }
                drawTable();
                $.unblockUI();
            });
        }
    }
    function drawTable() {
        oTable = $('#shipmentTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page",
                "sEmptyTable": "No shipment schemes under this Distribution yet"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": false,
            "bDestroy": true,
            "aoColumns": [
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center", "bSortable": false}
            ],
            "aaSorting": [[3, "desc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerParams": function (aoData) {
                aoData.push({"name": "distribution", "value": '<?php echo $this->selectedDistribution ?>'});
            },
            "fnServerData": function (sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }, "fnRowCallback": function (nRow, aData, iDisplayIndex) {
                $('td.sorting_1').addClass('goga');
            },
        });
<?php
if (isset($this->searchData) && $this->searchData != '') { ?>
     oTable.fnFilter('<?php echo $this->searchData; ?>');
<?php
} ?>
    }

    function newShipment() {
        getSampleForm();
        $("#configShipment").fadeIn('fast', function () {
            $('html,body').animate({scrollTop: ($("#configShipment").offset().top - 50)}, 1300, function () {
                $("#configShipment").effect("highlight", 2000);
            });
        });
    }
    function getSampleForm() {
        $.blockUI();
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'shipment', 'action' => 'get-sample-form')); ?>", { format: "html"},
        function (data) {
            $("#sampleFormFragment").html(data);
                $("#isFollowUpContainer").css('display', 'block');
            $.unblockUI();
        });
    }

    function isFollowChanged () {
        if ($("#isFollowUp").prop('checked')) {
            $("#followsUpFromContainer").css('display', 'block');
            $("#followsUpAutoEnrollContainer").css('display', 'block');
            $("#autoEnroll").prop('checked',true);
            $("#followsUpFrom").addClass('isRequired');
        } else {
            $("#followsUpFromContainer").css('display', 'none');
            $("#followsUpFrom").val('');
            $("#followsUpAutoEnrollContainer").css('display', 'none');
            $("#autoEnroll").prop('checked',false);
            $("#followsUpFrom").removeClass('isRequired');
        }
    }

    function mailShipment(sid) {
        layoutModal('/admin/shipment/edit-shipment-email/id/' + sid + '/mail_purpose/new_shipment/', '980', '550');
    }

    function generateForms(sid) {
      layoutModal('/reports/shipment/generate-forms/sid/' + sid, '980', '550');
    }

    $('#myModal').on('hidden.bs.modal', function () {
      $(this).removeData('bs.modal');
    });

	function shipDistribution(did) {
		var choice = confirm("Are you sure you want to ship this PE Survey ? \n You cannot undo this !");
		if (!choice) {
			return false;
		}
		$.blockUI();
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'distributions', 'action' => 'ship-distribution')); ?>", { did: did, format: "html" },
            function (data) {
                alert(data);
			    oTable.fnDraw();
			    $.unblockUI();
            });
	}
</script>
