
<link href="<?php echo $this->baseUrl('css/hummingbird-treeview.css'); ?>" rel="stylesheet" type="text/css">

<fieldset>
    <legend>
        <?php echo strtoupper($this->shipment->scheme_type); ?>
        &nbsp;Shipment :
        &nbsp;<?php echo $this->shipment->shipment_code . "(".$this->dateFormat($this->shipment->shipment_date).") "; ?>
    </legend>
    <form method="post" action="" id="shipForm">
	    <div class="form-group">
            <div id="treeview_container" class="hummingbird-treeview well h-scroll-large" style="background-color: white">
                <ul id="treeview" class="hummingbird-base">
            <?php
            foreach ($this->countries as $ckey => $country) { 
            ?>

                    <li><i class="fa fa-minus"></i> 
                        <label> 
                            <input id="node-<?php echo $ckey; ?>" data-id="custom-<?php echo $ckey; ?>" type="checkbox"  <?php if(count($country["unenrolled_participants"]) == 0) {  ?> checked="true" <?php  } ?>>
                            <?php echo $country["iso_name"]; ?>
                        </label>
                        <ul style="display: block;">
                            <?php foreach ($country["enrolled_participants"] as $key => $participant) { ?>
                                <li>
                                    <label> 
                                        <input  class="participant_checkbox" name="participants[]" type="checkbox" value="<?php echo $participant['participant_id']; ?>"  checked="true">
                                        <?php echo $participant['lab_name']; ?>
                                        (<?php echo $participant['participant_id']; ?>)
                                        (<?php echo $participant['unique_identifier']; ?>)
                                    </label>
                                </li>
                            <?php } ?>
                            <?php foreach ($country["unenrolled_participants"] as $key => $participant) { ?>
                                <li>
                                    <label> 
                                        <input  class="participant_checkbox" name="participants[]" type="checkbox" value="<?php echo $participant['participant_id']; ?>">
                                        <?php echo $participant['lab_name']; ?>
                                        (<?php echo $participant['participant_id']; ?>)
                                        (<?php echo $participant['unique_identifier']; ?>)
                                    </label>
                                </li>
                            <?php } ?>
                        </ul>
                    </li>
            <?php } ?>
                </ul>
            </div>
	    </div>
	    <input type="hidden" id="shipmentId" name="shipmentId" value="<?php echo $this->shipment->shipment_id; ?>" />
	    <div class="form-group" style="margin-left:230px;display:none;">
	        <label class="col-lg-4 control-label">Optional Enrollment Identifier</label>
	        <div class="col-lg-4">
                <input id="enrollmentName" name="enrollmentName" size="50" maxlength="45"
                       class="form-control input-sm" title="Enter an optional name for this enrollment"
                       placeholder="Enter an optional name for this enrollment" />
            </div>
	    </div>
	    <div style="clear:both;margin: 90px auto 30px auto; text-align: center;" align="center">
	        <input name="submitbtn" class="btn btn-primary btn-sm" type="button" onclick="validateNow(); return true;"
                   tabindex="7" value="Enroll"/>
	        <input class="btn btn-danger btn-sm" type="button" onclick="window.history.go(-1);"
                   tabindex="8" value="Cancel"/>
	    </div>
    </form>
</fieldset>

<script>
    function validateNow() {
        var numberOfChecked = $('.participant_checkbox:checkbox:checked').length;
        var totalCheckboxes = $('.participant_checkbox:checkbox').length;
        var numberNotChecked = totalCheckboxes - numberOfChecked;

        if (confirm('You have enrolled '+ numberOfChecked +' participants and ' + numberNotChecked + '  unenrolled Participants. Are you sure you want to continue?' )){

            flag = deforayValidator.init({
                formId: 'shipForm'
            });
            if (flag) {
                $.blockUI();
                document.getElementById('shipForm').submit();
            }
        } else {
            return false;
        }
    }
</script>

<script src="<?php echo $this->baseUrl('js/hummingbird-treeview.js'); ?>" ></script>

<script>
$("#treeview").hummingbird();
$( "#checkNode" ).click(function() {
  $("#treeview").hummingbird("checkNode",{attr:"id",name: "node-0-2-2",expandParents:false});
});
</script>




