
<link href="<?php echo $this->baseUrl('css/hummingbird-treeview.css'); ?>" rel="stylesheet" type="text/css"/>

<div style="height: 100%">

    <legend class="row">
            <?php echo strtoupper($this->shipment->scheme_type); ?>
            &nbsp;Shipment:
            &nbsp;<?php echo $this->shipment->shipment_code . " (" . $this->dateFormat($this->shipment->shipment_date) . ") "; ?>
            <span style="float: right; padding-bottom:10px;"  >
                Search:
                <input type="text" id="searchBox" placeholder="Search"  onkeyup="search()">
            </span>
    </legend>
    <div style="font-style: italic;font-size: 16px;letter-spacing: 2px;font-weight: bold;" class="text-center" id="ParticipantCalculation">
    </div><hr>
    <form method="post" action="" id="shipForm">
        <div class="container" style="overflow-y: scroll;overflow-x: hidden;border: 2px solid darkgray;border-radius: 5px; height: 70vh;  width: 100%;">
            <div id="treeview_container" class="hummingbird-treeview well h-scroll-large" style="background-color: white">
                <ul id="treeview" class="hummingbird-base">
            <?php
            $i=0;
            foreach ($this->countries as $ckey => $country) {
                $unenrolledParticipants = array_filter($country, function ($participant) { return !isset($participant["map_id"]); });
            ?>
                    <li class="country"><i class="fa fa-minus"></i>
                        <label class="CountryDetails">
                            <input id="node-<?php echo $ckey; ?>" class="countr_checkbox" data-id="custom-<?php echo $ckey; ?>" type="checkbox"  <?php if(count($unenrolledParticipants) == 0) {  ?> checked="true" <?php  } ?>>
                            <span style="width: 50%;">
                                <?php echo $ckey; ?>
                            </span>
                            <span class="dueDate" style="float:right;">
                                <label>Result due date: </label>
                                <input id="country_last_dates_<?php echo $ckey; ?>" type="text" class="input_date" onchange="$(this).attr('name','country_last_dates[<?php  echo $ckey; ?>]')"
                                value="<?php
                                            if($country[$i]['due_date_text']){
                                                echo ($country[$i]['due_date_text']);
                                            }else{
                                                echo ($this->shipment->shipment_date);
                                            }
                                        ?>"
                                        width="40" size="20"
                                        title="Result due date for "
                                        placeholder="Result due date for "
                                        >
                            </span>
                        </label>
                        <ul style="display: block;">
                            <?php foreach ($country as $participant) {
                                $i++; ?>
                                <li>
                                    <label class="ParticipantDetails">
                                        <input id="participant_checkbox_<?php echo $participant['participant_id']; ?>" class="participant_checkbox" name="participants[]" type="checkbox" value="<?php echo $participant['participant_id']; ?>" <?php if(isset($participant['map_id'])) {  ?> checked="true" <?php  } ?>>
                                        <?php echo $participant['unique_identifier']; ?>
                                        &nbsp;-&nbsp;
                                        <?php echo $participant['lab_name']; ?>
                                        &nbsp;-&nbsp;
                                        <span style="visibility: hidden;">
                                        <?php echo $participant['email']; ?>
                                        </span>
                                    </label>
                                </li>
                            <?php } ?>
                        </ul>
                    </li>
                <?php } ?>
                </ul>
            </div>
	    </div>
	    <input type="hidden" id="shipmentId" name="shipmentId" value="<?php echo $this->shipment->shipment_id; ?>" />
	    <div class="form-group" style="margin-left:230px;display:none;">
	        <label class="col-lg-4 control-label">Optional Enrollment Identifier</label>
	        <div class="col-lg-4">
                <input id="enrollmentName" name="enrollmentName" size="50" maxlength="45"
                       class="form-control input-sm" title="Enter an optional name for this enrollment"
                       placeholder="Enter an optional name for this enrollment" />
            </div>
	    </div>

	    <div class="text-center" style="padding-top: 10px;">
	        <input name="submitbtn" class="btn btn-primary btn-sm" type="button" onclick="validateNow(); return true;"
                   tabindex="7" value="Enroll"/>
	        <input class="btn btn-danger btn-sm" type="button" onclick="window.history.go(-1);"
                   tabindex="8" value="Cancel"/>
	    </div>
    </form>

</div>


<script>
    function search(){
        var searchvalue=$("#searchBox").val().toLowerCase();
        if(searchvalue != ""){
            $(".ParticipantDetails").hide();
            $(".CountryDetails").hide();
            $('.ParticipantDetails').each(function( index ) {
                if( $(this).text().toLowerCase().includes(searchvalue)){
                    $(this).show();
                    $(this).closest('.country').find('.CountryDetails').show();
                }
            });
            $(".CountryDetails").each(function( index ) {
                if( $(this).text().toLowerCase().includes(searchvalue)){
                    $(this).show();
                    $(this).closest('.country').find('.ParticipantDetails').show();
                }
            });
        }else{
            $(".ParticipantDetails").show();
            $(".CountryDetails").show();
        }
    }
    function validateNow() {
        var numberOfChecked = $('.participant_checkbox:checkbox:checked').length;
        var totalCheckboxes = $('.participant_checkbox:checkbox').length;
        var numberNotChecked = totalCheckboxes - numberOfChecked;

        if (confirm('You have enrolled '+ numberOfChecked +' participants and ' + numberNotChecked + '  unenrolled Participants. Are you sure you want to continue?' )){
            flag = deforayValidator.init({
                formId: 'shipForm'
            });
            if (flag) {
                $.blockUI();
                document.getElementById('shipForm').submit();
            }
        } else {
            return false;
        }
    }
    $(document).ready(function(){
        $('.participant_checkbox:checked').addClass('selectedParticipant');
        $('.participant_checkbox:not(:checked)').addClass('unselectedParticipant');
        calculateParticipantEnrollment();
    });
    $(".participant_checkbox").change(function(){
        calculateParticipantEnrollment();
    });
    $(".countr_checkbox").change(function(){
      calculateParticipantEnrollment();
    });
    function calculateParticipantEnrollment(){
        $("#ParticipantCalculation").html('<span id="selected">'+$('.participant_checkbox:checked').length+'</span> Participants Selected, Removing <span id="removing">'+ ($('.selectedParticipant').length-$('.selectedParticipant:checked').length) +'</span> Participants and Adding <span id="adding">'+$('.unselectedParticipant:checked').length +' Participants</span>');
    }
</script>

<script src="<?php echo $this->baseUrl('js/hummingbird-treeview.js'); ?>" ></script>

<script>

$("#treeview").hummingbird();
$( "#checkNode" ).click(function() {
  $("#treeview").hummingbird("checkNode",{attr:"id",name: "node-0-2-2",expandParents:false});
});


$( document ).ready(function() {
    dueDateDisplay();
});
$( ".participant_checkbox" ).click(function( index ) {
    dueDateDisplay();
});
$( ".countr_checkbox" ).click(function( index ) {
    dueDateDisplay();
});
function dueDateDisplay(){
    $(".dueDate").hide();
    $( ".participant_checkbox:checked" ).each(function( index ) {
        $(this).closest('.country').find(".dueDate").show();
    });
}

</script>




