<?php
$distributionCode = "";
foreach ($this->unshippedDistro as $dist) {
    if ($dist['distribution_id'] == $this->selectedDistribution) {
        $distributionCode = $dist['distribution_code'];
    }
} ?>
<table style="width: 1050px;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix">
    <tbody>
    <?php
    for ($i = 0; $i < 5; ++$i) {
        $counter = $i + 1; ?>
        <tr align="center">
            <th style="text-align: center;vertical-align:middle;" colspan="10">Sample <?php echo $counter; ?></th>
        </tr>
        <tr align="center">
            <th style="width:10%;text-align: center;vertical-align:middle;">Name</th>
            <th style="width:9%;vertical-align:middle;" rowspan="2">MTB/RIF</th>
            <th style="width:12%;vertical-align:middle;">MTB Detected</th>
            <th style="width:14%;vertical-align:middle;">Rif Resistance</th>
            <th style="width:7%;text-align: center;vertical-align:middle;">Probe D</th>
            <th style="width:12%;text-align: center;vertical-align:middle;">Probe C</th>
            <th style="width:7%;text-align: center;vertical-align:middle;">Probe E</th>
            <th style="width:7%;text-align: center;vertical-align:middle;">Probe B</th>
            <th style="width:7%;text-align: center;vertical-align:middle;">SPC</th>
            <th style="width:7%;text-align: center;vertical-align:middle;">Probe A</th>
        </tr>
        <tr>
            <td>
                <input type="text" name="sampleName[]" class="isRequired input-sm form-control" value="<?php echo $distributionCode."-".$counter; ?>" />
            </td>
            <td>
                <select name="mtbDetectedMtbRif[]" class="isRequired form-control input-sm"
                        title="Please enter the MTB Detected for this sample"
                        placeholder="Please enter the MTB Detected for this sample">
                    <option value="">-- Select --</option>
                    <option value="high">High</option>
                    <option value="medium">Medium</option>
                    <option value="low">Low</option>
                    <option value="veryLow">Very Low</option>
                    <option value="notDetected">Not Detected</option>
                    <option value="noResult">No Result</option>
                    <option value="invalid">Invalid</option>
                    <option value="error">Error</option>
                </select>
            </td>
            <td>
                <select name="rifResistanceMtbRif[]" class="isRequired form-control input-sm"
                        title="Please enter the Rif Resistance for this sample"
                        placeholder="Please enter the Rif Resistance for this sample">
                    <option value="">-- Select --</option>
                    <option value="detected">Detected</option>
                    <option value="notDetected">Not Detected</option>
                    <option value="indeterminate">RIF Indeterminate</option>
                    <option value="na">N/A</option>
                </select>
            </td>
            <td>
                <input type="text" name="probeMtbRifD[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
            <td>
                <input type="text" name="probeMtbRifC[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
            <td>
                <input type="text" name="probeMtbRifE[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
            <td>
                <input type="text" name="probeMtbRifB[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
            <td>
                <input type="text" name="probeMtbRifSpc[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
            <td>
                <input type="text" name="probeMtbRifA[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
        </tr>
        <tr>
            <th style="text-align: center;vertical-align:middle;">Content</th>
            <th style="vertical-align:middle;" rowspan="2">MTB Ultra</th>
            <th style="vertical-align:middle;">MTB Detected</th>
            <th style="vertical-align:middle;">Rif Resistance</th>
            <th style="text-align: center;vertical-align:middle;">SPC</th>
            <th style="text-align: center;vertical-align:middle;">IS1081-IS6110</th>
            <th style="text-align: center;vertical-align:middle;">rpoB1</th>
            <th style="text-align: center;vertical-align:middle;">rpoB2</th>
            <th style="text-align: center;vertical-align:middle;">rpoB3</th>
            <th style="text-align: center;vertical-align:middle;">rpoB4</th>
        </tr>
        <tr>
            <td>
                <select name="sampleContent[]" class="form-control input-sm"
                        title="Please enter the organism used for this sample"
                        placeholder="Please enter the organism used for this sample">
                    <option value="">-- Select --</option>
                    <option value="0.85% Saline, CDC-ILB in-house prepared">0.85% Saline, CDC-ILB in-house prepared</option>
                    <option value="M. kansasii, ATCC 12478">M. kansasii, ATCC 12478</option>
                    <option value="M. gordonae, ATCC 14470">M. gordonae, ATCC 14470</option>
                    <option value="M. fortuitum, ATCC 6841">M. fortuitum, ATCC 6841</option>
                    <option value="M. intracellularae, ATCC 13950">M. intracellularae, ATCC 13950</option>
                    <option value="M. bovis, ATCC 35729">M. bovis, ATCC 35729</option>
                    <option value="M. tuberculosis, H37Rv ATCC 27294">M. tuberculosis, H37Rv ATCC 27294</option>
                    <option value="M. tuberculosis, ATCC 35810">M. tuberculosis, ATCC 35810</option>
                    <option value="M. tuberculosis, ATCC 35811">M. tuberculosis, ATCC 35811</option>
                    <option value="H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (S522L)">H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (S522L)</option>
                    <option value="H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (H526Y)">H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (H526Y)</option>
                    <option value="H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (S531L)">H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (S531L)</option>
                    <option value="H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (H526D)">H37Rv M. tuberculosis parent strain with laboratory derived mutation in the rpoB gene (H526D)</option>
                    <option value="M. tuberculosis, WHO strain 2116, mutation in the rpoB gene (A516V)">M. tuberculosis, WHO strain 2116, mutation in the rpoB gene (A516V)</option>
                    <option value="M. tuberculosis, WHO strain 3201, mutation in the rpoB gene (H526T)">M. tuberculosis, WHO strain 3201, mutation in the rpoB gene (H526T)</option>
                </select>
            </td>
            <td>
                <select name="mtbDetectedUltra[]" class="isRequired form-control input-sm"
                        title="Please enter the MTB Detected for this sample"
                        placeholder="Please enter the MTB Detected for this sample">
                    <option value="">-- Select --</option>
                    <option value="high">High</option>
                    <option value="medium">Medium</option>
                    <option value="low">Low</option>
                    <option value="veryLow">Very Low</option>
                    <option value="trace">Trace</option>
                    <option value="notDetected">Not Detected</option>
                    <option value="noResult">No Result</option>
                    <option value="invalid">Invalid</option>
                    <option value="error">Error</option>
                </select>
            </td>
            <td>
                <select name="rifResistanceUltra[]" class="isRequired form-control input-sm"
                        title="Please enter the Rif Resistance for this sample"
                        placeholder="Please enter the Rif Resistance for this sample">
                    <option value="">-- Select --</option>
                    <option value="detected">Detected</option>
                    <option value="notDetected">Not Detected</option>
                    <option value="indeterminate">RIF Indeterminate</option>
                    <option value="na">N/A</option>
                </select>
            </td>
            <td>
                <input type="text" name="probeUltraSpc[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
            <td>
                <input type="text" name="probeUltraIS1081IS6110[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
            <td>
                <input type="text" name="probeUltraRpoB1[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
            <td>
                <input type="text" name="probeUltraRpoB2[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
            <td>
                <input type="text" name="probeUltraRpoB3[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
            <td>
                <input type="text" name="probeUltraRpoB4[]" class="form-control input-sm oneDecimal"
                       title="Please enter all Ct values for each sample"
                       placeholder="Please enter all Ct values for each sample" />
            </td>
        </tr>
    <?php
    } ?>
    </tbody>
</table>
