<table style="width: 100%;margin: 0 auto;" border="1" class="table table-bordered table-striped clearfix" id="vlSampleTable">
	<thead>
		<tr align="center" style="background:yellow;">
			<th  style="text-align: center;" colspan="3">
				Results Table
			</th>
			<th style="text-align: center;" colspan="12">
				Cycle Threshold (CT)
			</th>
		</tr>
		<tr align="center">
			<th style="width:10%;text-align: center;vertical-align:middle;" rowspan="2">Sample</th>
			<th style="width:9%;text-align: center;vertical-align:middle;" rowspan="2">MTB Detected<br/>(Level)</th>
			<th style="width:9%;text-align: center;vertical-align:middle;" rowspan="2">Rif Resistance</th>
            <th style="text-align: center;vertical-align:middle;" colspan="6">MTB/RIF</th>
            <th style="text-align: center;vertical-align:middle;" colspan="6">MTB Ultra</th>
		</tr>
        <tr align="center">
            <th style="width:6%;text-align: center;vertical-align:middle;">Probe D</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">Probe C</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">Probe E</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">Probe B</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">SPC</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">Probe A</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">SPC</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">IS1081-IS6110</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">rpoB1</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">rpoB2</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">rpoB3</th>
            <th style="width:6%;text-align: center;vertical-align:middle;">rpoB4</th>
        </tr>
	</thead>
	<tbody>
    <?php for ($i = 0; $i < 5; ++$i) { ?>
        <tr align="center">
            <th>
                <input type="text" name="sampleName[]" value="" class="isRequired form-control input-sm" placeholder="Please enter the Sample Name" title="Please enter the Sample Name" />
            </th>
            <td>
                <select name="mtbDetected[]" class="isRequired form-control input-sm"  title="Please enter the MTB Detected for this sample" placeholder="Please enter the MTB Detected for this sample">
                    <option value="">-- Select --</option>
                    <option value="high">High</option>
                    <option value="medium">Medium</option>
                    <option value="low">Low</option>
                    <option value="veryLow">Very Low</option>
                    <option value="trace">Trace</option>
                    <option value="notDetected">Not Detected</option>
                </select>
            </td>
            <td>
                <select name="rifResistance[]" class="isRequired form-control input-sm"  title="Please enter the Rif Resistance for this sample" placeholder="Please enter the Rif Resistance for this sample">
                    <option value="">-- Select --</option>
                    <option value="detected">Detected</option>
                    <option value="notDetected">Not Detected</option>
                    <option value="indeterminate">RIF Indeterminate</option>
                    <option value="na">N/A</option>
                </select>
            </td>
            <td>
                <input type="text" name="probeMtbRifD[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe D value for this sample" placeholder="Please enter the Probe D value for this sample" />
            </td>
            <td>
                <input type="text" name="probeMtbRifC[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe C value for this sample" placeholder="Please enter the Probe C value for this sample" />
            </td>
            <td>
                <input type="text" name="probeMtbRifE[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe E value for this sample" placeholder="Please enter the Probe E value for this sample" />
            </td>
            <td>
                <input type="text" name="probeMtbRifB[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe B value for this sample" placeholder="Please enter the Probe B value for this sample" />
            </td>
            <td>
                <input type="text" name="probeMtbRifSpc[]" class="form-control input-sm oneDecimal"  title="Please enter the MTB/RIF SPC value for this sample" placeholder="Please enter the SPC value for this sample" />
            </td>
            <td>
                <input type="text" name="probeMtbRifA[]" class="form-control input-sm oneDecimal"  title="Please enter the Probe A value for this sample" placeholder="Please enter the Probe A value for this sample" />
            </td>
            <td>
                <input type="text" name="probeUltraSpc[]" class="form-control input-sm oneDecimal"  title="Please enter the Ultra SPC value for this sample" placeholder="Please enter the Probe D value for this sample" />
            </td>
            <td>
                <input type="text" name="probeUltraIS1081IS6110[]" class="form-control input-sm oneDecimal"  title="Please enter the IS1081-IS6110 value for this sample" placeholder="Please enter the Probe C value for this sample" />
            </td>
            <td>
                <input type="text" name="probeUltraRpoB1[]" class="form-control input-sm oneDecimal"  title="Please enter the rpoB1 value for this sample" placeholder="Please enter the Probe E value for this sample" />
            </td>
            <td>
                <input type="text" name="probeUltraRpoB2[]" class="form-control input-sm oneDecimal"  title="Please enter the rpoB2 value for this sample" placeholder="Please enter the Probe B value for this sample" />
            </td>
            <td>
                <input type="text" name="probeUltraRpoB3[]" class="form-control input-sm oneDecimal"  title="Please enter the rpoB3 value for this sample" placeholder="Please enter the SPC value for this sample" />
            </td>
            <td>
                <input type="text" name="probeUltraRpoB4[]" class="form-control input-sm oneDecimal"  title="Please enter the rpoB4 value for this sample" placeholder="Please enter the Probe A value for this sample" />
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
