<style>
    .fieldLabel {
        white-space: nowrap;
    }
</style>
<?php
$attributes = json_decode($this->responseData['shipment']['attributes'], true);
$dateFormatHelper = $this->getHelper('DateFormat');
$dtFormat = $dateFormatHelper->getDateFormat();
$testReceiptDate = date('d-M-Y');
if (isset($this->shipment["shipment_test_report_date"]) &&
    trim($this->shipment["shipment_test_report_date"]) != "") {
    $expTestReceiptDate = explode(" ", $this->responseData['shipment']["shipment_test_report_date"]);
    $testReceiptDate = $this->dateFormat($expTestReceiptDate[0]);
} ?>
<table class="table table-bordered table-striped" style="width:100%;margin:0 auto 10px auto;">
    <tr>
        <th style="width: 20%;">
            <label class="fieldLabel">
                Shipment Received on
                <span class='mandatory'>*</span>
            </label>
        </th>
        <td style="width: 30%;">
            <input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;"
                   value="<?php echo $this->dateFormat($this->responseData['shipment']["shipment_receipt_date"]); ?>"
                   class="form-control datepicker" readonly="readonly" title="Please enter Test Receipt Date" />
            <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('receiptDate')"> Clear</i>
        </td>
        <td>
            <label class="fieldLabel">
                Assay
                <span class='mandatory'>*</span>
            </label>
        </td>
        <td>
            <select class="form-control" name="assay" id="assay" class="form-control"
                    title="Please choose the assay type">
                <?php foreach($this->assays as $id => $name) { ?>
                    <option value="<?php echo $id; ?>" <?php if(isset($attributes['assay'])) { echo ($attributes['assay'] == $id) ? "selected='selected'" : ""; } ?>>
                        <?php echo $name; ?>
                    </option>
                <?php } ?>
            </select>
        </td>
    </tr>
    <tr>
        <th>
            <label class="fieldLabel">
                MTB/RIF Kit Lot No
                <span class='mandatory'>*</span>
            </label>
        </th>
        <td>
            <input type="text" name="mtbRifKitLotNo" id="mtbRifKitLotNo" class="form-control isRequired"
                   value="<?php echo $attributes['mtb_rif_kit_lot_no'];?>" />
        </td>
        <td>
            <label class="fieldLabel">
                Expiration date of MTB/RIF Kit
                <span class='mandatory'>*</span>
            </label>
        </td>
        <td>
            <input type="text" name="expiryDate" id="expiryDate" style="width:180px;float:left;" maxlength="11"
                   value="<?php echo $attributes['expiry_date'];?>" class="isRequired datepicker form-control"
                   readonly="readonly" />
            <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('expiryDate')"> Clear</i>
        </td>
    </tr>
    <tr>
        <th>
            <label class="fieldLabel">
                Response Date
                <span class='mandatory'>*</span>
            </label>
        </th>
        <td>
            <input type="text" id="testReceiptDate" name="testReceiptDate" style="width:180px;float:left;" maxlength="11"
                   value="<?php echo $testReceiptDate; ?>" class="isRequired datepicker form-control"
                   readonly="readonly" />
            <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('testReceiptDate')"> Clear</i>
        </td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>
            <label>How many Xpert MTB/RIF tests have been conducted by this site in the last full month?</label>
        </td>
        <td>
            <input type="text" name="countTestsConductedOverMonth" id="countTestsConductedOverMonth"
                   class="form-control"
                   value="<?php if(isset($attributes['count_tests_conducted_over_month'])) { echo $attributes['count_tests_conducted_over_month']; }?>" />
        </td>
        <td>
            <label>How many errors occurred during testing in the last full month?</label>
        </td>
        <td>
            <input type="text" name="countErrorsEncounteredOverMonth" id="countErrorsEncounteredOverMonth"
                   class="form-control"
                   value="<?php if(isset($attributes['count_errors_encountered_over_month'])) { echo $attributes['count_errors_encountered_over_month']; }?>" />
        </td>
    </tr>
    <tr>
        <td><label>What were the error codes?</label></td>
        <td colspan="3">
            <input type="text" name="errorCodesEncounteredOverMonth" id="errorCodesEncounteredOverMonth"
                   class="form-control"
                   value="<?php if(isset($attributes['error_codes_encountered_over_month'])) { echo $attributes['error_codes_encountered_over_month']; }?>" />
        </td>
    </tr>
    <?php
    if ($this->globalQcAccess == 'yes') { ?>
    <tr>
        <td>
            <label class="fieldLabel">Monthly Maintenance Done</label>
        </td>
        <td>
            <input type="radio" id="qcDoneYes" name="qcDone" value="yes"
                   title="Please select monthly maintenance status" <?php echo ($this->responseData['shipment']['qc_done'] == "yes") ? " checked='checked' " : ""; ?>
                   onclick="checkQcStatus();" />
            <strong>Yes</strong>&nbsp;&nbsp;
            <input type="radio" id="qcDoneNo" name="qcDone" value="no"
                   title="Please select monthly maintenance done status" <?php echo ($this->responseData['shipment']['qc_done'] == null || $this->responseData['shipment']['qc_done'] == "" || $this->responseData['shipment']['qc_done'] == "no") ? " checked='checked' " : ""; ?>
                   onclick="checkQcStatus();" />
            <strong>No</strong>
        </td>
        <td colspan="2"></td>
    </tr>
    <?php
        $display = "display:none";
        $isRequired = "";
        if (isset($this->responseData['shipment']['qc_done']) &&
            $this->responseData['shipment']['qc_done'] == "yes") {
            $display = "";
            $isRequired = "isRequired";
        } ?>
    <tr id="qcSection" class="light" style="<?php echo $display; ?>">
        <td>
            <label class="fieldLabel">
                Maintenance Date
                <span class='mandatory'>*</span>
            </label>
        </td>
        <td>
            <input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;"
                   value="<?php echo $this->dateFormat($this->responseData['shipment']["qc_date"]); ?>"
                   class="form-control datepicker <?php echo $isRequired; ?>" readonly="readonly"
                   title="Please enter Maintenance Date" />
            <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('qcDate')"> Clear</i>
        </td>
        <td>
            <label class="fieldLabel">
                Maintenance Done By
                <span class='mandatory'>*</span>
            </label>
        </td>
        <td>
            <input type="text" id="qcDoneBy" name="qcDoneBy" class="form-control <?php echo $isRequired; ?>"
                   title="Please enter who performed maintenance"
                   value="<?php echo $this->responseData['shipment']["qc_done_by"]; ?>" />
        </td>
    </tr>
    <?php
    } ?>
</table>
<br />
<table class="table table-bordered table-striped table-hover" style="width:100%;margin:0 auto;">
<?php
$total = 0;
$counter = 1;
foreach ($this->responseData['results'] as $result) {
    if (($counter % 2) == 0) {
        $class = "evenResult";
    } else {
        $class = "oddResult";
    }
    $errorCodeEnabled = $result['res_mtb_detected'] == "error";
    $rifResistanceEnabled = in_array($result['res_mtb_detected'], array("detected", "high", "medium", "low", "veryLow")); ?>
    <tr class="<?php echo $class ?>">
        <td>
            <table class="table" style="background-color: transparent;">
                <tr>
                    <th colspan="11" style="white-space: nowrap;background-color: transparent;">
                        <?php echo $result['sample_label']; ?>
                        <span class='mandatory'>*</span>
                        <input type="hidden" id ="sample<?php echo $counter; ?>" name="sampleId[]"
                               value="<?php echo $result['sample_id'];?>" />
                    </th>
                </tr>
                <tr style="background-color: transparent;">
                    <th colspan="2" style="background-color: transparent;">Date Tested</th>
                    <th style="background-color: transparent;">MTB Detected</th>
                    <th style="background-color: transparent;">Error Code</th>
                    <th style="background-color: transparent;">Rif Resistance</th>
                    <th style="background-color: transparent;">Probe D</th>
                    <th style="background-color: transparent;">Probe C</th>
                    <th style="background-color: transparent;">Probe E</th>
                    <th style="background-color: transparent;">Probe B</th>
                    <th style="background-color: transparent;">SPC</th>
                    <th style="background-color: transparent;">Probe A</th>
                </tr>
                <tr>
                    <td colspan="2" style="vertical-align: middle;text-align: center;width: 14%;background-color: transparent;">
                        <input type="text" class="form-control datepicker sampleTestDate input-sm" readonly="readonly"
                               name="dateTested[]" value="<?php echo $this->dateFormat($result['res_date_tested']); ?>"
                               title="Please enter the Test Date for <?php echo $result['sample_label']; ?>" />
                    </td>
                    <td style="vertical-align: middle;text-align: center;width: 13%;background-color: transparent;">
                        <select id="mtbDetected<?php echo $counter; ?>" name="mtbDetected[]"
                                class="isRequired form-control input-sm"
                                title="Please enter the MTB Detected for this sample"
                                placeholder="Please enter the MTB Detected for this sample"
                                onChange="changeMtbDetected(<?php echo $counter; ?>)">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($result['res_mtb_detected'] == 'detected' ? "selected='selected'" : ""); ?>>
                                Detected
                            </option>
                            <option value="high" <?php echo ($result['res_mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>
                                High
                            </option>
                            <option value="medium" <?php echo ($result['res_mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>
                                Medium
                            </option>
                            <option value="low" <?php echo ($result['res_mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>
                                Low
                            </option>
                            <option value="veryLow" <?php echo ($result['res_mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>
                                Very Low
                            </option>
                            <option value="notDetected" <?php echo ($result['res_mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>Not Detected</option>
                            <option value="noResult" <?php echo ($result['res_mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>
                                No Result
                            </option>
                            <option value="invalid" <?php echo ($result['res_mtb_detected'] == 'invalid' ? "selected='selected'" : ""); ?>>
                                Invalid
                            </option>
                            <option value="error" <?php echo ($result['res_mtb_detected'] == 'error' ? "selected='selected'" : ""); ?>>
                                Error
                            </option>
                        </select>
                    </td>
                    <td style="vertical-align: middle;text-align: center;width: 11%;">
                        <input type="text" id="errorCode<?php echo $counter; ?>" name="errorCode[]"
                               class="form-control input-sm" value="<?php echo $result['res_error_code']; ?>"
                               title="Please enter the Probe D value for <?php echo $result['sample_label']; ?>" <?php if (!$errorCodeEnabled) { echo "readonly"; } ?> />
                    </td>
                    <td style="vertical-align: middle;text-align:center;width: 13%;">
                        <select id="rifResistance<?php echo $counter; ?>" name="rifResistance[]"
                                class="isRequired form-control input-sm"
                                title="Please enter the Rif Resistance for this sample"
                                placeholder="Please enter the Rif Resistance for this sample" <?php if (!$rifResistanceEnabled) { echo "readonly"; } ?>>
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($result['res_rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>
                                Detected
                            </option>
                            <option value="notDetected" <?php echo ($result['res_rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                Not Detected
                            </option>
                            <option value="indeterminate" <?php echo ($result['res_rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>
                                RIF Indeterminate
                            </option>
                            <option value="na"  <?php echo ($result['res_rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>
                                N/A
                            </option>
                        </select>
                    </td>
                    <td style="vertical-align: middle;text-align: center;width: 7%;">
                        <input type="text" name="probeD[]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_d']; ?>" title="Please enter the Probe D value for <?php echo $result['sample_label']; ?>" />
                    </td>
                    <td style="vertical-align: middle;text-align: center;width: 7%;">
                        <input type="text" name="probeC[]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_c']; ?>" title="Please enter the Probe C value for <?php echo $result['sample_label']; ?>" />
                    </td>
                    <td style="vertical-align: middle;text-align: center;width: 7%;">
                        <input type="text" name="probeE[]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_e']; ?>" title="Please enter the Probe E value for <?php echo $result['sample_label']; ?>" />
                    </td>
                    <td style="vertical-align: middle;text-align: center;width: 7%;">
                        <input type="text" name="probeB[]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_b']; ?>" title="Please enter the Probe B value for <?php echo $result['sample_label']; ?>" />
                    </td>
                    <td style="vertical-align: middle;text-align: center;width: 7%;">
                        <input type="text" name="spc[]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_spc']; ?>" title="Please enter the SPC value for <?php echo $result['sample_label']; ?>" />
                    </td>
                    <td style="vertical-align: middle;text-align: center;width: 7%;">
                        <input type="text" name="probeA[]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_a']; ?>" title="Please enter the Probe A value for <?php echo $result['sample_label']; ?>" />
                    </td>
                </tr>
                <tr>
                    <th colspan="3" style="vertical-align: bottom;">Instrument Serial</th>
                    <th colspan="2" style="vertical-align: bottom;">Installed</th>
                    <th colspan="2" style="vertical-align: bottom;">Last Calibrated</th>
                    <th style="vertical-align: bottom;">Module Number</th>
                    <th colspan="3" style="vertical-align: bottom;">Instrument User</th>
                </tr>
                <tr style="background-color: transparent;">
                    <th colspan="3" style="white-space: nowrap;background-color: transparent;">
                        <input type="text" name="instrumentSerial[]" class="form-control input-sm"
                               value="<?php echo $result['res_instrument_serial']; ?>" title="Please enter the instrument serial number for <?php echo $result['sample_label']; ?>" />
                    </th>
                    <td colspan="2" style="background-color: transparent;">
                        <input type="text" class="form-control datepicker input-sm" readonly="readonly"
                               name="instrumentInstalledOn[]" value="<?php echo $this->dateFormat($result['res_instrument_installed_on']); ?>"
                               title="Please enter the instrument installation date for <?php echo $result['sample_label']; ?>" />
                    </td>
                    <td colspan="2" style="background-color: transparent;">
                        <input type="text" class="form-control datepicker input-sm" readonly="readonly"
                               name="instrumentLastCalibratedOn[]"
                               value="<?php echo $this->dateFormat($result['res_instrument_last_calibrated_on']); ?>"
                               title="Please enter the date that the instrument was last calibrated for <?php echo $result['sample_label']; ?>" />
                    </td>
                    <th style="white-space: nowrap;background-color: transparent;">
                        <input type="text" name="moduleName[]" class="form-control input-sm"
                               value="<?php echo $result['res_module_name']; ?>"
                               title="Please enter the module number for <?php echo $result['sample_label']; ?>" />
                    </th>
                    <th colspan="3" style="white-space: nowrap;background-color: transparent;">
                        <input type="text" name="instrumentUser[]" class="form-control input-sm"
                               value="<?php echo $result['res_instrument_user']; ?>"
                               title="Please enter the instrument user for <?php echo $result['sample_label']; ?>" />
                    </th>
                </tr>
            </table>
        </td>
    </tr>
    <tr class="<?php echo $class ?>"></tr>
<?php
    $counter++;
} ?>
</table>
<script>
  $(function() {
    $(".datepicker,.expDatepicker").datepicker({dateFormat: '<?php echo $dtFormat; ?>'});
    <?php
      if (!$this->isEditable) { ?>
    $("#tbResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
    <?php
      } ?>
  });

  function clearDate(id) {
    $("#" + id).val('');
  }

  function changeMtbDetected(resultNumber) {
    var mtbDetected = $("#mtbDetected" + resultNumber).val();
    var errorCodeInput = $("#errorCode" + resultNumber);
    var rifResistanceSelect = $("#rifResistance" + resultNumber);
    if (mtbDetected === "error") {
      errorCodeInput.removeAttr("readonly");
    } else {
      errorCodeInput.attr("readonly", "");
      errorCodeInput.val('')
    }
    if (["detected", "high", "medium", "low", "veryLow"].includes(mtbDetected)) {
      rifResistanceSelect.removeAttr("readonly");
    } else {
      rifResistanceSelect.attr("readonly", "");
      rifResistanceSelect.val('na')
    }
  }

  function checkQcStatus() {
    var radioValue = $("input[name='qcDone']:checked").val();
    if (radioValue == "yes") {
      $("#qcSection").show();
      $("#qcDate").addClass("isRequired");
      $("#qcDoneBy").addClass("isRequired");
    } else {
      $("#qcSection").hide();
      $("#qcDate").val("");
      $("#qcDoneBy").val("");
      $("#qcDate").removeClass("isRequired");
      $("#qcDoneBy").removeClass("isRequired");
    }
  }
</script>
