<style>
    .fieldLabel {
        white-space: nowrap;
    }

    div.error {
        color: #ff0000;
        float: left;
    }

    input.error, select.error {
        border: solid 1px #ff0000;
    }
</style>
<?php
$attributes = json_decode($this->responseData['shipment']['attributes'], true);
$dateFormatHelper = $this->getHelper('DateFormat');
$dtFormat = $dateFormatHelper->getDateFormat();
$testReceiptDate = date('d-M-Y');
if (isset($this->responseData['shipment']["shipment_test_report_date"]) &&
    trim($this->responseData['shipment']["shipment_test_report_date"]) != "") {
    $expTestReceiptDate = explode(" ", $this->responseData['shipment']["shipment_test_report_date"]);
    $testReceiptDate = $this->dateFormat($expTestReceiptDate[0]);
} ?>
<hr />
<table class="table table-bordered table-striped" style="width:100%;margin:0 auto 10px auto;">
    <tr>
        <td colspan="2">
            <h4 class="text-info">
                Was the participant able to test the performance evaluation panel?
                &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" id="ableToEnterResultsYes" name="ableToEnterResults" value="yes"
                <?php echo ($this->responseData['shipment']['is_pt_test_not_performed'] == "no" || $this->responseData['shipment']['is_pt_test_not_performed'] == "" || $this->responseData['shipment']['is_pt_test_not_performed'] == null) ? " checked='checked' " : ""; ?> />
                <label for="ableToEnterResultsYes">Yes</label>&nbsp;&nbsp;
                <input type="radio" id="ableToEnterResultsNo" name="ableToEnterResults" value="no"
                <?php echo ($this->responseData['shipment']['is_pt_test_not_performed'] == "yes") ? " checked='checked' " : ""; ?> />
                    <label for="ableToEnterResultsNo">No</label>
            </h4>
        </td>
    </tr>
    <tr id="ableToEnterResultsReasonsRow" style="display: <?php echo ($this->responseData['shipment']['is_pt_test_not_performed'] == "no" || $this->responseData['shipment']['is_pt_test_not_performed'] == '' || $this->responseData['shipment']['is_pt_test_not_performed'] == null) ? "none" : "table-row"; ?>;">
        <td style="width: 30%;">
            <label for="notTestedReason" class="fieldLabel">Reason for not testing the panel <span class="mandatory">*</span>:</label>
        </td>
        <td>
            <select id="notTestedReason" name="notTestedReason" class="form-control" title="Please select reason" style="width:60%;">
                <option value="">--Select--</option>
<?php
    foreach($this->allNotTestedReason as $reason) { ?>
                <option value="<?php echo $reason['not_tested_reason_id']; ?>"
                    <?php echo($this->responseData['shipment']['not_tested_reason'] == $reason['not_tested_reason_id']) ? 'selected="selected"':''; ?>>
                    <?php echo ucwords($reason['not_tested_reason']); ?>
                </option>
<?php
    } ?>
                <option value="other"
                    <?php echo (isset($this->responseData['shipment']['pt_test_not_performed_comments']) && trim($this->responseData['shipment']['pt_test_not_performed_comments']) != "") ? 'selected="selected"' : ''; ?>>
                    Other
                </option>
            </select>
        </td>
    </tr>
    <tr id="ableToEnterResultsOtherReasonRow" style="display: <?php echo (isset($this->responseData['shipment']['pt_test_not_performed_comments']) && trim($this->responseData['shipment']['pt_test_not_performed_comments']) != '') ? 'table-row' : 'none'; ?>;">
        <td>
            <label for="notTestedOtherReason" class="fieldLabel">Please specify <span class="mandatory">*</span>:</label>
        </td>
        <td>
            <input type="text" name="notTestedOtherReason" id="notTestedOtherReason" class="form-control isRequired"
                value="<?php echo $this->responseData['shipment']['pt_test_not_performed_comments']; ?>" />
        </td>
    </tr>
    <tr id="transferToParticipantRow" style="display: <?php echo ($this->responseData['shipment']['is_pt_test_not_performed'] == "no" || $this->responseData['shipment']['is_pt_test_not_performed'] == '' || $this->responseData['shipment']['is_pt_test_not_performed'] == null) ? "none" : "table-row"; ?>;">
        <td style="width: 30%;">
            <label for="transferToParticipant" class="fieldLabel">Transfer sample to:</label>
        </td>
        <td>
            <select id="transferToParticipant" name="transferToParticipant" class="form-control" title="Transfer Sample To" style="width:60%;">
                <option value="">--Select another Participant--</option>
                <?php
                foreach($this->otherUnenrolledParticipants as $otherUnenrolledParticipant) {
                    $transferToParticipantId = null;
                    if (isset($attributes)) {
                        if (isset($attributes['transferToParticipantId'])) {
                            $transferToParticipantId = $attributes['transferToParticipantId'];
                        }
                    }
                ?>
                <option value="<?php echo $otherUnenrolledParticipant['participant_id']; ?>"
                    <?php echo($transferToParticipantId == $otherUnenrolledParticipant['participant_id'] ? 'selected="selected"':''); ?>>
                    <?php echo $otherUnenrolledParticipant['participant_name']; ?>
                </option>
                <?php
                } ?>
            </select>
        </td>
    </tr>
</table>
<hr />
<table id="submissionHeader" class="table table-bordered table-striped" style="width:100%;margin:0 auto 10px auto;">
    <tr>
        <th style="width: 20%;">
            <label class="fieldLabel">
                Shipment Received on
                <span class='mandatory'>*</span>
            </label>
        </th>
        <td style="width: 30%;">
            <input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;"
                   value="<?php echo $this->dateFormat($this->responseData['shipment']["shipment_receipt_date"]); ?>"
                   class="form-control datepicker" readonly="readonly" title="Please enter Test Receipt Date" />
            <i id="clearReceiptDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('receiptDate')"> Clear</i>
        </td>
        <td>
            <label class="fieldLabel">
                Assay
                <span class='mandatory'>*</span>
            </label>
        </td>
        <td>
            <select class="form-control" name="assay" id="assay" class="form-control"
                    title="Please choose the assay type">
                <?php foreach ($this->assays as $id => $definition) { ?>
                    <option value="<?php echo $id; ?>" <?php if(isset($attributes['assay'])) { echo ($attributes['assay'] == $id) ? "selected='selected'" : ""; } ?>>
                        <?php echo $definition['name']; ?>
                    </option>
                <?php } ?>
            </select>
        </td>
    </tr>
    <tr>
        <th>
            <label class="fieldLabel">
                Cartridge Lot No
                <span class='mandatory'>*</span>
            </label>
        </th>
        <td>
            <input type="text" name="cartridgeLotNo" id="cartridgeLotNo" class="form-control isRequired"
                   value="<?php echo $attributes['cartridge_lot_no'];?>" />
        </td>
        <td>
            <label class="fieldLabel">
                Expiration date of Cartridge
                <span class='mandatory'>*</span>
            </label>
        </td>
        <td>
            <input type="text" name="expiryDate" id="expiryDate" style="width:180px;float:left;" maxlength="11"
                   value="<?php echo $attributes['expiry_date'];?>" class="isRequired datepicker form-control allowFutureDate"
                   readonly="readonly" />
            <i id="clearExpiryDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('expiryDate')"> Clear</i>
        </td>
    </tr>
    <tr>
        <th>
            <label class="fieldLabel">
                Response Date
                <span class='mandatory'>*</span>
            </label>
        </th>
        <td>
            <input type="text" id="testReceiptDate" name="testReceiptDate" style="width:180px;float:left;" maxlength="11"
                   value="<?php echo $testReceiptDate; ?>" class="isRequired datepicker form-control"
                   readonly="readonly" />
            <i id="clearTestReceiptDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('testReceiptDate')"> Clear</i>
        </td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>
            <label>How many Xpert MTB/RIF and MTB Ultra tests have been conducted by this site in the last full month?</label>
        </td>
        <td>
            <input type="text" name="countTestsConductedOverMonth" id="countTestsConductedOverMonth"
                   class="form-control"
                   value="<?php if(isset($attributes['count_tests_conducted_over_month'])) { echo $attributes['count_tests_conducted_over_month']; }?>" />
        </td>
        <td>
            <label>How many errors occurred during testing in the last full month?</label>
        </td>
        <td>
            <input type="text" name="countErrorsEncounteredOverMonth" id="countErrorsEncounteredOverMonth"
                   class="form-control"
                   value="<?php if(isset($attributes['count_errors_encountered_over_month'])) { echo $attributes['count_errors_encountered_over_month']; }?>" />
        </td>
    </tr>
    <tr>
        <td><label>What were the error codes?</label></td>
        <td colspan="3">
            <input type="text" name="errorCodesEncounteredOverMonth" id="errorCodesEncounteredOverMonth"
                   class="form-control"
                   value="<?php if(isset($attributes['error_codes_encountered_over_month'])) { echo $attributes['error_codes_encountered_over_month']; }?>" />
        </td>
    </tr>
    <?php
    if ($this->globalQcAccess == 'yes') { ?>
    <tr>
        <td>
            <label class="fieldLabel">Monthly Maintenance Done</label>
        </td>
        <td>
            <input type="radio" id="qcDoneYes" name="qcDone" value="yes"
                   title="Please select monthly maintenance status" <?php echo ($this->responseData['shipment']['qc_done'] == "yes") ? " checked='checked' " : ""; ?>
                   onclick="checkQcStatus();" />
            <strong>Yes</strong>&nbsp;&nbsp;
            <input type="radio" id="qcDoneNo" name="qcDone" value="no"
                   title="Please select monthly maintenance done status" <?php echo ($this->responseData['shipment']['qc_done'] == null || $this->responseData['shipment']['qc_done'] == "" || $this->responseData['shipment']['qc_done'] == "no") ? " checked='checked' " : ""; ?>
                   onclick="checkQcStatus();" />
            <strong>No</strong>
        </td>
        <td colspan="2"></td>
    </tr>
    <?php
        $display = "display:none";
        $isRequired = "";
        if (isset($this->responseData['shipment']['qc_done']) &&
            $this->responseData['shipment']['qc_done'] == "yes") {
            $display = "";
            $isRequired = "isRequired";
        } ?>
    <tr id="qcSection" class="light" style="<?php echo $display; ?>">
        <td>
            <label class="fieldLabel">
                Maintenance Date
                <span class='mandatory'>*</span>
            </label>
        </td>
        <td>
            <input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;"
                   value="<?php echo $this->dateFormat($this->responseData['shipment']["qc_date"]); ?>"
                   class="form-control datepicker <?php echo $isRequired; ?>" readonly="readonly"
                   title="Please enter Maintenance Date" />
            <i id="clearQcDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('qcDate')"> Clear</i>
        </td>
        <td>
            <label class="fieldLabel">
                Maintenance Done By
                <span class='mandatory'>*</span>
            </label>
        </td>
        <td>
            <input type="text" id="qcDoneBy" name="qcDoneBy" class="form-control <?php echo $isRequired; ?>"
                   title="Please enter who performed maintenance"
                   value="<?php echo $this->responseData['shipment']["qc_done_by"]; ?>" />
        </td>
    </tr>
    <?php
    } ?>
    <tr>
        <td colspan="4">
            <label>Instruments at Facility:</label>
            <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
                <thead>
                <tr>
                    <td>
                        <label>Serial Number</label>
                    </td>
                    <td>
                        <label>Installed</label>
                    </td>
                    <td>
                        <label>Last Calibrated</label>
                    </td>
                    <td>
                        <label>Add/Remove</label>
                    </td>
                </tr>
                </thead>
                <tbody>
                <?php
                        $instrumentCount = 0;
                        $instrumentIndex = 0;
                        foreach ($this->instruments as $id => $instrument_details) {
                            $instrumentCount++; ?>
                <tr>
                    <td>
                        <input type="hidden" name="headerInstrumentIndex[<?php echo $instrumentIndex; ?>]"
                               class="instrumentIndex" value="<?php echo $instrumentIndex; ?>" />
                        <input type="hidden" id="headerInstrumentId<?php echo $instrumentCount; ?>"
                               name="headerInstrumentId[<?php echo $instrumentIndex; ?>]"
                               value="<?php echo $id; ?>"  />
                        <input type="text" id="headerInstrumentSerial<?php echo $instrumentCount; ?>"
                               name="headerInstrumentSerial[<?php echo $instrumentIndex; ?>]"
                               class="form-control input-sm" value="<?php echo $instrument_details['instrument_serial']; ?>"
                               title="Please enter the instrument serial number"
                               onblur="updateInstrumentLists()" />
                    </td>
                    <td>
                        <input type="text" id="headerInstrumentInstalledOn<?php echo $instrumentCount; ?>"
                               class="form-control datepicker input-sm instrument-date-picker" readonly="readonly"
                               name="headerInstrumentInstalledOn[<?php echo $instrumentIndex; ?>]"
                               value="<?php echo $this->dateFormat($instrument_details['instrument_installed_on']); ?>"
                               title="Please enter the instrument installation date" />
                    </td>
                    <td>
                        <input type="text" id="headerInstrumentLastCalibratedOn<?php echo $instrumentCount; ?>"
                               class="form-control datepicker input-sm instrument-date-picker" readonly="readonly"
                               name="headerInstrumentLastCalibratedOn[<?php echo $instrumentIndex; ?>]"
                               value="<?php echo $this->dateFormat($instrument_details['instrument_last_calibrated_on']); ?>"
                               title="Please enter the date that the instrument was last calibrated" />
                    </td>
                    <td>
                        <a href="javascript:void(0);" onclick="addInstrumentRow(this);"
                           class="btn btn-xs btn-info">
                            <i class="icon-plus"></i>
                        </a>&nbsp;&nbsp;
                        <a href="javascript:void(0);" onclick="removeInstrumentRow(this)" class="btn btn-xs btn-danger"
                           title="Remove this instrument" alt="Remove this instrument">
                            <i class="icon-minus"></i>
                        </a>
                    </td>
                </tr>
                <?php
                            $instrumentIndex++;
                        } ?>
                </tbody>
            </table>
        </td>
    </tr>
</table>
<br />
<table id="results" class="table table-bordered table-striped table-hover" style="width:100%;margin:0 auto;">
<?php
$total = 0;
$counter = 1;
$index = 0;
foreach ($this->responseData['results'] as $result) {
    if (($counter % 2) == 0) {
        $class = "evenResult";
    } else {
        $class = "oddResult";
    }
    $errorCodeEnabled = $result['res_mtb_detected'] == "error";
    $rifResistanceEnabled = in_array($result['res_mtb_detected'], array("detected", "high", "medium", "low", "veryLow")); ?>
    <tr class="<?php echo $class ?>">
        <td>
            <table class="table" style="background-color: transparent;">
                <tr>
                    <th colspan="11" style="white-space: nowrap;background-color: transparent;">
                        <?php echo $result['sample_label']; ?>
                        <span class='mandatory'>*</span>
                        <input type="hidden" id ="sample<?php echo $counter; ?>" name="sampleId[<?php echo $index; ?>]"
                               value="<?php echo $result['sample_id'];?>" />
                    </th>
                </tr>
                <tr style="background-color: transparent;">
                    <th colspan="2" style="background-color: transparent; width:14%;">Date Tested</th>
                    <th style="background-color: transparent;width:14%;">MTB Detected</th>
                    <th style="background-color: transparent;width:10%;">Error Code</th>
                    <th style="background-color: transparent;width:14%;">Rif Resistance</th>
                    <th class="probe1Header" style="background-color: transparent;width:8%;"></th>
                    <th class="probe2Header" style="background-color: transparent;width:8%;"></th>
                    <th class="probe3Header" style="background-color: transparent;width:8%;"></th>
                    <th class="probe4Header" style="background-color: transparent;width:8%;"></th>
                    <th class="probe5Header" style="background-color: transparent;width:8%;"></th>
                    <th class="probe6Header" style="background-color: transparent;width:8%;"></th>
                </tr>
                <tr>
                    <td colspan="2" style="vertical-align: top;text-align: center;width: 14%;background-color: transparent;">
                        <input type="text" class="form-control datepicker sampleTestDate input-sm" readonly="readonly"
                               name="dateTested[<?php echo $index; ?>]" value="<?php echo $this->dateFormat($result['res_date_tested']); ?>"
                               title="Please enter the Test Date for <?php echo $result['sample_label']; ?>" />
                    </td>
                    <td style="vertical-align: top;text-align: center;width: 13%;background-color: transparent;">
                        <select id="mtbDetected<?php echo $counter; ?>" name="mtbDetected[<?php echo $index; ?>]"
                                class="isRequired form-control input-sm mtbDetected"
                                title="Please enter the MTB Detected for this sample"
                                placeholder="Please enter the MTB Detected for this sample"
                                onChange="changeMtbDetected(<?php echo $counter; ?>)">
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($result['res_mtb_detected'] == 'detected' ? "selected='selected'" : ""); ?>>
                                Detected
                            </option>
                            <option value="high" <?php echo ($result['res_mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>
                                High
                            </option>
                            <option value="medium" <?php echo ($result['res_mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>
                                Medium
                            </option>
                            <option value="low" <?php echo ($result['res_mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>
                                Low
                            </option>
                            <option value="veryLow" <?php echo ($result['res_mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>
                                Very Low
                            </option>
                            <option value="trace" <?php echo ($result['res_mtb_detected'] == 'trace' ? "selected='selected'" : ""); ?>>
                                Trace
                            </option>
                            <option value="notDetected" <?php echo ($result['res_mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                Not Detected
                            </option>
                            <option value="noResult" <?php echo ($result['res_mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>
                                No Result
                            </option>
                            <option value="invalid" <?php echo ($result['res_mtb_detected'] == 'invalid' ? "selected='selected'" : ""); ?>>
                                Invalid
                            </option>
                            <option value="error" <?php echo ($result['res_mtb_detected'] == 'error' ? "selected='selected'" : ""); ?>>
                                Error
                            </option>
                        </select>
                    </td>
                    <td style="vertical-align: top;text-align: center;width: 11%;">
                        <input type="text" id="errorCode<?php echo $counter; ?>" name="errorCode[<?php echo $index; ?>]"
                               class="form-control input-sm" value="<?php echo $result['res_error_code']; ?>"
                               title="Please enter the Probe D value for <?php echo $result['sample_label']; ?>" <?php if (!$errorCodeEnabled) { echo "readonly"; } ?> />
                    </td>
                    <td style="vertical-align: top;text-align:center;width: 13%;">
                        <select id="rifResistance<?php echo $counter; ?>" name="rifResistance[<?php echo $index; ?>]"
                                class="isRequired form-control input-sm"
                                title="Please enter the Rif Resistance for this sample"
                                placeholder="Please enter the Rif Resistance for this sample" <?php if (!$rifResistanceEnabled) { echo "readonly"; } ?>>
                            <option value="">-- Select --</option>
                            <option value="detected" <?php echo ($result['res_rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>
                                Detected
                            </option>
                            <option value="notDetected" <?php echo ($result['res_rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                Not Detected
                            </option>
                            <option value="indeterminate" <?php echo ($result['res_rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>
                                RIF Indeterminate
                            </option>
                            <option value="na" <?php echo ($result['res_rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>
                                N/A
                            </option>
                        </select>
                    </td>
                    <td style="vertical-align: top;text-align: center;width: 7%;">
                        <input type="text" name="probe1[<?php echo $index; ?>]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_1']; ?>" title="Please enter all Ct values for each sample" />
                    </td>
                    <td style="vertical-align: top;text-align: center;width: 7%;">
                        <input type="text" name="probe2[<?php echo $index; ?>]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_2']; ?>" title="Please enter all Ct values for each sample" />
                    </td>
                    <td style="vertical-align: top;text-align: center;width: 7%;">
                        <input type="text" name="probe3[<?php echo $index; ?>]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_3']; ?>" title="Please enter all Ct values for each sample" />
                    </td>
                    <td style="vertical-align: top;text-align: center;width: 7%;">
                        <input type="text" name="probe4[<?php echo $index; ?>]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_4']; ?>" title="Please enter all Ct values for each sample" />
                    </td>
                    <td style="vertical-align: top;text-align: center;width: 7%;">
                        <input type="text" name="probe5[<?php echo $index; ?>]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_5']; ?>" title="Please enter all Ct values for each sample" />
                    </td>
                    <td style="vertical-align: top;text-align: center;width: 7%;">
                        <input type="text" name="probe6[<?php echo $index; ?>]" class="form-control oneDecimal input-sm numberInput"
                               value="<?php echo $result['res_probe_6']; ?>" title="Please enter all Ct values for each sample" />
                    </td>
                </tr>
                <tr>
                    <th colspan="3" style="vertical-align: bottom;">Instrument Serial</th>
                    <th style="vertical-align: bottom;">Module Number</th>
                    <th colspan="3" style="vertical-align: bottom;">Instrument User</th>
                </tr>
                <tr style="background-color: transparent;">
                    <th colspan="3" style="vertical-align: top;white-space: nowrap;background-color: transparent;">
                        <input type="hidden" id="instrumentSerial<?php echo $counter; ?>"
                               name="instrumentSerial[<?php echo $index; ?>]"
                               value="<?php echo $result['res_instrument_serial']; ?>" />
                        <div id="instrumentDropDown<?php echo $counter; ?>" class="btn-group dropdownTextContainer" style="display: block; border: solid 1px #ccc; width: 100%; height: 2.13em;">
                            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" style="width: 100%; padding-top: 3px;">
                                <span class="dropdownText">
                                    <?php echo (isset($result['res_instrument_serial']) && $result['res_instrument_serial'] != "" ? $result['res_instrument_serial'] : "-- Select --") ?>
                                </span>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu instrument-list">
<?php
    foreach ($this->instruments as $id => $instrument_details) {
        if ($id != "-1") { ?>
                                <li class="instrument-list-item">
                                    <a href="" onClick='return changeInstrument({serial: "<?php echo $instrument_details["instrument_serial"]; ?>", installedOn: "<?php echo $this->dateFormat($instrument_details["instrument_installed_on"]); ?>", lastCalibratedOn: "<?php echo $this->dateFormat($instrument_details["instrument_last_calibrated_on"]); ?>", dropDownId: "instrumentDropDown<?php echo $counter; ?>", serialTextFieldId: "instrumentSerial<?php echo $counter; ?>", installedOnTextFieldId: "instrumentInstalledOn<?php echo $counter; ?>", lastCalibratedOnTextFieldId: "instrumentLastCalibratedOn<?php echo $counter; ?>"})'>
                                        <?php echo $instrument_details['instrument_serial']; ?>
                                    </a>
                                </li>
<?php
        }
    } ?>
                            </ul>
                        </div>
                    </th>
                    <th style="vertical-align: top;white-space: nowrap;background-color: transparent;">
                        <input type="text" name="moduleName[<?php echo $index; ?>]" class="form-control input-sm"
                               value="<?php echo $result['res_module_name']; ?>"
                               title="Please enter the module number for <?php echo $result['sample_label']; ?>" />
                    </th>
                    <th colspan="3" style="vertical-align: top;white-space: nowrap;background-color: transparent;">
                        <input type="text" name="instrumentUser[<?php echo $index; ?>]" class="form-control input-sm"
                               value="<?php echo $result['res_instrument_user']; ?>"
                               title="Please enter the instrument user for <?php echo $result['sample_label']; ?>" />
                    </th>
                </tr>
            </table>
        </td>
    </tr>
    <tr class="<?php echo $class ?>"></tr>
<?php
    $index++;
    $counter++;
} ?>
</table>
<script>
  function toggleToEnterResults() {
    if ($("input[name='ableToEnterResults']:checked").val() === "yes") {
      $("#ableToEnterResultsReasonsRow").hide();
      $("#transferToParticipantRow").hide();
      $("#ableToEnterResultsOtherReasonRow").hide();
      $("#notTestedReason").val("");
      $("#notTestedOtherReason").val("");
      $("#submissionHeader").find("input,select,textarea").removeAttr("disabled");
      $("#submissionHeader").find("input,select,textarea").not(".datepicker").removeAttr("readonly");
      $("#results").find("input,select,textarea").removeAttr("disabled");
      $("#results").find("input,select,textarea").not(".datepicker").removeAttr("readonly");
      $("#results").find(".btn.dropdown-toggle").attr("data-toggle", "dropdown");
      $("#results").find(".btn.dropdown-toggle").attr("href", "#");
      $("#results").find(".dropdownTextContainer").removeAttr("disabled");
      $("#submissionFooter").find("input,select,textarea").removeAttr("disabled");
      $("#submissionFooter").find("input,select,textarea").not(".datepicker").removeAttr("readonly");
      for (var i = 1; i <= 5; i++) {
        changeMtbDetected(i)
      }
    } else if ($("input[name='ableToEnterResults']:checked").val() === "no") {
      $("#ableToEnterResultsReasonsRow").show();
      $("#transferToParticipantRow").show();
      $("#submissionHeader").find("input,select,textarea").attr("disabled", "");
      $("#submissionHeader").find("input,select,textarea").not(".datepicker").attr("readonly", "");
      $("#results").find("input,select,textarea").attr("disabled", "");
      $("#results").find("input,select,textarea").not(".datepicker").attr("readonly", "");
      $("#results").find(".btn.dropdown-toggle").removeAttr("data-toggle");
      $("#results").find(".btn.dropdown-toggle").removeAttr("href");
      $("#results").find(".dropdownTextContainer").attr("disabled", "");
      $("#submissionFooter").find("input,select,textarea").attr("disabled", "");
      $("#submissionFooter").find("input,select,textarea").not(".datepicker").attr("readonly", "");
    }
  }

  var analyteLables = {
  <?php foreach ($this->assays as $id => $definition) {
    echo "    \"".$id."\": {\n";
    echo "      \"analyte1Label\": \"".$definition['analyte1Label']."\",\n";
    echo "      \"analyte2Label\": \"".$definition['analyte2Label']."\",\n";
    echo "      \"analyte3Label\": \"".$definition['analyte3Label']."\",\n";
    echo "      \"analyte4Label\": \"".$definition['analyte4Label']."\",\n";
    echo "      \"analyte5Label\": \"".$definition['analyte5Label']."\",\n";
    echo "      \"analyte6Label\": \"".$definition['analyte6Label']."\",\n";
    echo "      \"includeTraceForMtbDetected\": ".$definition['includeTraceForMtbDetected']."\n";
    echo "    },\n";
  } ?>
  };
  function setAssay() {
    var selectedAssayId = $("#assay").val();
    if (!selectedAssayId) {
      selectedAssayId = Object.keys(analyteLables)[0];
    }
    var selectedAssayDefinition = analyteLables[selectedAssayId];
    $(".probe1Header").text(selectedAssayDefinition['analyte1Label']);
    $(".probe2Header").text(selectedAssayDefinition['analyte2Label']);
    $(".probe3Header").text(selectedAssayDefinition['analyte3Label']);
    $(".probe4Header").text(selectedAssayDefinition['analyte4Label']);
    $(".probe5Header").text(selectedAssayDefinition['analyte5Label']);
    $(".probe6Header").text(selectedAssayDefinition['analyte6Label']);
    if (selectedAssayDefinition['includeTraceForMtbDetected'] && !$(".mtbDetected option[value='trace']").length) {
      $("<option value='trace'>Trace</option>").insertAfter(".mtbDetected option[value='veryLow']");
    } else if (!selectedAssayDefinition['includeTraceForMtbDetected']) {
      $(".mtbDetected option[value='trace']").remove();
    }
  }

  $(function() {
    var today = new Date('<?php echo date("Y-m-d") ?>');
    $(".datepicker.allowFutureDate")
      .datepicker({
        dateFormat: '<?php echo $dtFormat;?>'
      });

    $(".datepicker:not(.instrument-date-picker,.allowFutureDate)")
      .datepicker({
        dateFormat: '<?php echo $dtFormat;?>',
        beforeShowDay: function(date){
          return [date <= today, ""];
        }
      });

    $(".instrument-date-picker").datepicker({
      dateFormat: '<?php echo $dtFormat;?>',
      onSelect: updateInstrumentLists,
      beforeShowDay: function(date){
        return [date <= today, ""];
      }
    });

    <?php if (!$this->isEditable) { ?>
    $("#tbResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
    <?php } ?>

    $("input[name='ableToEnterResults']").on('click change', toggleToEnterResults);

    $("#notTestedReason").on('change', function(e) {
      if ($("#notTestedReason").val() === "other") {
        $("#ableToEnterResultsOtherReasonRow").show();
      } else {
        $("#ableToEnterResultsOtherReasonRow").hide();
        $("#notTestedOtherReason").val("");
      }
    });
    toggleToEnterResults();
    $("#assay").on('change', setAssay);
    setAssay();
  });

  function clearDate(id) {
    if ($("input[name='ableToEnterResults']:checked").val() === "yes") {
      $("#" + id).val('');
    }
  }

  function changeInstrument(details) {
    $("#" + details.serialTextFieldId).val(details.serial);
    $("#" + details.dropDownId + " a span.dropdownText").text(details.serial);
    return false;
  }

  function changeMtbDetected(resultNumber) {
    var mtbDetected = $("#mtbDetected" + resultNumber).val();
    var errorCodeInput = $("#errorCode" + resultNumber);
    var rifResistanceSelect = $("#rifResistance" + resultNumber);
    if (mtbDetected === "error") {
      errorCodeInput.removeAttr("disabled");
      errorCodeInput.removeAttr("readonly");
    } else {
      errorCodeInput.attr("disabled", "");
      errorCodeInput.attr("readonly", "");
      errorCodeInput.val('')
    }
    if (["detected", "high", "medium", "low", "veryLow"].includes(mtbDetected)) {
      rifResistanceSelect.removeAttr("disabled");
      rifResistanceSelect.removeAttr("readonly");
    } else if (mtbDetected === "trace") {
      rifResistanceSelect.attr("disabled", "");
      rifResistanceSelect.attr("readonly", "");
      rifResistanceSelect.val('indeterminate')
    } else {
      rifResistanceSelect.attr("disabled", "");
      rifResistanceSelect.attr("readonly", "");
      rifResistanceSelect.val('na')
    }
  }

  function checkQcStatus() {
    var radioValue = $("input[name='qcDone']:checked").val();
    if (radioValue == "yes") {
      $("#qcSection").show();
      $("#qcDate").addClass("isRequired");
      $("#qcDoneBy").addClass("isRequired");
    } else {
      $("#qcSection").hide();
      $("#qcDate").val("");
      $("#qcDoneBy").val("");
      $("#qcDate").removeClass("isRequired");
      $("#qcDoneBy").removeClass("isRequired");
    }
  }

  var newInstrumentIndex = <?php echo count($this->instruments) ?>;
  var instrumentsMap = {
  <?php
    $instrumentsListIndex = 0;
  foreach ($this->instruments as $id => $instrument_details) { ?>
    '<?php echo $instrumentsListIndex ?>': {
      id: <?php echo $id; ?>,
      serial: "<?php echo $instrument_details['instrument_serial'] ?>",
        installed: "<?php echo $this->dateFormat($instrument_details['instrument_installed_on']); ?>",
        calibrated: "<?php echo $this->dateFormat($instrument_details['instrument_last_calibrated_on']); ?>"
    },
  <?php
      $instrumentsListIndex++;
  } ?>
  };

  function addInstrumentRow(obj) {
    if ($("input[name='ableToEnterResults']:checked").val() === "yes") {
      $(obj.parentNode.parentNode).after('<tr id="instrumentRow' + newInstrumentIndex + '">\
      <td>\
        <input type="hidden" name="headerInstrumentIndex[' + newInstrumentIndex + ']"\
          class="instrumentIndex" value="' + newInstrumentIndex + '" />\
        <input type="text" name="headerInstrumentSerial[' + newInstrumentIndex + ']"\
          class="form-control input-sm" onblur="updateInstrumentLists()"\
          title="Please enter the instrument serial number" />\
      </td>\
      <td>\
        <input type="text" class="form-control datepicker input-sm new-instrument-date-picker" readonly="readonly"\
          name="headerInstrumentInstalledOn[' + newInstrumentIndex + ']"\
          title="Please enter the instrument installation date" />\
      </td>\
      <td>\
        <input type="text" class="form-control datepicker input-sm new-instrument-date-picker" readonly="readonly"\
            name="headerInstrumentLastCalibratedOn[' + newInstrumentIndex + ']"\
            title="Please enter the date that the instrument was last calibrated" />\
      </td>\
      <td>\
        <a href="javascript:void(0);" onclick="addInstrumentRow(this);" class="btn btn-xs btn-info">\
          <i class="icon-plus"></i>\
        </a>&nbsp;&nbsp;\
        <a href="javascript:void(0);" onclick="removeInstrumentRow(this)" class="btn btn-xs btn-danger"\
          title="Remove this instrument" alt="Remove this instrument">\
          <i class="icon-minus"></i>\
        </a>\
      </td>\
    </tr>');
      instrumentsMap[newInstrumentIndex + ''] = {
        serial: "",
        installed: "",
        calibrated: ""
      };
      var today = new Date('<?php echo date("Y-m-d") ?>');
      $(".new-instrument-date-picker").datepicker({
        dateFormat: '<?php echo $dtFormat;?>',
        onSelect: updateInstrumentLists,
        beforeShowDay: function(date){
          return [date <= today, ""];
        }
      });
      newInstrumentIndex++;
    }
  }

  function removeInstrumentRow(obj) {
    if ($("input[name='ableToEnterResults']:checked").val() === "yes") {
      if (Object.keys(instrumentsMap).length == 1) {
        addInstrumentRow(obj);
      }
      var removeInstrumentIndex = $(obj.parentNode.parentNode).find('.instrumentIndex').val();
      $(obj.parentNode.parentNode).fadeOut("normal", function () {
        $(this).remove();
      });
      delete instrumentsMap[removeInstrumentIndex];
      updateInstrumentLists();
    }
  }

  function updateInstrumentLists() {
    var instrumentIndices = Object.keys(instrumentsMap);
    instrumentIndices.forEach(function (instrumentIndex) {
      var instrumentSerial = $('[name="headerInstrumentSerial[' + instrumentIndex + ']"]').val();
      var installed = $('[name="headerInstrumentInstalledOn[' + instrumentIndex + ']"]').val();
      var calibrated = $('[name="headerInstrumentLastCalibratedOn[' + instrumentIndex + ']"]').val();
      var instrumentId = undefined;
      var instrumentIdField = $('[name="headerInstrumentId['+ instrumentIndex + ']"]');
      if (instrumentIdField) {
        instrumentId = instrumentIdField.val();
      }
      instrumentsMap[instrumentIndex] = {
        id: instrumentId,
        serial: instrumentSerial,
        installed: installed,
        calibrated: calibrated
      }
    });
    $('.instrument-list-item').remove();
    instrumentIndices = Object.keys(instrumentsMap);
    $('.instrument-list').each(function (elementIndex, instrumentUl) {
      var sampleNumber = $(instrumentUl).parent().attr('id').replace('instrumentDropDown', '');
      instrumentIndices.reverse().forEach(function (instrumentIndex) {
        $(instrumentUl).prepend('<li class="instrument-list-item">\
  <a href="" onClick="return changeInstrument({serial: \'' + instrumentsMap[instrumentIndex].serial + '\', dropDownId: \'instrumentDropDown' + sampleNumber + '\', serialTextFieldId: \'instrumentSerial' + sampleNumber + '\'})">\
    ' + instrumentsMap[instrumentIndex].serial + '\
  </a>\
</li>');
      });
    });
  }
</script>
