<?php
if($this->result!=""){
    $fileName=$this->result['lab_name']."-".$this->result['map_id'].".pdf";

    $fileName = preg_replace('/[^A-Za-z0-9.]/', '-', $fileName);
    $fileName = str_replace(" ", "-", $fileName);

    $fileSafeShipmentCode = str_replace(array_merge(
        array_map('chr', range(0, 31)),
        array('<', '>', ':', '"', '/', '\\', '|', '?', '*')), '', $this->result['shipment_code']);
    $file = UPLOAD_PATH. DIRECTORY_SEPARATOR."reports". DIRECTORY_SEPARATOR.$fileSafeShipmentCode.DIRECTORY_SEPARATOR.$fileName;

    if (file_exists($file)) {
        echo "<h2 align='center' style='margin-top:100px;font-family:arial;'>Requested image will be downloaded shortly, After downloaded please close the window </h2>";
        header('Content-Description: Report Download');
        header('Content-Type: application/pdf');
        header('Content-Disposition: inline');
        header('Content-Transfer-Encoding: binary');
        header('Expires: 0');
        header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
        header('Pragma: public');
        header('Content-Length: ' . filesize($file));
        ob_clean();
        flush();
        readfile($file);
        exit;
    } else {
        echo "<h2 align='center' style='margin-top:100px;font-family:arial;'>Requested report does not exist</h2>";
    }
}
?>
