<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<meta charset="UTF-8">
<?php
if (isset($this->url)) { ?>
<link href="<?php echo $this->baseUrl('assets/plugins/jQuery/jquery.touchPDF.css'); ?>" rel="stylesheet" media="screen" />
<?php
} ?>
<style>
body, html{
  background-color: #404040;
  height: 100%;
  padding: 0;
  margin: 0;
}
</style>
</head>
<body>
<?php
if (isset($this->url)) { ?>
<div id="report-canvas" style="height: 95%; width: 95%; margin: auto;"></div>

<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jQuery/pdf.compatibility.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jQuery/pdf.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jQuery/jQuery-2.1.4.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jQuery/jquery.touchSwipe.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jQuery/jquery.touchPDF.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jQuery/jquery.panzoom.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/plugins/jQuery/jquery.mousewheel.js'); ?>"></script>
<script type="text/javascript">
  $(function() {
    $("#report-canvas").pdf({
      source: '<?php echo $this->url ?>',
      showToolbar: false
    });
  });
</script>
<?php
} else { ?>
<h1>Unauthorised</h1>
<?php
} ?>
</body>
</html>