<?php
$authNameSpace = new Zend_Session_Namespace('datamanagers');
$genderHelper = $this->getHelper('DateFormat');
$dtFormat=  $genderHelper->getDateFormat();
$activeSchemes = array();
if(isset($this->schemes) && count($this->schemes) >0 ){
    foreach($this->schemes as $scheme){
	$activeSchemes[] = $scheme['scheme_id'];
    }
}
?>
<style>
    .green{
	background-color:green;
    }
    .red{
	background-color:red;
    }
</style>
<section class="content-header">
    <h1> Dashboard </h1>
</section>
<section class="content">
    <?php if (count($this->monthly_indicators) > 0) { ?>
        <div class="box">
            <div class="box-body">
                <h3 class="txt text-info">Monthly Indicators - <?php echo date('M Y'); ?></h3>
                <?php foreach ($this->monthly_indicators as $monthly_indicator) {
                    $attributes = array();
                    if (isset($monthly_indicator['attributes'])) {
                        $attributes = json_decode($monthly_indicator['attributes'], true);
                    } ?>
                <h3 class="txt text-info"><?php echo $monthly_indicator['unique_identifier'].' - '.$monthly_indicator['participantName'] ?></h3>
                <table class="table table-bordered table-striped" style="width:100%; margin: 10px auto;">
                    <tr class="dark">
                        <td style="width: 25%;">
                            <label>How many Xpert MTB/RIF and MTB Ultra tests have been conducted by this site in the last full month?</label>
                        </td>
                        <td style="width: 25%;">
                            <input type="text" name="countTestsConductedOverMonth_<?php echo $monthly_indicator['participant_id'] ?>" id="countTestsConductedOverMonth_<?php echo $monthly_indicator['participant_id'] ?>"
                                   class="form-control zeroDecimal numberInput"
                                   value="<?php if(isset($attributes['countTestsConductedOverMonth'])) { echo $attributes['countTestsConductedOverMonth']; }?>" />
                        </td>
                        <td style="width: 25%;">
                            <label>How many errors occurred during testing in the last full month?</label>
                        </td>
                        <td style="width: 25%;">
                            <input type="text" name="countErrorsEncounteredOverMonth_<?php echo $monthly_indicator['participant_id'] ?>" id="countErrorsEncounteredOverMonth_<?php echo $monthly_indicator['participant_id'] ?>"
                                   class="form-control zeroDecimal numberInput"
                                   value="<?php if(isset($attributes['countErrorsEncounteredOverMonth'])) { echo $attributes['countErrorsEncounteredOverMonth']; }?>" />
                        </td>
                    </tr>
                    <tr class="light">
                        <td>
                            <label>What were the error codes?</label>
                        </td>
                        <td colspan="3">
                            <input type="text" name="errorCodesEncounteredOverMonth_<?php echo $monthly_indicator['participant_id'] ?>" id="errorCodesEncounteredOverMonth_<?php echo $monthly_indicator['participant_id'] ?>" class="form-control"
                                   value="<?php if(isset($attributes['errorCodesEncounteredOverMonth'])) { echo $attributes['errorCodesEncounteredOverMonth']; }?>" />
                        </td>
                    </tr>
                </table>
                <?php } ?>
                <div style="margin: 0px auto 0px auto; text-align: center;">
                    <p> &nbsp;&nbsp;&nbsp;
                        <input name="submitbtn" class="btn btn-success" type="submit" value="Submit" onclick="javascript:submitMonthlyIndicatorForm()" />
                    </p>
                </div>
            </div>
        </div>
    <?php } ?>
	<?php if (count($activeSchemes) > 0 && in_array('tb',$activeSchemes)) { ?>
		<div class="box">
                    <div class="box-body">
			    <h3 class="txt text-info">Dried Tube Specimen - Tuberculosis</h3>
			    <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="dtsTuberculosisTable">
				    <thead>
					<tr>
					    <th>Shipment Date</th>
					    <th>Shipment Code</th>
						<th>Participant Id</th>
					    <th>Participant</th>
					    <th>Response Date</th>
					    <th>Performance</th>
					</tr>
				    </thead>
				    <tbody>
					<tr>
					  <td colspan="6" class="dataTables_empty">Loading data from server</td>
					</tr>
				    </tbody>
			    </table>
		    </div>
		</div>
	<?php } ?>
		<div class="box">
                <div class="box-body">
					<h3 class="txt text-info">Schemes Overview</h3>
					<table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="overviewTable">
						<thead>
						    <tr>
							<th>Year</th>
							<th>Scheme Type</th>
							<th>Total Schemes <br>Shipped</th>
							<th>Reported Within <br>Due Date</th>
							<th>Responses <br>not received yet</th>
						    </tr>
						</thead>
						<tbody>
						    <tr>
						      <td colspan="5" class="dataTables_empty">Loading data from server</td>
						    </tr>
						</tbody>
					</table>
				</div>
		</div>
        <div class="box">
            <div class="box-body">
                <h3 class="txt text-info">All Shipments</h3>
                <?php if ($this->globalQcAccess=='yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access=='yes')) { ?>
                <table class="table">
                    <tr>
                        <td style="width:100%;">
                            <select id="qualityChecked" name="qualityChecked" onchange="schemeTable.fnDraw()"  class="form-control">
                            <option value=""> -- Filter QC Checked Responses --</option>
                            <option value="yes">Show QC Checked Responses</option>
                            <option value="no">Show Not QC Checked Responses</option>
                            </select>
                        </td>
                    </tr>
                </table>
                <input type="hidden" name="participantMapId" id="participantMapId"/>
                <div style="padding-top:20px;display:none;" id="qcTopButton">
                    <a href="javascript:void(0)" onclick="checkQcStatus()" class="btn btn-primary btn-sm" style="margin-bottom: 15px;"><i class="fa fa-cogs"></i>&nbsp;<b>(<span id="qcCount">0</span>) Selected for Bulk Quality Check</b></a>
                </div>
                <?php } ?>
                <table cellpadding="0" cellspacing="0" border="0" class="display datatable table table-bordered table-hover table-striped " id="allSchemeTable">
                    <thead>
                        <tr>
                        <th></th>
                        <th style="width:30px;">Year</th>
                        <th style="width:100px;">Shipment<br/>Date</th>
                        <th style="width:50px;">Scheme</th>
                        <th style="width:100px;">Shipment Code</th>
                        <th>Participant Id</th>
                        <th>Participant</th>
                        <th style="width:100px;">Response<br/>Date</th>
                        <th style="width:100px;">Action</th>
                        <th>Report</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                        <td colspan="10" class="dataTables_empty">Loading data from server</td>
                        </tr>
                    </tbody>
                </table>
			</div>
		</div>
</section>
<div class="deleteAction dialog" id="migrateBox">
	<div style="padding:10px;">
        <span onClick="hidedefModal()" class="closeModal"></span>
        <h3>Quality Check Done</h3>
        <table  class="display datatable table table-bordered table-hover table-striped ">
			<tr>
				<th>Maintenance Done on : </th>
				<td><input type="text" id="qcDate" name="qcDate"  style="width:180px;float:left;"  maxlength="11" value=""  class="isRequired form-control" readonly="readonly" /></td>
			</tr>
		</table>
		<div class="box-footer" style="text-align: center">
			<button class="btn btn-primary" onclick="submitQcForm();return false;">Submit</button>
		</div>
    </div>
</div>
<script>
    var s1Table = null;
	var s2Table = null;
	var s3Table = null;
	var s4Table = null;
	var s5Table = null;
	sOneLastShipmentRow = [];
	sOneLastShipmentRowColor = [];
	sTwoLastShipmentRow = [];
	sTwoLastShipmentRowColor = [];
	<?php if (count($activeSchemes) > 0 && in_array('tb',$activeSchemes)) { ?>
	function dtsTuberculosisSchemes() {
		s2Table = $('#dtsTuberculosisTable').dataTable({
			"oLanguage": {
			    "sLengthMenu": "_MENU_ records per page"
			},
			"bJQueryUI": false,
			"bAutoWidth": false,
			"bInfo": true,
			"bScrollCollapse": true,
			"sPaginationType": "full_numbers",
			"bRetrieve": true,
			"aoColumns": [
			    { "sClass": "center" },
			    { "sClass": "center" },
			    { "sClass": "center" },
			    { "sClass": "center" },
			    { "sClass": "center" },
			    { "sClass": "center" }
			],
			"fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
			    if($.inArray(aData[1], sTwoLastShipmentRow) == -1){
				sTwoLastShipmentRow = [];
				sTwoLastShipmentRow.push(aData[1]);
				if($.inArray("#ecf1ef", sTwoLastShipmentRowColor) == -1){
				    sTwoLastShipmentRowColor = [];
				    sTwoLastShipmentRowColor.push("#ecf1ef");
				    $(nRow).attr("class","");
				    $(nRow).css("background-color","#ecf1ef");
				}else{
				    sTwoLastShipmentRowColor = [];
				    sTwoLastShipmentRowColor.push("#fffff2");
				    $(nRow).attr("class","");
				    $(nRow).css("background-color","#fffff2");
				}
			    }else{
				if($.inArray("#ecf1ef", sTwoLastShipmentRowColor) == -1){
				    $(nRow).attr("class","");
				    $(nRow).css("background-color","#fffff2");
				}
				if($.inArray("#fffff2", sTwoLastShipmentRowColor) == -1){
				    $(nRow).attr("class","");
				    $(nRow).css("background-color","#ecf1ef");
				}
			    }
			},
			"aaSorting": [[ 0, "desc" ]],
			"bProcessing": true,
			"bServerSide": true,
			"sAjaxSource": "<?php echo $this->url(array('module' => 'default', 'controller' => 'participant', 'action' => 'scheme', 'format' => 'html')); ?>",
			"fnServerData": function ( sSource, aoData, fnCallback ) {
			    aoData.push({"name": "scheme", "value": "tb"});
			    $.ajax({
				"dataType": 'json',
				"type": "POST",
				"url": sSource,
				"data": aoData,
				"success": fnCallback
			    });
			}
		});
	}
	<?php } ?>
	sThreeLastShipmentRow = [];
	sThreeLastShipmentRowColor = [];
	sFiveLastShipmentRow = [];
	sFiveLastShipmentRowColor = [];
	$(document).ready(function() {
	    <?php if (count($activeSchemes) > 0 && in_array('tb',$activeSchemes)) { ?>
	    dtsTuberculosisSchemes();
	    <?php } ?>
	});

	var oTable = null;
	function overviewSchemes() {
		oTable = $('#overviewTable').dataTable({
			"oLanguage": {
			    "sLengthMenu": "_MENU_ records per page"
			},
			"bJQueryUI": false,
			"bFilter": false,
			"bAutoWidth": false,
			"bInfo": true,
			"bScrollCollapse": true,
			"sPaginationType": "full_numbers",
			"bRetrieve": true,
			"aoColumns": [
			    { "sClass": "center" },
			    { "sClass": "center" },
			    { "sClass": "center", "bSortable": false },
			    { "sClass": "center", "bSortable": false },
			    { "sClass": "center", "bSortable": false }
			],
			"aaSorting": [[ 0, "desc" ]],
			"bProcessing": true,
			"bServerSide": true,
			"sAjaxSource": "<?php echo $this->url(array('module' => 'default', 'controller' => 'participant', 'action' => 'index', 'format' => 'html')); ?>",
			"fnServerData": function(sSource, aoData, fnCallback) {
			    $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
			    });
			}
		});
	}

	$(document).ready(function() {
		overviewSchemes();
	});

    var schemeTable = null;
	var selectedQc=[];
	function allSchemes() {
		schemeTable = $('#allSchemeTable').dataTable({
			"oLanguage": {
			    "sLengthMenu": "_MENU_ records per page"
			},
			"bJQueryUI": false,
			"bAutoWidth": false,
			"bInfo": true,
			"bScrollCollapse": true,
			"sPaginationType": "full_numbers",
			"bRetrieve": true,
			"aoColumns": [
				{ "bSortable": false },
			    { "sClass": "center" },
			    { "sClass": "center" },
			    { "sClass": "center" },
                { "sClass": "center" },
			    { "sClass": "" },
			    { "sClass": "" },
			    { "sClass": "center" },
			    { "sClass": "center", "bSortable":false },
			    { "sClass": "center", "bSortable":false }
			],
			"aaSorting": [[ 1, "desc" ]],
			"fnDrawCallback": function() {
                var checkBoxes=document.getElementsByName("subchk[]");
                len = checkBoxes.length;
                for (c = 0; c < len; c++) {
                    if (jQuery.inArray(checkBoxes[c].id,selectedQc) != -1 ) {
                        checkBoxes[c].setAttribute("checked", true);
                    }
                }
            },
			"bProcessing": true,
			"bServerSide": true,
			"sAjaxSource": "<?php echo $this->url(array('module' => 'default', 'controller' => 'participant', 'action' => 'all-schemes', 'format' => 'html')); ?>",
			"fnServerParams": function (aoData) {
                aoData.push({"name": "qualityChecked", "value": $("#qualityChecked").val()});
				if ($("#qualityChecked").val() == 'yes') {
					$("#qcTopButton").show();
				} else {
					$("#qcTopButton").hide();
				}
            },
			"fnServerData": function(sSource, aoData, fnCallback ) {
			    $.ajax({
				    "dataType": 'json',
				    "type": "POST",
				    "url": sSource,
				    "data": aoData,
				    "success": fnCallback
			    });
			}
		});
	}

	$(document).ready(function(){
		allSchemes();
	});

    function removeSchemes(schemeType,mid){
		if (window.confirm("Are you sure you want to remove this response?\n This cannot be undone !")) {
			$.blockUI();
			$.post("<?php echo $this->url(array('module'=>'default','controller' =>'common', 'action' => 'delete-response')); ?>", { schemeType:schemeType, mid: mid, format: "html" },
			    function (data) {
				alert("Response removed successfully");
				schemeTable.fnDraw();
				$.unblockUI();
			});
		}
	}

	function addQc(mapId,obj) {
		if (obj.checked == true)
        {
			if ($.inArray(mapId,selectedQc) == -1) {
			    selectedQc.push(mapId);
			}
		} else {
			selectedQc.remove(mapId);
		}
		$("#participantMapId").val(selectedQc);
		$("#qcCount").text(selectedQc.length);
    }

	function addSingleQc(mapId, qcDate) {
        if($.inArray(mapId,selectedQc) == -1){
			selectedQc.push(mapId);
			$("#participantMapId").val(selectedQc);
		}
		showQcForm();
    }

	function showQcForm() {
        showdefModal("migrateBox", 600,400);
        var today = new Date('<?php echo date("Y-m-d") ?>');
        $("#qcDate").datepicker({
		  dateFormat: '<?php echo $dtFormat; ?>',
          beforeShowDay: function(date) {
            return [date <= today, ""];
          }
		});
    }

	function submitQcForm() {
		participantMapId = $("#participantMapId").val();
		qcDate = $("#qcDate").val();
		if (participantMapId != "" && qcDate != "") {
            $.post("<?php echo $this->url(array('module'=>'default','controller' =>'participant', 'action' => 'add-qc')); ?>", { mapId: participantMapId,qcDate:qcDate,format: "html" },
			function(data) {
                if (data > 0) {
                    schemeTable.fnDraw();
                    $("#countChecksPending").text("0");
                    selectedQc = '';
                    alert("Monthly Maintenance details added successfully");
                    hidedefModal();
                }
			});

        } else {
			alert("Please select the date");
		}
    }

    function submitMonthlyIndicatorForm() {
        var participantIds = [
            <?php foreach ($this->monthly_indicators as $monthly_indicator) {
                echo $monthly_indicator['participant_id'].",";
            } ?>
        ];
        var monthlyIndicators = { participants: [] };
        for (var i = 0; i < participantIds.length; i++) {
            monthlyIndicators.participants.push({
                participantId: participantIds[i],
                countTestsConductedOverMonth: $('#countTestsConductedOverMonth_' + participantIds[i]).val(),
                countErrorsEncounteredOverMonth: $('#countErrorsEncounteredOverMonth_' + participantIds[i]).val(),
                errorCodesEncounteredOverMonth: $('#errorCodesEncounteredOverMonth_' + participantIds[i]).val()
            });
        }
        $.post(
            "<?php echo $this->url(array('module'=>'default','controller' =>'participant', 'action' => 'submit-monthly-indicators')); ?>",
            monthlyIndicators,
            function(data) {
                console.log(data)
            });
    }

	function checkQcStatus() {
        if (selectedQc.length == 0) {
			alert("Please select at least one shipment to proceed with QC");
		} else {
			showQcForm();
		}
    }
</script>
