<?php
date_default_timezone_set('America/New_York');
$authNameSpace = new Zend_Session_Namespace('datamanagers');
if (isset($this->shipment["shipment_test_report_date"]) &&
    trim($this->shipment["shipment_test_report_date"]) != "") {
    $expTestReceiptDate = explode(" ",$this->shipment["shipment_test_report_date"]);
    $testReceiptDate = $this->dateFormat($expTestReceiptDate[0]);
} else {
	$testReceiptDate = date('d-M-Y');
}
?>
<style>
    th {
        text-align: center;
    }
	table,th,td {
		border-color: #ccc !important;
	}
	.hideOtherAssay {
		display: none;
	}
</style>
<section class="content-header">
    <h1><?php echo $this->shipment['scheme_name'];?></h1>
</section>
<section class="content">
<div class="box">
<form name="tbResponseForm" id="tbResponseForm" method="post"
      action="<?php echo $this->url(array("controller"=>"tb","action"=>"response"),null,true) ?>"
      onsubmit="return validateNow();return false;">
<div class="box-body">
<input type="hidden" id ="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response'];?>" />
<input type="hidden" id ="smid" name="smid" value="<?php echo $this->shipment['map_id'];?>" />
<input type="hidden" id ="shipmentId" name="shipmentId" value="<?php echo $this->shipId;?>" />
<input type="hidden" id ="participantId" name="participantId" value="<?php echo $this->participantId;?>" />
<input type="hidden" id ="evId" name="evId" value="<?php echo $this->eID;?>" />
<?php $count =0;  
foreach ($this->allSamples as $sample) {
    $count++;  ?>
<input type="hidden" id ="<?php echo $count . "_hdSampleId"; ?>" name="<?php echo $count . "_hdSampleId"; ?>"
       value="<?php echo $sample['sample_id'];?>" />
<?php
} ?>
<div id="view-content">
<br />
<div id=error></div>
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
    <tr>
        <td style="width:20%;">
            <h4 class="text-info"> Participant Name </h4>&nbsp;
            <?php echo ( $this->participant['first_name'] . ' ' . $this->participant['last_name'] );?>
        </td>
        <td style="width:20%;">
            <h4 class="text-info"> Participant Code </h4>&nbsp;
            <?php echo $this->participant['unique_identifier'] ?>
        </td>
        <td style="width:20%;">
            <h4 class="text-info"> Affiliation </h4>&nbsp;
            <?php echo ( $this->participant['affiliation'] );?>
        </td>
        <td style="width:20%;">
            <h4 class="text-info"> Phone No </h4>&nbsp;
            <?php  echo ( $this->participant['mobile']  . '<br/>' .   $this->participant['phone'] ); ?>
        </td>
    </tr>
</table>
<hr />
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
	<tr class="dark">
		<td style="width:20%;">
            <label>Shipment Date</label>
        </td>
		<td style="width:30%;">
            <?php echo $this->dateFormat($this->shipment['shipment_date']) ?>
        </td>
		<td style="width:20%;">
            <label>Result Due Date</label>
        </td>
		<td style="width:30%;">
            <?php echo $this->dateFormat($this->shipment['lastdate_response']);?>
        </td>
	</tr>
	<tr class ="light">
		<td style="width:20%; white-space: nowrap;">
            <label>Shipment Receipt Date</label>
            <span class='mandatory'>*</span>
        </td>
		<td style="width:30%;">
			<input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;"
                   value="<?php  echo $this->dateFormat($this->shipment["shipment_receipt_date"]);  ?>"
                   class="form-control isRequired datepicker" readonly="readonly" />&nbsp;
			<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('receiptDate')"> Clear</i>
		</td>
        <td style="white-space: nowrap;">
            <label>Assay</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <select class="form-control" name="assay" id="assay" class="form-control"
                    title="Please choose the assay type">
                <?php
                foreach ($this->assays as $id => $name) { ?>
                    <option value="<?php echo $id; ?>"
                        <?php if (isset($this->shipment['attributes']['assay'])) { echo ($this->shipment['attributes']['assay'] == $id) ? "selected='selected'" : ""; } ?>>
                        <?php echo $name; ?>
                    </option>
                    <?php
                } ?>
            </select>
        </td>
	</tr>
    <tr class ="dark">
		<td style="white-space: nowrap;">
            <label>MTB/RIF Kit Lot No</label>
            <span class='mandatory'>*</span>
        </td>
		<td>
		    <input type="text" name="mtbRifKitLotNo" id="mtbRifKitLotNo" class="form-control isRequired"
                   value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no'];?>"/>
		</td>
		<td style="width:20%; white-space: nowrap;">
            <label>Expiration date of MTB/RIF Kit</label>
            <span class='mandatory'>*</span>
        </td>
		<td style="width:30%;">
			<input type="text" name="expiryDate" id="expiryDate" class="form-control isRequired datepicker"
                   size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date'];?>"
                   readonly="readonly"/>&nbsp;
			<i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('expiryDate')"> Clear</i>
		</td>
	</tr>
    <tr class="light">
        <td style="white-space: nowrap;">
            <label>Response Date</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11"
                   style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker"
                   readonly="readonly" title="Please enter Shipment Test Response Date " />&nbsp;
            <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('testReceiptDate')"> Clear</i>
        </td>
        <td colspan="2"></td>
    </tr>
    <tr class="dark">
        <td>
            <label>How many Xpert MTB/RIF tests have been conducted by this site in the last full month?</label>
        </td>
        <td>
            <input type="text" name="countTestsConductedOverMonth" id="countTestsConductedOverMonth"
                   class="form-control zeroDecimal numberInput"
                   value="<?php if(isset($this->shipment['attributes']['count_tests_conducted_over_month'])) { echo $this->shipment['attributes']['count_tests_conducted_over_month']; }?>" />
        </td>
        <td>
            <label>How many errors occurred during testing in the last full month?</label>
        </td>
        <td>
            <input type="text" name="countErrorsEncounteredOverMonth" id="countErrorsEncounteredOverMonth"
                   class="form-control zeroDecimal numberInput"
                   value="<?php if(isset($this->shipment['attributes']['count_errors_encountered_over_month'])) { echo $this->shipment['attributes']['count_errors_encountered_over_month']; }?>" />
        </td>
    </tr>
    <tr class="light">
        <td>
            <label>What were the error codes?</label>
        </td>
        <td colspan="3">
            <input type="text" name="errorCodesEncounteredOverMonth" id="errorCodesEncounteredOverMonth" class="form-control"
                   value="<?php if(isset($this->shipment['attributes']['error_codes_encountered_over_month'])) { echo $this->shipment['attributes']['error_codes_encountered_over_month']; }?>" />
        </td>
    </tr>
    <?php
	if ($this->globalQcAccess=='yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access=='yes')) { ?>
    <tr class="dark">
        <td>
            <label>Monthly Maintenance Done</label>
        </td>
        <td>
            <input type="radio" id="qcDoneYes" name="qcDone" value="yes"
                <?php echo ($this->shipment['qc_done']=="yes") ? " checked='checked' " : ""; ?> onclick="checkQcStatus();" />
            <strong>Yes</strong>&nbsp;&nbsp;
            <input type="radio" id="qcDoneNo" name="qcDone" value="no" title="Please select monthly maintenance done status"
                   onclick="checkQcStatus();" <?php echo ($this->shipment['qc_done']== null || $this->shipment['qc_done']=="" || $this->shipment['qc_done']=="no") ? " checked='checked' " : ""; ?> />
            <strong>No</strong>
        </td>
        <td colspan="2"></td>
    </tr>
        <?php
        $display = "display:none";
        $isRequired = "";
        if (isset($this->shipment['qc_done']) && $this->shipment['qc_done'] == "yes") {
            $display = "";
            $isRequired = "required";
        } ?>
    <tr id="qcSection" class="light" style="<?php echo $display; ?>">
        <td style="white-space: nowrap;">
            <label>Maintenance Date</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;"
                   value="<?php echo $this->dateFormat($this->shipment["qc_date"]); ?>"
                   class="form-control datepicker<?php echo $isRequired ? ' isRequired' : ''; ?>" readonly="readonly"
                   title="Please enter Maintenance Date" />&nbsp;
            <i class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('qcDate')"> Clear</i>
        </td>
        <td style="white-space: nowrap;">
            <label>Maintenance Done By</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <input type="text" id="qcDoneBy" name="qcDoneBy" title="Please enter who performed maintenance"
                   class="form-control<?php echo $isRequired ? ' isRequired' : ''; ?>"
                   value="<?php echo $this->shipment["qc_done_by"]; ?>" />
        </td>
    </tr>
    <?php
	} ?>
</table>
<hr />
<div>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;" cellpadding="0">
    <?php
    $count =0;
    foreach ($this->allSamples as $sample) {
        $count++;
        $errorCodeEnabled = $sample['res_mtb_detected'] == "error";
        $rifResistanceEnabled = in_array($sample['res_mtb_detected'], array("high", "medium", "low", "veryLow")); ?>
        <tr>
            <td style="padding: 0;">
                <table class="table" style="width: 100%;background-color: transparent;">
                    <tr>
                        <th colspan="11" style="white-space: nowrap;background-color: transparent;">
                            <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                            <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[]"
                                   value="<?php echo $sample['sample_id'];?>" />
                        </th>
                    </tr>
                    <tr>
                        <th rowspan="2" style="vertical-align: middle;">Result Details</th>
                        <th style="vertical-align: bottom;">Date Tested</th>
                        <th style="vertical-align: bottom;">MTB Detected</th>
                        <th class="errorCode" style="vertical-align: bottom;">Error Code</th>
                        <th style="vertical-align: bottom;">Rif Resistance</th>
                        <th style="vertical-align: bottom;">Probe D</th>
                        <th style="vertical-align: bottom;">Probe C</th>
                        <th style="vertical-align: bottom;">Probe E</th>
                        <th style="vertical-align: bottom;">Probe B</th>
                        <th style="vertical-align: bottom;">SPC</th>
                        <th style="vertical-align: bottom;">Probe A</th>
                    </tr>
                    <tr style="background-color: transparent;">
                        <td style="background-color: transparent;">
                            <input type="text" class="form-control datepicker input-sm sampleTestDate" readonly="readonly"
                                   name="dateTested[]" value="<?php echo $this->dateFormat($sample['res_date_tested']); ?>"
                                   title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <select id="mtbDetected<?php echo $count; ?>" name="mtbDetected[]"
                                    class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample"
                                    placeholder="Please enter the MTB Detected for this sample"
                                    onChange="changeMtbDetected(<?php echo $count; ?>)">
                                <option value="">-- Select --</option>
                                <option value="high" <?php echo ($sample['res_mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>
                                    High
                                </option>
                                <option value="medium" <?php echo ($sample['res_mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>
                                    Medium
                                </option>
                                <option value="low" <?php echo ($sample['res_mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>
                                    Low
                                </option>
                                <option value="veryLow" <?php echo ($sample['res_mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>
                                    Very Low
                                </option>
                                <option value="notDetected" <?php echo ($sample['res_mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                    Not Detected
                                </option>
                                <option value="noResult" <?php echo ($sample['res_mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>
                                    No Result
                                </option>
                                <option value="invalid" <?php echo ($sample['res_mtb_detected'] == 'invalid' ? "selected='selected'" : ""); ?>>
                                    Invalid
                                </option>
                                <option value="error" <?php echo ($sample['res_mtb_detected'] == 'error' ? "selected='selected'" : ""); ?>>
                                    Error
                                </option>
                            </select>
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" id="errorCode<?php echo $count; ?>" name="errorCode[]"
                                   class="form-control input-sm errorCode" value="<?php echo $sample['res_error_code']; ?>"
                                   title="Please enter the Error Code for <?php echo $sample['sample_label']; ?>" <?php if (!$errorCodeEnabled) { echo "readonly"; } ?> />
                        </td>
                        <td style="background-color: transparent;">
                            <select id="rifResistance<?php echo $count; ?>" name="rifResistance[]"
                                    class="isRequired form-control input-sm"
                                    title="Please enter the Rif Resistance for this sample"
                                    placeholder="Please enter the Rif Resistance for this sample" <?php if (!$rifResistanceEnabled) { echo "readonly"; } ?>>
                                <option value="">
                                    -- Select --
                                </option>
                                <option value="detected" <?php echo ($sample['res_rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>
                                    Detected
                                </option>
                                <option value="notDetected" <?php echo ($sample['res_rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                    Not Detected
                                </option>
                                <option value="indeterminate" <?php echo ($sample['res_rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>
                                    RIF Indeterminate
                                </option>
                                <option value="na" <?php echo ($sample['res_rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>
                                    N/A
                                </option>
                            </select>
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probeD[]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_d']; ?>"
                                   title="Please enter the Probe D value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probeC[]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_c']; ?>"
                                   title="Please enter the Probe C value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probeE[]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_e']; ?>"
                                   title="Please enter the Probe E value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probeB[]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_b']; ?>"
                                   title="Please enter the Probe B value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="spc[]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_spc']; ?>" title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probeA[]" class="form-control input-sm oneDecimal numberInput" value="<?php echo $sample['res_probe_a']; ?>"
                                   title="Please enter the Probe A value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                    </tr>
                    <tr>
                        <th rowspan="2" style="vertical-align: middle;">Instrument/Cartridge Details</th>
                        <th colspan="3" style="vertical-align: bottom;">Serial Number</th>
                        <th colspan="2" style="vertical-align: bottom;">Installed</th>
                        <th colspan="2" style="vertical-align: bottom;">Last Calibrated</th>
                        <th style="vertical-align: bottom;">Module Number</th>
                        <th colspan="2" style="vertical-align: bottom;">Instrument User</th>
                    </tr>
                    <tr style="background-color: transparent;">
                        <th colspan="3" style="white-space: nowrap;background-color: transparent;">
                            <input type="text" id="instrumentSerial<?php echo $count; ?>" name="instrumentSerial[]"
                                   class="form-control input-sm" value="<?php echo $sample['res_instrument_serial']; ?>"
                                   title="Please enter the instrument serial number for <?php echo $sample['sample_label']; ?>"
                                   style="display: <?php if (!isset($this->instruments) || count($this->instruments) == 0) { echo "block"; } else { echo "none"; }?>;" />
                            <?php
                            if (isset($this->instruments) && count($this->instruments) > 0) { ?>
                            <div id="instrumentDropDown<?php echo $count; ?>" class="btn-group" style="display: block; border: solid 1px #ccc; width: 100%; height: 2.13em;">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" style="width: 100%; padding-top: 3px;">
                                    <span class="dropdownText">
                                        <?php echo (isset($sample['res_instrument_serial']) && $sample['res_instrument_serial'] != "" ? $sample['res_instrument_serial'] : "-- Select --") ?>
                                    </span>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <?php
                                    foreach ($this->instruments as $id => $instrument_details) { ?>
                                    <li>
                                        <a href="" onClick="return changeInstrument({serial: '<?php echo $instrument_details["instrument_serial"]; ?>', installedOn: '<?php echo $this->dateFormat($instrument_details["instrument_installed_on"]); ?>', lastCalibratedOn: '<?php echo $this->dateFormat($instrument_details["instrument_last_calibrated_on"]); ?>', dropDownId: 'instrumentDropDown<?php echo $count; ?>', serialTextFieldId: 'instrumentSerial<?php echo $count; ?>', installedOnTextFieldId: 'instrumentInstalledOn<?php echo $count; ?>', lastCalibratedOnTextFieldId: 'instrumentLastCalibratedOn<?php echo $count; ?>'})">
                                            <?php echo $instrument_details['instrument_serial']; ?>
                                        </a>
                                    </li>
                                    <?php
                                    } ?>
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <a href=""
                                           onClick="return newInstrument({dropDownId: 'instrumentDropDown<?php echo $count; ?>', serialTextFieldId: 'instrumentSerial<?php echo $count; ?>', installedOnTextFieldId: 'instrumentInstalledOn<?php echo $count; ?>', lastCalibratedOnTextFieldId: 'instrumentLastCalibratedOn<?php echo $count; ?>'})">
                                            New Instrument
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <?php
                            } ?>
                        </th>
                        <td colspan="2" style="background-color: transparent;">
                            <input type="text" id="instrumentInstalledOn<?php echo $count; ?>"
                                   class="form-control datepicker input-sm" readonly="readonly" name="instrumentInstalledOn[]"
                                   value="<?php echo $this->dateFormat($sample['res_instrument_installed_on']); ?>"
                                   title="Please enter the instrument installation date for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td colspan="2" style="background-color: transparent;">
                            <input type="text" id="instrumentLastCalibratedOn<?php echo $count; ?>"
                                   class="form-control datepicker input-sm" readonly="readonly" name="instrumentLastCalibratedOn[]"
                                   value="<?php echo $this->dateFormat($sample['res_instrument_last_calibrated_on']); ?>"
                                   title="Please enter the date that the instrument was last calibrated for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <th style="white-space: nowrap;background-color: transparent;">
                            <input type="text" name="moduleName[]" class="form-control input-sm"
                                   value="<?php echo $sample['res_module_name']; ?>"
                                   title="Please enter the module number for <?php echo $sample['sample_label']; ?>" />
                        </th>
                        <th colspan="2" style="white-space: nowrap;background-color: transparent;">
                            <input type="text" name="instrumentUser[]" class="form-control input-sm"
                                   value="<?php echo $sample['res_instrument_user']; ?>"
                                   title="Please enter the instrument user for <?php echo $sample['sample_label']; ?>" />
                        </th>
                    </tr>
                </table>
            </td>
        </tr>
    <?php
    } ?>
    </table>
</div>
<br />
<hr />
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
    <tr>
        <th style="width:20%;">Supervisor Review</th>
        <td style="width:20%;">
            <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                <option value="">--Select--</option>
                <option value="yes" <?php if($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                <option value="no" <?php if($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
            </select>
        </td>
        <th>
            <label <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>
                   id ="labSupervisor" style="white-space: nowrap;">
                Supervisor Name
                <span class='mandatory'>*</span>
            </label>
        </th>
        <td>
            <input name="participantSupervisor" id="participantSupervisor" type="text" class="form-control"
                   value="<?php echo $this->shipment['participant_supervisor'] ; ?>" <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> />
        </td>
    </tr>
    <tr>
        <th>Comments </th>
        <td colspan="3">
            <textarea name="userComments" id="userComments" class="form-control">
                <?php echo $this->shipment['user_comment'] ; ?>
            </textarea>
        </td>
    </tr>
</table>
<?php if ($this->isEditable) { ?>
<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
    <p>
        <input type="hidden" id="submitAction" />
        <input name="savebtn" class="btn btn-primary" type="submit" value="Save" onclick="javascript:save_form()" />
        &nbsp;&nbsp;&nbsp;
        <input name="submitbtn" class="btn btn-success" type="submit" value="Submit" onclick="javascript:submit_form()" />
        &nbsp;&nbsp;&nbsp;
        <input name="cancel" class="btn btn-danger" type="button" id="reset" value="Cancel" onclick="javascript:goto_dashboard()" />
    </p>
</div>
<?php } ?>
</div>
<?php 
$genderHelper = $this->getHelper('DateFormat');
$dtFormat = $genderHelper->getDateFormat();
?>
</div>
</form>
<?php if (!$this->isEditable) { ?>
<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
    <input name="cancel" class="btn btn-info" type="button" id="reset" value="Back" onclick="javascript:goto_dashboard()" />
</div>
<?php } ?>
</div>
</section>
<script>
  function goto_dashboard() {
    window.history.back();
  }

  function save_form() {
    $('#submitAction').val('save');
  }

  function submit_form() {
    $('#submitAction').val('submit');
  }

  var timeOut;

  $(function() {
    $(".datepicker:not(#expiryDate, input[name='instrumentLastCalibratedOn[]'], input[name='instrumentInstalledOn[]'])")
      .datepicker({
        dateFormat: '<?php echo $dtFormat;?>',
        maxDate: '0',
        minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')
      });

    $("#expiryDate")
      .datepicker({
        dateFormat: '<?php echo $dtFormat;?>',
        minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')
      });

    $("input[name='instrumentLastCalibratedOn[]'], input[name='instrumentInstalledOn[]']")
      .datepicker({ dateFormat: '<?php echo $dtFormat;?>' });

    <?php if (!$this->isEditable) { ?>
    $("#tbResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
	<?php } ?>
  });

  $('.oneDecimal, .zeroDecimal').keypress(function () {
    var $this = $(this);
	$this.val($this.val().replace(/[^\d.]/g, ''));
  });

  $('.sampleTestDate').change(function () {
    $('.sampleTestDate').each(function() { });
  });

  $(".oneDecimal").on("blur", function(el) {
    clearTimeout(timeOut);
	timeOut = setTimeout(function() {
	  var newVal = Number($(el.target).val()).toFixed(1);
	  if ($.isNumeric(newVal)) {
	    $(el.target).val(newVal);
	  } else {
	    $(el.target).val(0);
	  }
	}, 600);
  });

  $(".zeroDecimal").on("blur", function(el) {
    clearTimeout(timeOut);
    timeOut = setTimeout(function() {
      var newVal = Number($(el.target).val()).toFixed(0);
      if ($.isNumeric(newVal)) {
        $(el.target).val(newVal);
      } else {
        $(el.target).val(0);
      }
    },600);
  });

  function validateNow() {
    if ($('#submitAction').val() === 'submit') {
      var validationMessage = '';
      if (!$("#receiptDate").val()) {
        validationMessage += '\n- Please ensure Shipment Receipt Date has been entered';
      }

      if (!$("#expiryDate").val()) {
        validationMessage += '\n- Please ensure Expiration date of MTB/RIF Kit has been entered';
      }

      if (!$("#testReceiptDate").val()) {
        validationMessage += '\n- Please ensure Response Date has been entered';
      }

      if (!$("#mtbRifKitLotNo").val()) {
        validationMessage += '\n- Please ensure MTB/RIF Kit Lot No has been entered';
      }

      if (!$("#assay").val()) {
        validationMessage += '\n- Please ensure Assay has been specified';
      }

      if ($('#qcDoneYes').is(':checked')) {
        if (!$("#qcDate").val()) {
          validationMessage += '\n- Please ensure Maintenance Date has been entered';
        }

        if (!$("#qcDoneBy").val()) {
          validationMessage += '\n- Please ensure Maintenance Done By has been entered';
        }
      }

      if($('#supervisorApproval').val() === 'yes' && !$("#participantSupervisor").val()) {
        validationMessage += '\n- Please ensure Supervisor Name has been entered';
      }

      var dateTestedValidationCaught = false;
      $('[name="dateTested[]"]').each(function() {
        if (!dateTestedValidationCaught) {
          if (!$(this).val()) {
            validationMessage += '\n- Please ensure Date Tested has been specified for each sample';
            dateTestedValidationCaught = true;
          } else if ($("#receiptDate").val() &&
            moment($(this).val()).diff(new Date($("#receiptDate").val())) < 0) {
            validationMessage += '\n- Testing Date for each sample has to come after the Shipment Receipt Date';
            dateTestedValidationCaught = true;
          }
        }
      });

      var mtbDetectedValidationCaught = false;
      var mtbDetectedIndex = 0;
      var rifResistanceValidationCaught = false;
      var errorCodeValidationCaught = false;
      $('[name="mtbDetected[]"]').each(function() {
        if (!mtbDetectedValidationCaught) {
          if (!$(this).val()) {
            validationMessage += '\n- Please ensure MTB Detected has been specified for each sample';
            mtbDetectedValidationCaught = true;
          }
        }
        if (!rifResistanceValidationCaught) {
          if (['high', 'medium', 'low', 'veryLow'].includes($(this).val()) &&
            !['detected', 'notDetected'].includes($('[name="rifResistance[]"]').eq(mtbDetectedIndex).val())) {
            validationMessage += '\n- If MTB was detected in a sample, please specify whether Rif Resistance was detected';
            rifResistanceValidationCaught = true;
          } else if (!['high', 'medium', 'low', 'veryLow', 'error'].includes($(this).val()) &&
            $('[name="rifResistance[]"]').eq(mtbDetectedIndex).val() !== 'na') {
            validationMessage += '\n- If there was no result or an invalid result for a sample, Rif Resistance should be N/A';
            rifResistanceValidationCaught = true;
          }
        }
        if (!errorCodeValidationCaught && $(this).val() === 'error' &&
          !$('[name="errorCode[]"]').eq(mtbDetectedIndex).val()) {
          validationMessage += '\n- If the result was an error, please specify what the error code was';
          errorCodeValidationCaught = true;
        }
        mtbDetectedIndex++;
      });

      var probeValueValidationCaught = false;
      $('[name="probeD[]"],[name="probeC[]"],[name="probeE[]"],[name="probeB[]"],[name="spc[]"],[name="probeA[]"]')
        .each(function() {
          if (!probeValueValidationCaught) {
            if (!$(this).val()) {
              validationMessage += '\n- Please ensure all SPC and Probe values have been specified for each sample';
              probeValueValidationCaught = true;
            } else if (!$.isNumeric($(this).val())) {
              validationMessage += '\n- Please ensure all SPC and Probe values are valid numbers';
              probeValueValidationCaught = true;
            }
          }
        });

      if (validationMessage) {
        alert('Validation Check' + validationMessage);
        return false;
      }

      return deforayValidator.init({
        formId: 'tbResponseForm'
      });
    }
    return true;
  }

  $('#supervisorApproval').change(function() {
    if ($('#supervisorApproval').val() == 'yes') {
      $('#labSupervisor').show();
      $('#participantSupervisor').val('');
      $('#participantSupervisor').show();
    } else {
      $('#labSupervisor').hide();
      $('#participantSupervisor').val('');
      $('#participantSupervisor').hide();
    }
  });

  function clearDate(id) {
    $("#" + id).val('');
  }

  function checkQcStatus(){
    var radioValue = $("input[name='qcDone']:checked"). val();
    if (radioValue == "yes") {
      $("#qcSection").show();
      $("#qcDate").addClass("isRequired");
      $("#qcDoneBy").addClass("isRequired");
    } else {
      $("#qcSection").hide();
      $("#qcDate").val("");
      $("#qcDoneBy").val("");
      $("#qcDate").removeClass("isRequired");
      $("#qcDoneBy").removeClass("isRequired");
    }
  }

  function changeInstrument(details) {
    $("#" + details.serialTextFieldId).val(details.serial);
    $("#" + details.installedOnTextFieldId).val(details.installedOn);
    $("#" + details.lastCalibratedOnTextFieldId).val(details.lastCalibratedOn);
    $("#" + details.dropDownId + " a span.dropdownText").text(details.serial);
    return false;
  }

  function newInstrument(details) {
    $("#" + details.serialTextFieldId).val('');
    $("#" + details.installedOnTextFieldId).val('');
    $("#" + details.lastCalibratedOnTextFieldId).val('');
    $("#" + details.dropDownId).css('display', 'none');
    $("#" + details.serialTextFieldId).css('display', 'block');
    $("#" + details.serialTextFieldId).focus();
    return false;
  }

  function changeMtbDetected(resultNumber) {
    var mtbDetected = $("#mtbDetected" + resultNumber).val();
    var errorCodeInput = $("#errorCode" + resultNumber);
    var rifResistanceSelect = $("#rifResistance" + resultNumber);
    if (mtbDetected === "error") {
      errorCodeInput.removeAttr("readonly");
    } else {
      errorCodeInput.attr("readonly", "");
      errorCodeInput.val('')
    }
    if (["high", "medium", "low", "veryLow"].includes(mtbDetected)) {
      rifResistanceSelect.removeAttr("readonly");
    } else {
      rifResistanceSelect.attr("readonly", "");
      rifResistanceSelect.val('na')
    }
  }
</script>
