<?php
$authNameSpace = new Zend_Session_Namespace('datamanagers');
if (isset($this->shipment["shipment_test_report_date"]) &&
        trim($this->shipment["shipment_test_report_date"]) != "") {
    $expTestReceiptDate = explode(" ",$this->shipment["shipment_test_report_date"]);
    $testReceiptDate = $this->dateFormat($expTestReceiptDate[0]);
} else {
	$testReceiptDate = date('d-M-Y');
} ?>
<style>
    th {
        text-align: center;
    }
	table,th,td {
		border-color: #ccc !important;
	}
	.hideOtherAssay {
		display: none;
	}

    div.error {
        color: #ff0000;
        float: left;
    }

    input.error, select.error {
        border: solid 1px #ff0000;
    }
</style>
<section class="content-header">
    <h1><?php echo $this->shipment['scheme_name'];?></h1>
</section>
<section class="content">
<div class="box">
<form name="tbResponseForm" id="tbResponseForm" method="post"
      action="<?php echo $this->url(array("controller"=>"tb","action"=>"response"),null,true) ?>"
      onsubmit="return validateNow();return false;">
<div class="box-body">
<input type="hidden" id ="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response'];?>" />
<input type="hidden" id ="smid" name="smid" value="<?php echo $this->shipment['map_id'];?>" />
<input type="hidden" id ="shipmentId" name="shipmentId" value="<?php echo $this->shipId;?>" />
<input type="hidden" id ="participantId" name="participantId" value="<?php echo $this->participantId;?>" />
<input type="hidden" id ="evId" name="evId" value="<?php echo $this->eID;?>" />
<?php $count =0;  
foreach ($this->allSamples as $sample) {
    $count++;  ?>
<input type="hidden" id ="<?php echo $count . "_hdSampleId"; ?>" name="<?php echo $count . "_hdSampleId"; ?>"
       value="<?php echo $sample['sample_id'];?>" />
<?php
} ?>
<div id="view-content">
<br />
<div id=error></div>
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
    <tr>
        <td style="width:20%;">
            <h4 class="text-info"> Participant Name </h4>&nbsp;
            <?php echo ( $this->participant['first_name'] . ' ' . $this->participant['last_name'] );?>
        </td>
        <td style="width:20%;">
            <h4 class="text-info"> Participant Code </h4>&nbsp;
            <?php echo $this->participant['unique_identifier'] ?>
        </td>
        <td style="width:20%;">
            <h4 class="text-info"> Affiliation </h4>&nbsp;
            <?php echo ( $this->participant['affiliation'] );?>
        </td>
        <td style="width:20%;">
            <h4 class="text-info"> Phone No </h4>&nbsp;
            <?php  echo ( $this->participant['mobile']  . '<br/>' .   $this->participant['phone'] ); ?>
        </td>
    </tr>
</table>
<hr />
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
	<tr class="dark">
		<td style="width:20%;">
            <label>Shipment Date</label>
        </td>
		<td style="width:30%;">
            <?php echo $this->dateFormat($this->shipment['shipment_date']) ?>
        </td>
		<td style="width:20%;">
            <label>Result Due Date</label>
        </td>
		<td style="width:30%;">
            <?php echo $this->dateFormat($this->shipment['lastdate_response']);?>
        </td>
	</tr>
	<tr class ="light">
		<td style="width:20%; white-space: nowrap;">
            <label>Shipment Receipt Date</label>
            <span class='mandatory'>*</span>
        </td>
		<td style="width:30%;">
			<input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;"
                   value="<?php  echo $this->dateFormat($this->shipment["shipment_receipt_date"]);  ?>"
                   class="form-control isRequired datepicker" readonly />&nbsp;
			<i id="clearReceiptDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('receiptDate')"> Clear</i>
		</td>
        <td style="white-space: nowrap;">
            <label>Assay</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <select class="form-control" name="assay" id="assay" class="form-control"
                    title="Please choose the assay type">
                <?php
                foreach ($this->assays as $id => $name) { ?>
                    <option value="<?php echo $id; ?>"
                        <?php if (isset($this->shipment['attributes']['assay'])) { echo ($this->shipment['attributes']['assay'] == $id) ? "selected='selected'" : ""; } ?>>
                        <?php echo $name; ?>
                    </option>
                    <?php
                } ?>
            </select>
        </td>
	</tr>
    <tr class ="dark">
		<td style="white-space: nowrap;">
            <label>MTB/RIF Kit Lot No</label>
            <span class='mandatory'>*</span>
        </td>
		<td>
		    <input type="text" name="mtbRifKitLotNo" id="mtbRifKitLotNo" class="form-control isRequired"
                   value="<?php echo $this->shipment['attributes']['mtb_rif_kit_lot_no'];?>"/>
		</td>
		<td style="width:20%; white-space: nowrap;">
            <label>Expiration date of MTB/RIF Kit</label>
            <span class='mandatory'>*</span>
        </td>
		<td style="width:30%;">
			<input type="text" name="expiryDate" id="expiryDate" class="form-control isRequired datepicker"
                   size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date'];?>"
                   readonly="readonly"/>&nbsp;
			<i id="clearExpiryDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('expiryDate')"> Clear</i>
		</td>
	</tr>
    <tr class="light">
        <td style="white-space: nowrap;">
            <label>Response Date</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11"
                   style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker"
                   readonly="readonly" title="Please enter Shipment Test Response Date " />&nbsp;
            <i id="clearTestReceiptDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('testReceiptDate')"> Clear</i>
        </td>
        <td colspan="2"></td>
    </tr>
    <tr class="dark">
        <td>
            <label>How many Xpert MTB/RIF tests have been conducted by this site in the last full month?</label>
        </td>
        <td>
            <input type="text" name="countTestsConductedOverMonth" id="countTestsConductedOverMonth"
                   class="form-control zeroDecimal numberInput"
                   value="<?php if(isset($this->shipment['attributes']['count_tests_conducted_over_month'])) { echo $this->shipment['attributes']['count_tests_conducted_over_month']; }?>" />
        </td>
        <td>
            <label>How many errors occurred during testing in the last full month?</label>
        </td>
        <td>
            <input type="text" name="countErrorsEncounteredOverMonth" id="countErrorsEncounteredOverMonth"
                   class="form-control zeroDecimal numberInput"
                   value="<?php if(isset($this->shipment['attributes']['count_errors_encountered_over_month'])) { echo $this->shipment['attributes']['count_errors_encountered_over_month']; }?>" />
        </td>
    </tr>
    <tr class="light">
        <td>
            <label>What were the error codes?</label>
        </td>
        <td colspan="3">
            <input type="text" name="errorCodesEncounteredOverMonth" id="errorCodesEncounteredOverMonth" class="form-control"
                   value="<?php if(isset($this->shipment['attributes']['error_codes_encountered_over_month'])) { echo $this->shipment['attributes']['error_codes_encountered_over_month']; }?>" />
        </td>
    </tr>
    <?php
	if ($this->globalQcAccess=='yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access=='yes')) { ?>
    <tr class="dark">
        <td>
            <label>Monthly Maintenance Done</label>
        </td>
        <td>
            <input type="radio" id="qcDoneYes" name="qcDone" value="yes"
                <?php echo ($this->shipment['qc_done']=="yes") ? " checked='checked' " : ""; ?> onclick="checkQcStatus();" />
            <strong>Yes</strong>&nbsp;&nbsp;
            <input type="radio" id="qcDoneNo" name="qcDone" value="no" title="Please select monthly maintenance done status"
                   onclick="checkQcStatus();" <?php echo ($this->shipment['qc_done']== null || $this->shipment['qc_done']=="" || $this->shipment['qc_done']=="no") ? " checked='checked' " : ""; ?> />
            <strong>No</strong>
        </td>
        <td colspan="2"></td>
    </tr>
        <?php
        $display = "display:none";
        $isRequired = "";
        if (isset($this->shipment['qc_done']) && $this->shipment['qc_done'] == "yes") {
            $display = "";
            $isRequired = "required";
        } ?>
    <tr id="qcSection" class="light" style="<?php echo $display; ?>">
        <td style="white-space: nowrap;">
            <label>Maintenance Date</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;"
                   value="<?php echo $this->dateFormat($this->shipment["qc_date"]); ?>"
                   class="form-control datepicker<?php echo $isRequired ? ' isRequired' : ''; ?>" readonly="readonly"
                   title="Please enter Maintenance Date" />&nbsp;
            <i id="clearQcDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('qcDate')"> Clear</i>
        </td>
        <td style="white-space: nowrap;">
            <label>Maintenance Done By</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <input type="text" id="qcDoneBy" name="qcDoneBy" title="Please enter who performed maintenance"
                   class="form-control<?php echo $isRequired ? ' isRequired' : ''; ?>"
                   value="<?php echo $this->shipment["qc_done_by"]; ?>" />
        </td>
    </tr>
    <?php
	} ?>
</table>
<hr />
<div>
    <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;" cellpadding="0">
    <?php
    $count = 0;
    $index = 0;
    foreach ($this->allSamples as $sample) {
        $count++;
        $errorCodeEnabled = $sample['res_mtb_detected'] == "error";
        $rifResistanceEnabled = in_array($sample['res_mtb_detected'], array("detected", "high", "medium", "low", "veryLow")); ?>
        <tr>
            <td style="padding: 0;">
                <table class="table" style="width: 100%;background-color: transparent;">
                    <tr>
                        <th colspan="11" style="white-space: nowrap;background-color: transparent;">
                            <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                            <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[<?php echo $index; ?>]"
                                   value="<?php echo $sample['sample_id'];?>" />
                        </th>
                    </tr>
                    <tr>
                        <th rowspan="2" style="vertical-align: middle; width:14%;">Result Details</th>
                        <th style="vertical-align: bottom; width:14%;">Date Tested</th>
                        <th style="vertical-align: bottom; width:14%;">MTB Detected</th>
                        <th class="errorCode" style="vertical-align: bottom; width:9%;">Error Code</th>
                        <th style="vertical-align: bottom; width:13%;">Rif Resistance</th>
                        <th style="vertical-align: bottom; width:6%;">Probe D</th>
                        <th style="vertical-align: bottom; width:6%;">Probe C</th>
                        <th style="vertical-align: bottom; width:6%;">Probe E</th>
                        <th style="vertical-align: bottom; width:6%;">Probe B</th>
                        <th style="vertical-align: bottom; width:6%;">SPC</th>
                        <th style="vertical-align: bottom; width:6%;">Probe A</th>
                    </tr>
                    <tr style="background-color: transparent;">
                        <td style="background-color: transparent;">
                            <input type="text" id="sampleTestDate<?php echo $count; ?>"
                                   class="form-control datepicker input-sm sampleTestDate"
                                   readonly name="dateTested[<?php echo $index; ?>]"
                                   value="<?php echo $this->dateFormat($sample['res_date_tested']); ?>"
                                   title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <select id="mtbDetected<?php echo $count; ?>" name="mtbDetected[<?php echo $index; ?>]"
                                    class="isRequired form-control input-sm" title="Please enter the MTB Detected for this sample"
                                    placeholder="Please enter the MTB Detected for this sample"
                                    onChange="changeMtbDetected(<?php echo $count; ?>)">
                                <option value="">-- Select --</option>
                                <option value="detected" <?php echo ($sample['res_mtb_detected'] == 'detected' ? "selected='selected'" : ""); ?>>
                                    Detected
                                </option>
                                <option value="high" <?php echo ($sample['res_mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>
                                    High
                                </option>
                                <option value="medium" <?php echo ($sample['res_mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>
                                    Medium
                                </option>
                                <option value="low" <?php echo ($sample['res_mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>
                                    Low
                                </option>
                                <option value="veryLow" <?php echo ($sample['res_mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>
                                    Very Low
                                </option>
                                <option value="notDetected" <?php echo ($sample['res_mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                    Not Detected
                                </option>
                                <option value="noResult" <?php echo ($sample['res_mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>
                                    No Result
                                </option>
                                <option value="invalid" <?php echo ($sample['res_mtb_detected'] == 'invalid' ? "selected='selected'" : ""); ?>>
                                    Invalid
                                </option>
                                <option value="error" <?php echo ($sample['res_mtb_detected'] == 'error' ? "selected='selected'" : ""); ?>>
                                    Error
                                </option>
                            </select>
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" id="errorCode<?php echo $count; ?>" name="errorCode[<?php echo $index; ?>]"
                                   class="form-control input-sm errorCode" value="<?php echo $sample['res_error_code']; ?>"
                                   title="Please enter the Error Code for <?php echo $sample['sample_label']; ?>" <?php if (!$errorCodeEnabled) { echo "readonly"; } ?> />
                        </td>
                        <td style="background-color: transparent;">
                            <select id="rifResistance<?php echo $count; ?>" name="rifResistance[<?php echo $index; ?>]"
                                    class="isRequired form-control input-sm"
                                    title="Please enter the Rif Resistance for this sample"
                                    placeholder="Please enter the Rif Resistance for this sample" <?php if (!$rifResistanceEnabled) { echo "readonly"; } ?>>
                                <option value="">
                                    -- Select --
                                </option>
                                <option value="detected" <?php echo ($sample['res_rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>
                                    Detected
                                </option>
                                <option value="notDetected" <?php echo ($sample['res_rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                    Not Detected
                                </option>
                                <option value="indeterminate" <?php echo ($sample['res_rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>
                                    RIF Indeterminate
                                </option>
                                <option value="na" <?php echo ($sample['res_rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>
                                    N/A
                                </option>
                            </select>
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probeD[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_d']; ?>" id="probeD<?php echo $count; ?>"
                                   title="Please enter the Probe D value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probeC[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_c']; ?>" id="probeC<?php echo $count; ?>"
                                   title="Please enter the Probe C value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probeE[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_e']; ?>" id="probeE<?php echo $count; ?>"
                                   title="Please enter the Probe E value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probeB[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_b']; ?>" id="probeB<?php echo $count; ?>"
                                   title="Please enter the Probe B value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="spc[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_spc']; ?>" id="spc<?php echo $count; ?>"
                                   title="Please enter the SPC value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probeA[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_a']; ?>" id="probeA<?php echo $count; ?>"
                                   title="Please enter the Probe A value for <?php echo $sample['sample_label']; ?>" />
                        </td>
                    </tr>
                    <tr>
                        <th rowspan="2" style="vertical-align: middle;">Instrument/Cartridge Details</th>
                        <th style="vertical-align: bottom;">Serial Number</th>
                        <th style="vertical-align: bottom;">Installed</th>
                        <th style="vertical-align: bottom;"></th>
                        <th style="vertical-align: bottom;">Last Calibrated</th>
                        <th colspan="2" style="vertical-align: bottom;">Module Number</th>
                        <th colspan="4" style="vertical-align: bottom;">Instrument User</th>
                    </tr>
                    <tr style="background-color: transparent;">
                        <th style="white-space: nowrap;background-color: transparent;">
                            <input type="text" id="instrumentSerial<?php echo $count; ?>" name="instrumentSerial[<?php echo $index; ?>]"
                                   class="form-control input-sm" value="<?php echo $sample['res_instrument_serial']; ?>"
                                   title="Please enter the instrument serial number for <?php echo $sample['sample_label']; ?>"
                                   style="display: <?php if (!isset($this->instruments) || count($this->instruments) == 0) { echo "block"; } else { echo "none"; }?>;" />
                            <?php
                            if (isset($this->instruments) && count($this->instruments) > 0) { ?>
                            <div id="instrumentDropDown<?php echo $count; ?>" class="btn-group" style="display: block; border: solid 1px #ccc; width: 100%; height: 2.13em;">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" style="width: 100%; padding-top: 3px;">
                                    <span class="dropdownText">
                                        <?php echo (isset($sample['res_instrument_serial']) && $sample['res_instrument_serial'] != "" ? $sample['res_instrument_serial'] : "-- Select --") ?>
                                    </span>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <?php
                                    foreach ($this->instruments as $id => $instrument_details) { ?>
                                    <li>
                                        <a href="" onClick="return changeInstrument({serial: '<?php echo $instrument_details["instrument_serial"]; ?>', installedOn: '<?php echo $this->dateFormat($instrument_details["instrument_installed_on"]); ?>', lastCalibratedOn: '<?php echo $this->dateFormat($instrument_details["instrument_last_calibrated_on"]); ?>', dropDownId: 'instrumentDropDown<?php echo $count; ?>', serialTextFieldId: 'instrumentSerial<?php echo $count; ?>', installedOnTextFieldId: 'instrumentInstalledOn<?php echo $count; ?>', lastCalibratedOnTextFieldId: 'instrumentLastCalibratedOn<?php echo $count; ?>'})">
                                            <?php echo $instrument_details['instrument_serial']; ?>
                                        </a>
                                    </li>
                                    <?php
                                    } ?>
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <a href=""
                                           onClick="return newInstrument({dropDownId: 'instrumentDropDown<?php echo $count; ?>', serialTextFieldId: 'instrumentSerial<?php echo $count; ?>', installedOnTextFieldId: 'instrumentInstalledOn<?php echo $count; ?>', lastCalibratedOnTextFieldId: 'instrumentLastCalibratedOn<?php echo $count; ?>'})">
                                            New Instrument
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <?php
                            } ?>
                        </th>
                        <td style="background-color: transparent;">
                            <input type="text" id="instrumentInstalledOn<?php echo $count; ?>"
                                   class="form-control datepicker input-sm" readonly="readonly"
                                   name="instrumentInstalledOn[<?php echo $index; ?>]"
                                   value="<?php echo $this->dateFormat($sample['res_instrument_installed_on']); ?>"
                                   title="Please enter the instrument installation date for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td></td>
                        <td style="background-color: transparent;">
                            <input type="text" id="instrumentLastCalibratedOn<?php echo $count; ?>"
                                   class="form-control datepicker input-sm" readonly="readonly"
                                   name="instrumentLastCalibratedOn[<?php echo $index; ?>]"
                                   value="<?php echo $this->dateFormat($sample['res_instrument_last_calibrated_on']); ?>"
                                   title="Please enter the date that the instrument was last calibrated for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <th colspan="2" style="white-space: nowrap;background-color: transparent;">
                            <input type="text" name="moduleName[<?php echo $index; ?>]"
                                   class="form-control input-sm" value="<?php echo $sample['res_module_name']; ?>"
                                   title="Please enter the module number for <?php echo $sample['sample_label']; ?>" />
                        </th>
                        <th colspan="4" style="white-space: nowrap;background-color: transparent;">
                            <input type="text" name="instrumentUser[<?php echo $index; ?>]"
                                   class="form-control input-sm" value="<?php echo $sample['res_instrument_user']; ?>"
                                   title="Please enter the instrument user for <?php echo $sample['sample_label']; ?>" />
                        </th>
                    </tr>
                </table>
            </td>
        </tr>
    <?php
        $index++;
    } ?>
    </table>
</div>
<br />
<hr />
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
    <tr>
        <th style="width:20%;">Supervisor Review</th>
        <td style="width:20%;">
            <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                <option value="">--Select--</option>
                <option value="yes" <?php if($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                <option value="no" <?php if($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
            </select>
        </td>
        <th>
            <label <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>
                   id ="labSupervisor" style="white-space: nowrap;">
                Supervisor Name
                <span class='mandatory'>*</span>
            </label>
        </th>
        <td>
            <input name="participantSupervisor" id="participantSupervisor" type="text" class="form-control"
                   value="<?php echo $this->shipment['participant_supervisor'] ; ?>" <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> />
        </td>
    </tr>
    <tr>
        <th>Comments </th>
        <td colspan="3">
            <textarea name="userComments" id="userComments" class="form-control">
                <?php echo $this->shipment['user_comment'] ; ?>
            </textarea>
        </td>
    </tr>
</table>
<?php if ($this->isEditable) { ?>
<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
    <p>
        <input type="hidden" id="submitAction" name="submitAction" />
        <input name="savebtn" class="btn btn-primary" type="submit" value="Save" onclick="javascript:save_form()" />
        &nbsp;&nbsp;&nbsp;
        <input name="submitbtn" class="btn btn-success" type="submit" value="Submit" onclick="javascript:submit_form()" />
        &nbsp;&nbsp;&nbsp;
        <input name="cancel" class="btn btn-danger" type="button" id="reset" value="Cancel" onclick="javascript:goto_dashboard()" />
    </p>
</div>
<?php } ?>
</div>
<?php 
$genderHelper = $this->getHelper('DateFormat');
$dtFormat = $genderHelper->getDateFormat();
?>
</div>
</form>
<?php if (!$this->isEditable) { ?>
<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
    <input name="cancel" class="btn btn-info" type="button" id="reset" value="Back" onclick="javascript:goto_dashboard()" />
</div>
<?php } ?>
</div>
</section>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.validate.js"); ?>"></script>
<script>
  function goto_dashboard() {
    window.history.back();
  }

  function save_form() {
    $('#submitAction').val('save');
  }

  function submit_form() {
    $('#submitAction').val('submit');
  }

  var timeOut, formValidator;

  $(function() {
    $(".datepicker:not(#expiryDate, input[name='instrumentLastCalibratedOn[]'], input[name='instrumentInstalledOn[]'])")
      .datepicker({
        dateFormat: '<?php echo $dtFormat;?>',
        maxDate: '0',
        minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')
      });

    $("#expiryDate")
      .datepicker({
        dateFormat: '<?php echo $dtFormat;?>',
        minDate : new Date('<?php echo $this->shipment['shipment_date']; ?>')
      });

    $("input[name='instrumentLastCalibratedOn[]'], input[name='instrumentInstalledOn[]']")
      .datepicker({ dateFormat: '<?php echo $dtFormat;?>' });

    <?php if (!$this->isEditable) { ?>
    $("#tbResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
	<?php } ?>

    jQuery.validator.addMethod('dateLargerThan', function (value, dateInput, baseDateInputSelector) {
      return moment(value).diff(new Date($(baseDateInputSelector).val())) >= 0;
	});

    jQuery.validator.addMethod('validRifForMtbDetected', function (value, rifInput, mtbInputSelector) {
	  if (['detected', 'high', 'medium', 'low', 'veryLow'].includes($(mtbInputSelector).val())) {
	    return ['detected', 'notDetected', 'indeterminate'].includes(value);
	  }
      return true;
    });

    jQuery.validator.addMethod('validRifForNoMtb', function (value, rifInput, mtbInputSelector) {
      if (!['detected', 'high', 'medium', 'low', 'veryLow'].includes($(mtbInputSelector).val())) {
        return value === 'na';
      }
      return true;
    });

    jQuery.validator.addMethod('ctEndpointValue', function (value) {
      return value <= 42;
    });

    var validationOptions = {
	  errorElement: "div",
      focusInvalid: false,
      errorPlacement: function(error, element) {
        if (element.attr("name") == "receiptDate") {
          error.insertAfter("#clearReceiptDate");
        } else if (element.attr("name") == "expiryDate") {
          error.insertAfter("#clearExpiryDate");
        } else if (element.attr("name") == "testReceiptDate") {
          error.insertAfter("#clearTestReceiptDate");
        } else if (element.attr("name") == "qcDate") {
          error.insertAfter("#clearQcDate");
        } else {
          error.insertAfter(element);
        }
      },
      rules: {
        receiptDate: "required",
        expiryDate: {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit';
            }
          }
        },
        testReceiptDate: {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit';
            }
          }
        },
        mtbRifKitLotNo: {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit';
            }
          }
        },
        assay: {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit';
            }
          }
        },
        qcDate: {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                $("#qcDoneYes").is(":checked");
            }
          }
        },
        qcDoneBy: {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                $("#qcDoneYes").is(":checked");
            }
          }
        },
        participantSupervisor: {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                $('#supervisorApproval').val() === 'yes';
            }
          }
        },
<?php
$count = 0;
$index = 0;
foreach ($this->allSamples as $sample) {
    $count++; ?>
        'dateTested[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit';
            }
          },
          dateLargerThan: {
            param: '#receiptDate',
            depends: function () {
              return $('#submitAction').val() === 'submit';
            }
          }
        },
        'mtbDetected[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit';
            }
          }
        },
        'rifResistance[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit';
            }
          },
          validRifForMtbDetected: {
            param: '#mtbDetected<?php echo $count; ?>',
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                $("#mtbDetected<?php echo $count; ?>").val() !== '';
            }
          },
          validRifForNoMtb: {
            param: '#mtbDetected<?php echo $count; ?>',
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                $("#mtbDetected<?php echo $count; ?>").val() !== '';
            }
          }
        },
        'errorCode[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                $("#mtbDetected<?php echo $count; ?>").val() === 'error';
            }
          }
        },
        'probeD[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          number: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          ctEndpointValue: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          }
        },
        'probeC[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          number: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          ctEndpointValue: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          }
        },
        'probeE[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          number: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          ctEndpointValue: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          }
        },
        'probeB[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          number: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          ctEndpointValue: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          }
        },
        'spc[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          number: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          ctEndpointValue: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          }
        },
        'probeA[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          number: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          },
          ctEndpointValue: {
            depends: function () {
              return $('#submitAction').val() === 'submit' &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val());
            }
          }
        },
<?php
    $index++;
} ?>
      },
      messages: {
        receiptDate: "What date did you receipt the panel?",
        expiryDate: "Please enter the expiration date of MTB/RIF kit",
        testReceiptDate: "When did the lab submit the results?",
        mtbRifKitLotNo: "Please enter the lot number of MTB/RIF kit",
        assay: "Which assay was used to run the samples?",
        qcDate: "When was monthly maintenance done?",
        qcDoneBy: "Who performed monthly maintenance?",
        participantSupervisor: "What is the name of the supervisor who approved this submission?",
<?php
$index = 0;
foreach ($this->allSamples as $sample) { ?>
        'dateTested[<?php echo $index; ?>]': {
          required: "Required",
          dateLargerThan: "Must be after Shipment Receipt Date"
        },
        'mtbDetected[<?php echo $index; ?>]': "Required",
        'rifResistance[<?php echo $index; ?>]': {
          required: "Required",
          validRifForMtbDetected: "Invalid Selection for MTB Detected",
          validRifForNoMtb: "Invalid Selection for MTB Detected"
        },
        'errorCode[<?php echo $index; ?>]': "Required",
        'probeD[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
        'probeC[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
        'probeE[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
        'probeB[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
        'spc[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
        'probeA[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
<?php
    $index++;
} ?>
      }
    };

    formValidator = $("#tbResponseForm").validate(validationOptions);
    $("#tbResponseForm").submit(function(event) {
      var errors = formValidator.numberOfInvalids();
      if (errors) {
        $('html body').animate({
          scrollTop: $(formValidator.errorList[0].element).offset().top - 100
        }, 1000);
        event.preventDefault();
      }
    });
  });

  $('.oneDecimal, .zeroDecimal').keypress(function () {
    var $this = $(this);
	$this.val($this.val().replace(/[^\d.]/g, ''));
  });

  $('.sampleTestDate').change(function () {
    $('.sampleTestDate').each(function() { });
  });

  $(".oneDecimal").on("blur", function(el) {
    clearTimeout(timeOut);
	timeOut = setTimeout(function() {
	  var newVal = Number($(el.target).val()).toFixed(1);
	  if ($.isNumeric(newVal)) {
	    $(el.target).val(newVal);
	  } else {
	    $(el.target).val(0);
	  }
	}, 600);
  });

  $(".zeroDecimal").on("blur", function(el) {
    clearTimeout(timeOut);
    timeOut = setTimeout(function() {
      var newVal = Number($(el.target).val()).toFixed(0);
      if ($.isNumeric(newVal)) {
        $(el.target).val(newVal);
      } else {
        $(el.target).val(0);
      }
    },600);
  });

  function validateNow() {
    if (!formValidator.valid()) {
      formValidator.showErrors();
    }
    return formValidator.valid();
  }

  $('#supervisorApproval').change(function() {
    if ($('#supervisorApproval').val() == 'yes') {
      $('#labSupervisor').show();
      $('#participantSupervisor').val('');
      $('#participantSupervisor').show();
    } else {
      $('#labSupervisor').hide();
      $('#participantSupervisor').val('');
      $('#participantSupervisor').hide();
    }
  });

  function clearDate(id) {
    $("#" + id).val('');
  }

  function checkQcStatus(){
    var radioValue = $("input[name='qcDone']:checked"). val();
    if (radioValue == "yes") {
      $("#qcSection").show();
      $("#qcDate").addClass("isRequired");
      $("#qcDoneBy").addClass("isRequired");
    } else {
      $("#qcSection").hide();
      $("#qcDate").val("");
      $("#qcDoneBy").val("");
      $("#qcDate").removeClass("isRequired");
      $("#qcDoneBy").removeClass("isRequired");
    }
  }

  function changeInstrument(details) {
    $("#" + details.serialTextFieldId).val(details.serial);
    $("#" + details.installedOnTextFieldId).val(details.installedOn);
    $("#" + details.lastCalibratedOnTextFieldId).val(details.lastCalibratedOn);
    $("#" + details.dropDownId + " a span.dropdownText").text(details.serial);
    return false;
  }

  function newInstrument(details) {
    $("#" + details.serialTextFieldId).val('');
    $("#" + details.installedOnTextFieldId).val('');
    $("#" + details.lastCalibratedOnTextFieldId).val('');
    $("#" + details.dropDownId).css('display', 'none');
    $("#" + details.serialTextFieldId).css('display', 'block');
    $("#" + details.serialTextFieldId).focus();
    return false;
  }

  function changeMtbDetected(resultNumber) {
    var mtbDetected = $("#mtbDetected" + resultNumber).val();
    var errorCodeInput = $("#errorCode" + resultNumber);
    var rifResistanceSelect = $("#rifResistance" + resultNumber);
    if (mtbDetected === "error") {
      errorCodeInput.removeAttr("readonly");
    } else {
      errorCodeInput.attr("readonly", "");
      errorCodeInput.val('')
    }
    if (["detected", "high", "medium", "low", "veryLow"].includes(mtbDetected)) {
      rifResistanceSelect.removeAttr("readonly");
    } else {
      rifResistanceSelect.attr("readonly", "");
      rifResistanceSelect.val('na')
    }
  }
</script>
