<?php
$authNameSpace = new Zend_Session_Namespace('datamanagers');
if (isset($this->shipment["shipment_test_report_date"]) &&
        trim($this->shipment["shipment_test_report_date"]) != "") {
    $expTestReceiptDate = explode(" ",$this->shipment["shipment_test_report_date"]);
    $testReceiptDate = $this->dateFormat($expTestReceiptDate[0]);
} else {
	$testReceiptDate = date('d-M-Y');
} ?>
<style>
    th {
        text-align: center;
    }
	table,th,td {
		border-color: #ccc !important;
	}
	.hideOtherAssay {
		display: none;
	}

    div.error {
        color: #ff0000;
        float: left;
    }

    input.error, select.error {
        border: solid 1px #ff0000;
    }
</style>
<section class="content-header">
    <h1><?php echo $this->shipment['scheme_name'];?></h1>
</section>
<section class="content">
<div class="box">
<form name="tbResponseForm" id="tbResponseForm" method="post"
      action="<?php echo $this->url(array("controller"=>"tb","action"=>"response"),null,true) ?>"
      onsubmit="return validateNow();return false;">
<div class="box-body">
<input type="hidden" id ="hdLastDate" name="hdLastDate" value="<?php echo $this->shipment['lastdate_response'];?>" />
<input type="hidden" id ="smid" name="smid" value="<?php echo $this->shipment['map_id'];?>" />
<input type="hidden" id ="shipmentId" name="shipmentId" value="<?php echo $this->shipId;?>" />
<input type="hidden" id ="participantId" name="participantId" value="<?php echo $this->participantId;?>" />
<input type="hidden" id ="evId" name="evId" value="<?php echo $this->eID;?>" />
<?php $count =0;
foreach ($this->allSamples as $sample) {
    $count++;  ?>
<input type="hidden" id ="<?php echo $count . "_hdSampleId"; ?>" name="<?php echo $count . "_hdSampleId"; ?>"
       value="<?php echo $sample['sample_id'];?>" />
<?php
} ?>
<div id="view-content">
<br />
<div id=error></div>
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
    <tr>
        <td style="width:20%;">
            <h4 class="text-info"> Participant Name </h4>&nbsp;
            <?php echo ( $this->participant['first_name'] . ' ' . $this->participant['last_name'] );?>
        </td>
        <td style="width:20%;">
            <h4 class="text-info"> Participant Code </h4>&nbsp;
            <?php echo $this->participant['unique_identifier'] ?>
        </td>
        <td style="width:20%;">
            <h4 class="text-info"> Affiliation </h4>&nbsp;
            <?php echo ( $this->participant['affiliation'] );?>
        </td>
        <td style="width:20%;">
            <h4 class="text-info"> Phone No </h4>&nbsp;
            <?php  echo ( $this->participant['mobile']  . '<br/>' .   $this->participant['phone'] ); ?>
        </td>
    </tr>
</table>
<hr />
<table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
    <tr>
        <td colspan="2">
            <h4 class="text-info">
                Are you able to test the performance evaluation panel?
                &nbsp;&nbsp;&nbsp;&nbsp;
                <input type="radio" id="ableToEnterResultsYes" name="ableToEnterResults" value="yes"
                <?php echo ($this->shipment['is_pt_test_not_performed'] == "no" || $this->shipment['is_pt_test_not_performed'] == "" || $this->shipment['is_pt_test_not_performed'] == null) ? " checked='checked' " : ""; ?> />
                <label for="ableToEnterResultsYes">Yes</label>&nbsp;&nbsp;
                <input type="radio" id="ableToEnterResultsNo" name="ableToEnterResults" value="no"
                <?php echo ($this->shipment['is_pt_test_not_performed'] == "yes") ? " checked='checked' " : ""; ?> />
                <label for="ableToEnterResultsNo">No</label>
            </h4>
        </td>
    </tr>
    <tr id="ableToEnterResultsReasonsRow" style="display: <?php echo ($this->shipment['is_pt_test_not_performed'] == "no" || $this->shipment['is_pt_test_not_performed'] == "" || $this->shipment['is_pt_test_not_performed'] == null) ? "none" : "table-row"; ?>;">
        <td style="width:20%">
            <label for="notTestedReason">Reason for not testing the panel</label> <span class="mandatory">*</span>:
        </td>
        <td>
            <select id="notTestedReason" name="notTestedReason" class="form-control" title="Please select reason" style="width:60%;">
                <option value="">--Select--</option>
<?php
foreach($this->allNotTestedReason as $reason) { ?>
                <option value="<?php echo $reason['not_tested_reason_id']; ?>"
                    <?php echo($this->shipment['not_tested_reason'] == $reason['not_tested_reason_id']) ? 'selected="selected"':''; ?>>
                    <?php echo ucwords($reason['not_tested_reason']); ?>
                </option>
<?php
} ?>
                <option value="other"
                    <?php echo (isset($this->shipment['pt_test_not_performed_comments']) && trim($this->shipment['pt_test_not_performed_comments']) != "") ? 'selected="selected"' : ''; ?>>
                    Other
                </option>
            </select>
        </td>
    </tr>
    <tr id="ableToEnterResultsOtherReasonRow" style="display: <?php echo (isset($this->shipment['pt_test_not_performed_comments']) && trim($this->shipment['pt_test_not_performed_comments']) != '') ? 'table-row' : 'none'; ?>;">
        <td>
            <label for="notTestedOtherReason">Please specify</label> <span class="mandatory">*</span>:
        </td>
        <td>
            <input type="text" name="notTestedOtherReason" id="notTestedOtherReason" class="form-control isRequired"
                   value="<?php echo $this->shipment['pt_test_not_performed_comments']; ?>" />
        </td>
    </tr>
</table>
<hr />
<table id="submissionHeader" class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
	<tr class="dark">
		<td style="width:20%;">
            <label>Shipment Date</label>
        </td>
		<td style="width:30%;">
            <?php echo $this->dateFormat($this->shipment['shipment_date']) ?>
        </td>
		<td style="width:20%;">
            <label>Result Due Date</label>
        </td>
		<td style="width:30%;">
            <?php echo $this->dateFormat($this->shipment['lastdate_response']);?>
        </td>
	</tr>
	<tr class ="light">
		<td style="width:20%; white-space: nowrap;">
            <label>Shipment Receipt Date</label>
            <span class='mandatory'>*</span>
        </td>
		<td style="width:30%;">
			<input type="text" id="receiptDate" name="receiptDate" size="11" maxlength="11" style="width:180px;float:left;"
                   value="<?php  echo $this->dateFormat($this->shipment["shipment_receipt_date"]);  ?>"
                   class="form-control isRequired datepicker" readonly />&nbsp;
			<i id="clearReceiptDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('receiptDate')"> Clear</i>
		</td>
        <td style="white-space: nowrap;">
            <label>Assay</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <select class="form-control" name="assay" id="assay" class="form-control"
                    title="Please choose the assay type">
                <?php
                foreach ($this->assays as $id => $definition) { ?>
                    <option value="<?php echo $id; ?>"
                        <?php if (isset($this->shipment['attributes']['assay'])) { echo ($this->shipment['attributes']['assay'] == $id) ? "selected='selected'" : ""; } ?>>
                        <?php echo $definition['name']; ?>
                    </option>
                    <?php
                } ?>
            </select>
        </td>
	</tr>
    <tr class ="dark">
		<td style="white-space: nowrap;">
            <label>Cartridge Lot No</label>
            <span class='mandatory'>*</span>
        </td>
		<td>
		    <input type="text" name="cartridgeLotNo" id="cartridgeLotNo" class="form-control isRequired"
                   value="<?php echo $this->shipment['attributes']['cartridge_lot_no'];?>"/>
		</td>
		<td style="width:20%; white-space: nowrap;">
            <label>Expiration date of Cartridge</label>
            <span class='mandatory'>*</span>
        </td>
		<td style="width:30%;">
			<input type="text" name="expiryDate" id="expiryDate" class="form-control isRequired datepicker"
                   size="11" maxlength="11" style="width:180px;float:left;" value="<?php echo $this->shipment['attributes']['expiry_date'];?>"
                   readonly="readonly"/>&nbsp;
			<i id="clearExpiryDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('expiryDate')"> Clear</i>
		</td>
	</tr>
    <tr class="light">
        <td style="white-space: nowrap;">
            <label>Response Date</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <input type="text" id="testReceiptDate" name="testReceiptDate" size="11" maxlength="11"
                   style="width:180px;float:left;" value="<?php echo $testReceiptDate; ?>" class="form-control datepicker"
                   readonly="readonly" title="Please enter Shipment Test Response Date " />&nbsp;
            <i id="clearTestReceiptDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"
               onclick="clearDate('testReceiptDate')"> Clear</i>
        </td>
        <td colspan="2"></td>
    </tr>
    <tr class="dark">
        <td>
            <label>How many Xpert MTB/RIF and MTB Ultra tests have been conducted by this site in the last full month?</label>
        </td>
        <td>
            <input type="text" name="countTestsConductedOverMonth" id="countTestsConductedOverMonth"
                   class="form-control zeroDecimal numberInput"
                   value="<?php if(isset($this->shipment['attributes']['count_tests_conducted_over_month'])) { echo $this->shipment['attributes']['count_tests_conducted_over_month']; }?>" />
        </td>
        <td>
            <label>How many errors occurred during testing in the last full month?</label>
        </td>
        <td>
            <input type="text" name="countErrorsEncounteredOverMonth" id="countErrorsEncounteredOverMonth"
                   class="form-control zeroDecimal numberInput"
                   value="<?php if(isset($this->shipment['attributes']['count_errors_encountered_over_month'])) { echo $this->shipment['attributes']['count_errors_encountered_over_month']; }?>" />
        </td>
    </tr>
    <tr class="light">
        <td>
            <label>What were the error codes?</label>
        </td>
        <td colspan="3">
            <input type="text" name="errorCodesEncounteredOverMonth" id="errorCodesEncounteredOverMonth" class="form-control"
                   value="<?php if(isset($this->shipment['attributes']['error_codes_encountered_over_month'])) { echo $this->shipment['attributes']['error_codes_encountered_over_month']; }?>" />
        </td>
    </tr>
    <?php
	if ($this->globalQcAccess=='yes' && (isset($authNameSpace->qc_access) && $authNameSpace->qc_access=='yes')) { ?>
    <tr class="dark">
        <td>
            <label>Monthly Maintenance Done</label>
        </td>
        <td>
            <input type="radio" id="qcDoneYes" name="qcDone" value="yes"
                <?php echo ($this->shipment['qc_done']=="yes") ? " checked='checked' " : ""; ?> onclick="checkQcStatus();" />
            <strong>Yes</strong>&nbsp;&nbsp;
            <input type="radio" id="qcDoneNo" name="qcDone" value="no" title="Please select monthly maintenance done status"
                   onclick="checkQcStatus();" <?php echo ($this->shipment['qc_done']== null || $this->shipment['qc_done']=="" || $this->shipment['qc_done']=="no") ? " checked='checked' " : ""; ?> />
            <strong>No</strong>
        </td>
        <td colspan="2"></td>
    </tr>
<?php
        $display = "display:none";
        $isRequired = "";
        if (isset($this->shipment['qc_done']) && $this->shipment['qc_done'] == "yes") {
            $display = "";
            $isRequired = "required";
        } ?>
    <tr id="qcSection" class="light" style="<?php echo $display; ?>">
        <td style="white-space: nowrap;">
            <label>Maintenance Date</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <input type="text" id="qcDate" name="qcDate" size="11" maxlength="11" style="width:180px;float:left;"
                   value="<?php echo $this->dateFormat($this->shipment["qc_date"]); ?>"
                   class="form-control datepicker<?php echo $isRequired ? ' isRequired' : ''; ?>" readonly="readonly"
                   title="Please enter Maintenance Date" />&nbsp;
            <i id="clearQcDate" class="icon-remove-sign" style="cursor:pointer;margin-top:10px;margin-left:10px;float:left;" alt="Clear Date" title="Clear Date"  onclick="clearDate('qcDate')"> Clear</i>
        </td>
        <td style="white-space: nowrap;">
            <label>Maintenance Done By</label>
            <span class='mandatory'>*</span>
        </td>
        <td>
            <input type="text" id="qcDoneBy" name="qcDoneBy" title="Please enter who performed maintenance"
                   class="form-control<?php echo $isRequired ? ' isRequired' : ''; ?>"
                   value="<?php echo $this->shipment["qc_done_by"]; ?>" />
        </td>
    </tr>
<?php
	} ?>
    <tr>
        <td colspan="4">
            <label>Instruments at Facility:</label>
            <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
                <thead>
                <tr>
                    <td>
                        <label>Serial Number</label>
                    </td>
                    <td>
                        <label>Installed</label>
                    </td>
                    <td>
                        <label>Last Calibrated</label>
                    </td>
                    <td>
                        <label>Add/Remove</label>
                    </td>
                </tr>
                </thead>
                <tbody>
<?php
        $instrumentCount = 0;
        $instrumentIndex = 0;
        foreach ($this->instruments as $id => $instrument_details) {
            $instrumentCount++; ?>
                <tr>
                    <td>
                        <input type="hidden" name="headerInstrumentIndex[<?php echo $instrumentIndex; ?>]"
                               class="instrumentIndex" value="<?php echo $instrumentIndex; ?>" />
                        <input type="hidden" id="headerInstrumentId<?php echo $instrumentCount; ?>"
                               name="headerInstrumentId[<?php echo $instrumentIndex; ?>]"
                               value="<?php echo $id; ?>"  />
                        <input type="text" id="headerInstrumentSerial<?php echo $instrumentCount; ?>"
                               name="headerInstrumentSerial[<?php echo $instrumentIndex; ?>]"
                               class="form-control input-sm" value="<?php echo $instrument_details['instrument_serial']; ?>"
                               title="Please enter the instrument serial number"
                               onblur="updateInstrumentLists()" />
                    </td>
                    <td>
                        <input type="text" id="headerInstrumentInstalledOn<?php echo $instrumentCount; ?>"
                               class="form-control datepicker input-sm instrument-date-picker" readonly="readonly"
                               name="headerInstrumentInstalledOn[<?php echo $instrumentIndex; ?>]"
                               value="<?php echo $this->dateFormat($instrument_details['instrument_installed_on']); ?>"
                               title="Please enter the instrument installation date" />
                    </td>
                    <td>
                        <input type="text" id="headerInstrumentLastCalibratedOn<?php echo $instrumentCount; ?>"
                               class="form-control datepicker input-sm instrument-date-picker" readonly="readonly"
                               name="headerInstrumentLastCalibratedOn[<?php echo $instrumentIndex; ?>]"
                               value="<?php echo $this->dateFormat($instrument_details['instrument_last_calibrated_on']); ?>"
                               title="Please enter the date that the instrument was last calibrated" />
                    </td>
                    <td>
                        <a href="javascript:void(0);" onclick="addInstrumentRow(this);"
                           class="btn btn-xs btn-info">
                            <i class="icon-plus"></i>
                        </a>&nbsp;&nbsp;
                        <a href="javascript:void(0);" onclick="removeInstrumentRow(this)" class="btn btn-xs btn-danger"
                           title="Remove this instrument" alt="Remove this instrument">
                            <i class="icon-minus"></i>
                        </a>
                    </td>
                </tr>
<?php
            $instrumentIndex++;
        } ?>
                </tbody>
            </table>
        </td>
    </tr>
</table>
<hr />
<div>
    <table id="results" class="table table-bordered table-striped" style="width:100%;margin:10px auto;" cellpadding="0">
    <?php
    $count = 0;
    $index = 0;
    foreach ($this->allSamples as $sample) {
        $count++;
        $errorCodeEnabled = $sample['res_mtb_detected'] == "error";
        $rifResistanceEnabled = in_array($sample['res_mtb_detected'], array("detected", "high", "medium", "low", "veryLow")); ?>
        <tr>
            <td style="padding: 0;">
                <table class="table" style="width: 100%;background-color: transparent;">
                    <tr>
                        <th colspan="11" style="white-space: nowrap;background-color: transparent;">
                            <?php echo $sample['sample_label']; ?> <?php echo ($sample['mandatory'] == 1) ? " <span class='mandatory'>*</span>" : "&nbsp;&nbsp;"; ?>
                            <input type="hidden" id="sample<?php echo $count; ?>" name="sampleId[<?php echo $index; ?>]"
                                   value="<?php echo $sample['sample_id'];?>" />
                        </th>
                    </tr>
                    <tr>
                        <th rowspan="2" style="vertical-align: middle; width:14%;">Result Details</th>
                        <th style="vertical-align: bottom; width:14%;">Date Tested</th>
                        <th style="vertical-align: bottom; width:14%;">MTB Detected</th>
                        <th class="errorCode" style="vertical-align: bottom; width:9%;">Error Code</th>
                        <th style="vertical-align: bottom; width:13%;">Rif Resistance</th>
                        <th class="probe1Header" style="vertical-align: bottom; width:6%;"></th>
                        <th class="probe2Header" style="vertical-align: bottom; width:6%;"></th>
                        <th class="probe3Header" style="vertical-align: bottom; width:6%;"></th>
                        <th class="probe4Header" style="vertical-align: bottom; width:6%;"></th>
                        <th class="probe5Header" style="vertical-align: bottom; width:6%;"></th>
                        <th class="probe6Header" style="vertical-align: bottom; width:6%;"></th>
                    </tr>
                    <tr style="background-color: transparent;">
                        <td style="background-color: transparent;">
                            <input type="text" id="sampleTestDate<?php echo $count; ?>"
                                   class="form-control datepicker input-sm sampleTestDate"
                                   readonly name="dateTested[<?php echo $index; ?>]"
                                   value="<?php echo $this->dateFormat($sample['res_date_tested']); ?>"
                                   title="Please enter the Test Date for <?php echo $sample['sample_label']; ?>" />
                        </td>
                        <td style="background-color: transparent;">
                            <select id="mtbDetected<?php echo $count; ?>" name="mtbDetected[<?php echo $index; ?>]"
                                    class="isRequired form-control input-sm mtbDetected" title="Please enter the MTB Detected for this sample"
                                    placeholder="Please enter the MTB Detected for this sample"
                                    onChange="changeMtbDetected(<?php echo $count; ?>)">
                                <option value="">-- Select --</option>
                                <option value="detected" <?php echo ($sample['res_mtb_detected'] == 'detected' ? "selected='selected'" : ""); ?>>
                                    Detected
                                </option>
                                <option value="high" <?php echo ($sample['res_mtb_detected'] == 'high' ? "selected='selected'" : ""); ?>>
                                    High
                                </option>
                                <option value="medium" <?php echo ($sample['res_mtb_detected'] == 'medium' ? "selected='selected'" : ""); ?>>
                                    Medium
                                </option>
                                <option value="low" <?php echo ($sample['res_mtb_detected'] == 'low' ? "selected='selected'" : ""); ?>>
                                    Low
                                </option>
                                <option value="veryLow" <?php echo ($sample['res_mtb_detected'] == 'veryLow' ? "selected='selected'" : ""); ?>>
                                    Very Low
                                </option>
                                <option value="notDetected" <?php echo ($sample['res_mtb_detected'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                    Not Detected
                                </option>
                                <option value="noResult" <?php echo ($sample['res_mtb_detected'] == 'noResult' ? "selected='selected'" : ""); ?>>
                                    No Result
                                </option>
                                <option value="invalid" <?php echo ($sample['res_mtb_detected'] == 'invalid' ? "selected='selected'" : ""); ?>>
                                    Invalid
                                </option>
                                <option value="error" <?php echo ($sample['res_mtb_detected'] == 'error' ? "selected='selected'" : ""); ?>>
                                    Error
                                </option>
                            </select>
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" id="errorCode<?php echo $count; ?>" name="errorCode[<?php echo $index; ?>]"
                                   class="form-control input-sm errorCode" value="<?php echo $sample['res_error_code']; ?>"
                                   title="Please enter the Error Code for <?php echo $sample['sample_label']; ?>" <?php if (!$errorCodeEnabled) { echo "readonly"; } ?> />
                        </td>
                        <td style="background-color: transparent;">
                            <select id="rifResistance<?php echo $count; ?>" name="rifResistance[<?php echo $index; ?>]"
                                    class="isRequired form-control input-sm"
                                    title="Please enter the Rif Resistance for this sample"
                                    placeholder="Please enter the Rif Resistance for this sample" <?php if (!$rifResistanceEnabled) { echo "readonly"; } ?>>
                                <option value="">
                                    -- Select --
                                </option>
                                <option value="detected" <?php echo ($sample['res_rif_resistance'] == 'detected' ? "selected='selected'" : ""); ?>>
                                    Detected
                                </option>
                                <option value="notDetected" <?php echo ($sample['res_rif_resistance'] == 'notDetected' ? "selected='selected'" : ""); ?>>
                                    Not Detected
                                </option>
                                <option value="indeterminate" <?php echo ($sample['res_rif_resistance'] == 'indeterminate' ? "selected='selected'" : ""); ?>>
                                    RIF Indeterminate
                                </option>
                                <option value="na" <?php echo ($sample['res_rif_resistance'] == 'na' ? "selected='selected'" : ""); ?>>
                                    N/A
                                </option>
                            </select>
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probe1[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_1']; ?>" id="probe1<?php echo $count; ?>"
                                   title="Please enter all Ct values for each sample" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probe2[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_2']; ?>" id="probe2<?php echo $count; ?>"
                                   title="Please enter all Ct values for each sample" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probe3[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_3']; ?>" id="probe3<?php echo $count; ?>"
                                   title="Please enter all Ct values for each sample" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probe4[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_4']; ?>" id="probe4<?php echo $count; ?>"
                                   title="Please enter all Ct values for each sample" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probe5[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_5']; ?>" id="probe5<?php echo $count; ?>"
                                   title="Please enter all Ct values for each sample" />
                        </td>
                        <td style="background-color: transparent;">
                            <input type="text" name="probe6[<?php echo $index; ?>]" class="form-control input-sm oneDecimal numberInput"
                                   value="<?php echo $sample['res_probe_6']; ?>" id="probe6<?php echo $count; ?>"
                                   title="Please enter all Ct values for each sample" />
                        </td>
                    </tr>
                    <tr>
                        <th rowspan="2" style="vertical-align: middle;">Instrument/Cartridge Details</th>
                        <th style="vertical-align: bottom;">Serial Number</th>
                        <th colspan="2" style="vertical-align: bottom;">Module Number</th>
                        <th colspan="4" style="vertical-align: bottom;">Instrument User</th>
                    </tr>
                    <tr style="background-color: transparent;">
                        <th style="white-space: nowrap;background-color: transparent;">
                            <input type="hidden" id="instrumentSerial<?php echo $count; ?>"
                                   name="instrumentSerial[<?php echo $index; ?>]"
                                   value="<?php echo $sample['res_instrument_serial']; ?>" />
                            <div id="instrumentDropDown<?php echo $count; ?>" class="btn-group" style="display: block; border: solid 1px #ccc; width: 100%; height: 2.13em;">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#" style="width: 100%; padding-top: 3px;">
                                    <span class="dropdownText">
                                        <?php echo (isset($sample['res_instrument_serial']) && $sample['res_instrument_serial'] != "" ? $sample['res_instrument_serial'] : "-- Select --") ?>
                                    </span>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu instrument-list">
                                    <?php
                                    foreach ($this->instruments as $id => $instrument_details) {
                                        if ($id != "-1") { ?>
                                    <li class="instrument-list-item">
                                        <a href="" onClick="return changeInstrument({serial: '<?php echo $instrument_details["instrument_serial"]; ?>', installedOn: '<?php echo $this->dateFormat($instrument_details["instrument_installed_on"]); ?>', lastCalibratedOn: '<?php echo $this->dateFormat($instrument_details["instrument_last_calibrated_on"]); ?>', dropDownId: 'instrumentDropDown<?php echo $count; ?>', serialTextFieldId: 'instrumentSerial<?php echo $count; ?>', installedOnTextFieldId: 'instrumentInstalledOn<?php echo $count; ?>', lastCalibratedOnTextFieldId: 'instrumentLastCalibratedOn<?php echo $count; ?>'})">
                                            <?php echo $instrument_details['instrument_serial']; ?>
                                        </a>
                                    </li>
                                    <?php
                                        }
                                    } ?>
                                </ul>
                            </div>
                        </th>
                        <th colspan="2" style="white-space: nowrap;background-color: transparent;">
                            <input type="text" name="moduleName[<?php echo $index; ?>]"
                                   class="form-control input-sm" value="<?php echo $sample['res_module_name']; ?>"
                                   title="Please enter the module number for <?php echo $sample['sample_label']; ?>" />
                        </th>
                        <th colspan="4" style="white-space: nowrap;background-color: transparent;">
                            <input type="text" name="instrumentUser[<?php echo $index; ?>]"
                                   class="form-control input-sm" value="<?php echo $sample['res_instrument_user']; ?>"
                                   title="Please enter the instrument user for <?php echo $sample['sample_label']; ?>" />
                        </th>
                    </tr>
                </table>
            </td>
        </tr>
    <?php
        $index++;
    } ?>
    </table>
</div>
<br />
<hr />
<table id="submissionFooter" class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
    <tr>
        <th style="width:20%;">Supervisor Review</th>
        <td style="width:20%;">
            <select name="supervisorApproval" id="supervisorApproval" class="form-control isRequired">
                <option value="">--Select--</option>
                <option value="yes" <?php if($this->shipment['supervisor_approval'] == 'yes') echo " selected "; ?>>Yes</option>
                <option value="no" <?php if($this->shipment['supervisor_approval'] == 'no') echo " selected "; ?>>No</option>
            </select>
        </td>
        <th>
            <label <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?>
                   id ="labSupervisor" style="white-space: nowrap;">
                Supervisor Name
                <span class='mandatory'>*</span>
            </label>
        </th>
        <td>
            <input name="participantSupervisor" id="participantSupervisor" type="text" class="form-control"
                   value="<?php echo $this->shipment['participant_supervisor'] ; ?>" <?php echo(isset($this->shipment['supervisor_approval']) && $this->shipment['supervisor_approval'] == 'yes') ? "" : "style='display:none;'" ?> />
        </td>
    </tr>
    <tr>
        <th>Comments </th>
        <td colspan="3">
            <textarea name="userComments" id="userComments" class="form-control"><?php echo $this->shipment['user_comment'] ; ?></textarea>
        </td>
    </tr>
</table>
<?php if ($this->isEditable) { ?>
<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
    <p>
        <input type="hidden" id="submitAction" name="submitAction" />
        <input name="savebtn" class="btn btn-primary" type="submit" value="Save" onclick="javascript:save_form()" />
        &nbsp;&nbsp;&nbsp;
        <input name="submitbtn" class="btn btn-success" type="submit" value="Submit" onclick="javascript:submit_form()" />
        &nbsp;&nbsp;&nbsp;
        <input name="cancel" class="btn btn-danger" type="button" id="reset" value="Cancel" onclick="javascript:goto_dashboard()" />
    </p>
</div>
<?php } ?>
</div>
<?php
$genderHelper = $this->getHelper('DateFormat');
$dtFormat = $genderHelper->getDateFormat();
?>
</div>
</form>
<?php if (!$this->isEditable) { ?>
<div id="respond" style="margin: 0px auto 0px auto; text-align: center;">
    <input name="cancel" class="btn btn-info" type="button" id="reset" value="Back" onclick="javascript:goto_dashboard()" />
</div>
<?php } ?>
</div>
</section>
<script type="text/javascript" src="<?php echo $this->baseUrl("js/jquery.validate.js"); ?>"></script>
<script>
  function goto_dashboard() {
    window.history.back();
  }

  function save_form() {
    $('#submitAction').val('save');
  }

  function submit_form() {
    $('#submitAction').val('submit');
  }

  function toggleToEnterResults() {
    if ($("input[name='ableToEnterResults']:checked").val() === "yes") {
      $("#ableToEnterResultsReasonsRow").hide();
      $("#ableToEnterResultsOtherReasonRow").hide();
      $("#notTestedReason").val("");
      $("#notTestedOtherReason").val("");
      $("#submissionHeader").find("input,select,textarea").removeAttr("disabled");
      $("#submissionHeader").find("input,select,textarea").not(".datepicker").removeAttr("readonly");
      $("#results").find("input,select,textarea").removeAttr("disabled");
      $("#results").find("input,select,textarea").not(".datepicker").removeAttr("readonly");
      $("#results").find(".btn.dropdown-toggle").attr("data-toggle", "dropdown");
      $("#results").find(".btn.dropdown-toggle").attr("href", "#");
      $("#results").find(".dropdownTextContainer").removeAttr("disabled");
      $("#submissionFooter").find("input,select,textarea").removeAttr("disabled");
      $("#submissionFooter").find("input,select,textarea").not(".datepicker").removeAttr("readonly");
      for (var i = 1; i <= 5; i++) {
        changeMtbDetected(i)
      }
    } else if ($("input[name='ableToEnterResults']:checked").val() === "no") {
      $("#ableToEnterResultsReasonsRow").show();
      $("#submissionHeader").find("input,select,textarea").attr("disabled", "");
      $("#submissionHeader").find("input,select,textarea").not(".datepicker").attr("readonly", "");
      $("#results").find("input,select,textarea").attr("disabled", "");
      $("#results").find("input,select,textarea").not(".datepicker").attr("readonly", "");
      $("#results").find(".btn.dropdown-toggle").removeAttr("data-toggle");
      $("#results").find(".btn.dropdown-toggle").removeAttr("href");
      $("#results").find(".dropdownTextContainer").attr("disabled", "");
      $("#submissionFooter").find("input,select,textarea").attr("disabled", "");
      $("#submissionFooter").find("input,select,textarea").not(".datepicker").attr("readonly", "");
    }
  }
  var analyteLables = {
  <?php foreach ($this->assays as $id => $definition) {
      echo "    \"".$id."\": {\n";
      echo "      \"analyte1Label\": \"".$definition['analyte1Label']."\",\n";
      echo "      \"analyte2Label\": \"".$definition['analyte2Label']."\",\n";
      echo "      \"analyte3Label\": \"".$definition['analyte3Label']."\",\n";
      echo "      \"analyte4Label\": \"".$definition['analyte4Label']."\",\n";
      echo "      \"analyte5Label\": \"".$definition['analyte5Label']."\",\n";
      echo "      \"analyte6Label\": \"".$definition['analyte6Label']."\",\n";
      echo "      \"includeTraceForMtbDetected\": ".$definition['includeTraceForMtbDetected']."\n";
      echo "    },\n";
    } ?>
  };
  function setAssay() {
    var selectedAssayId = $("#assay").val();
    if (!selectedAssayId) {
      selectedAssayId = Object.keys(analyteLables)[0];
    }
    var selectedAssayDefinition = analyteLables[selectedAssayId];
    $(".probe1Header").text(selectedAssayDefinition['analyte1Label']);
    $(".probe2Header").text(selectedAssayDefinition['analyte2Label']);
    $(".probe3Header").text(selectedAssayDefinition['analyte3Label']);
    $(".probe4Header").text(selectedAssayDefinition['analyte4Label']);
    $(".probe5Header").text(selectedAssayDefinition['analyte5Label']);
    $(".probe6Header").text(selectedAssayDefinition['analyte6Label']);
    if (selectedAssayDefinition['includeTraceForMtbDetected'] && !$(".mtbDetected option[value='trace']").length) {
      $("<option value='trace'>Trace</option>").insertAfter(".mtbDetected option[value='veryLow']");
    } else {
      $(".mtbDetected option[value='trace']").remove();
    }
  }

  var timeOut, formValidator;

  var previouslySubmitted = false;
  $(function() {
    <?php if ($this->shipment['evaluation_status'][2] == '1') { ?>
    previouslySubmitted = true;
    <?php } else { ?>
    previouslySubmitted = false;
    <?php } ?>

    $(".datepicker:not(.instrument-date-picker)")
      .datepicker({
        dateFormat: '<?php echo $dtFormat;?>'
      });

    $(".instrument-date-picker").datepicker({
      dateFormat: '<?php echo $dtFormat;?>',
      onSelect: updateInstrumentLists
    });

    <?php if (!$this->isEditable) { ?>
    $("#tbResponseForm").find("input:enabled, select:enabled, textarea:enabled").attr("disabled", "disabled");
	<?php } ?>

    $("input[name='ableToEnterResults']").on('click change', toggleToEnterResults);

    $("#notTestedReason").on('change', function(e) {
      if ($("#notTestedReason").val() === "other") {
        $("#ableToEnterResultsOtherReasonRow").show();
      } else {
        $("#ableToEnterResultsOtherReasonRow").hide();
        $("#notTestedOtherReason").val("");
      }
    });

    $("#assay").on('change', setAssay);
    setAssay();
    jQuery.validator.addMethod('dateLargerThan', function (value, dateInput, baseDateInputSelector) {
      return moment(value).diff(new Date($(baseDateInputSelector).val())) >= 0;
	});

    jQuery.validator.addMethod('validRifForMtbDetected', function (value, rifInput, mtbInputSelector) {
	  if (['detected', 'high', 'medium', 'low', 'veryLow'].includes($(mtbInputSelector).val())) {
	    return ['detected', 'notDetected', 'indeterminate'].includes(value);
	  }
      return true;
    });

    jQuery.validator.addMethod('validRifForNoMtb', function (value, rifInput, mtbInputSelector) {
      if (!['detected', 'high', 'medium', 'low', 'veryLow'].includes($(mtbInputSelector).val())) {
        return value === 'na';
      }
      return true;
    });

    jQuery.validator.addMethod('ctEndpointValue', function (value) {
      return value <= 42;
    });

    var validationOptions = {
	  errorElement: "div",
      focusInvalid: false,
      errorPlacement: function(error, element) {
        if (element.attr("name") == "receiptDate") {
          error.insertAfter("#clearReceiptDate");
        } else if (element.attr("name") == "expiryDate") {
          error.insertAfter("#clearExpiryDate");
        } else if (element.attr("name") == "testReceiptDate") {
          error.insertAfter("#clearTestReceiptDate");
        } else if (element.attr("name") == "qcDate") {
          error.insertAfter("#clearQcDate");
        } else {
          error.insertAfter(element);
        }
      },
      rules: {
        notTestedReason: {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("input[name='ableToEnterResults']:checked").val() === "no";
            }
          }
        },
        notTestedOtherReason: {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("#notTestedReason").val() === "other";
            }
          }
        },
        receiptDate: {
          required: {
            depends: function () {
              return $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        expiryDate: {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        testReceiptDate: {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        cartridgeLotNo: {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        assay: {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        qcDate: {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("#qcDoneYes").is(":checked") &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        qcDoneBy: {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("#qcDoneYes").is(":checked") &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        participantSupervisor: {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $('#supervisorApproval').val() === 'yes' &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
<?php
$count = 0;
$index = 0;
foreach ($this->allSamples as $sample) {
    $count++; ?>
        'dateTested[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        'mtbDetected[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        'rifResistance[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          validRifForMtbDetected: {
            param: '#mtbDetected<?php echo $count; ?>',
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("#mtbDetected<?php echo $count; ?>").val() !== '' &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          validRifForNoMtb: {
            param: '#mtbDetected<?php echo $count; ?>',
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("#mtbDetected<?php echo $count; ?>").val() !== '' &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        'errorCode[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                $("#mtbDetected<?php echo $count; ?>").val() === 'error' &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        'probe1[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          number: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          ctEndpointValue: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        'probe2[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          number: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          ctEndpointValue: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        'probe3[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          number: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          ctEndpointValue: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        'probe4[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          number: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          ctEndpointValue: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        'probe5[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          number: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          ctEndpointValue: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
        'probe6[<?php echo $index; ?>]': {
          required: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          number: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          },
          ctEndpointValue: {
            depends: function () {
              return ($('#submitAction').val() === 'submit' || previouslySubmitted) &&
                ['detected', 'high', 'medium', 'low', 'veryLow', 'notDetected'].includes($("#mtbDetected<?php echo $count; ?>").val()) &&
                $("input[name='ableToEnterResults']:checked").val() === "yes";
            }
          }
        },
<?php
    $index++;
} ?>
      },
      messages: {
        notTestedReason: "Why couldn't the PE panel be tested?",
        notTestedOtherReason: "Required if 'Other' selected",
        receiptDate: "What date did you receipt the panel?",
        expiryDate: "Please enter the expiration date of cartridge",
        testReceiptDate: "When did the lab submit the results?",
        mtbRifKitLotNo: "Please enter the lot number of cartridge",
        assay: "Which assay was used to run the samples?",
        qcDate: "When was monthly maintenance done?",
        qcDoneBy: "Who performed monthly maintenance?",
        participantSupervisor: "What is the name of the supervisor who approved this submission?",
<?php
$index = 0;
foreach ($this->allSamples as $sample) { ?>
        'dateTested[<?php echo $index; ?>]': {
          required: "Required"
        },
        'mtbDetected[<?php echo $index; ?>]': "Required",
        'rifResistance[<?php echo $index; ?>]': {
          required: "Required",
          validRifForMtbDetected: "Invalid Selection for MTB Detected",
          validRifForNoMtb: "Invalid Selection for MTB Detected"
        },
        'errorCode[<?php echo $index; ?>]': "Required",
        'probe1[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
        'probe2[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
        'probe3[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
        'probe4[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
        'probe5[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
        'probe6[<?php echo $index; ?>]': {
          required: "Required",
          number: "Only numerical values allowed for probe/spc fields",
          ctEndpointValue: "A value was detected above 42, have you entered endpoint values by mistake?"
        },
<?php
    $index++;
} ?>
      }
    };

    formValidator = $("#tbResponseForm").validate(validationOptions);
    $("#tbResponseForm").submit(function(event) {
      var errors = formValidator.numberOfInvalids();
      if (errors) {
        $('html body').animate({
          scrollTop: $(formValidator.errorList[0].element).offset().top - 100
        }, 1000);
        event.preventDefault();
      }
    });
    toggleToEnterResults();
  });

  $('.oneDecimal, .zeroDecimal').keypress(function () {
    var $this = $(this);
	$this.val($this.val().replace(/[^\d.]/g, ''));
  });

  $('.sampleTestDate').change(function () {
    $('.sampleTestDate').each(function() { });
  });

  $(".oneDecimal").on("blur", function(el) {
    clearTimeout(timeOut);
	timeOut = setTimeout(function() {
      var inputVal = $(el.target).val();
      if (inputVal) {
        var newVal = Number($(el.target).val()).toFixed(1);
        if ($.isNumeric(newVal)) {
          $(el.target).val(newVal);
        } else {
          $(el.target).val('');
        }
      }
	}, 600);
  });

  $(".zeroDecimal").on("blur", function(el) {
    clearTimeout(timeOut);
    timeOut = setTimeout(function() {
      var inputVal = $(el.target).val();
      if (inputVal) {
        var newVal = Number(inputVal).toFixed(0);
        if ($.isNumeric(newVal)) {
          $(el.target).val(newVal);
        } else {
          $(el.target).val('');
        }
      }
    },600);
  });

  function validateNow() {
    if (!formValidator.valid()) {
      formValidator.showErrors();
    }
    return formValidator.valid();
  }

  $('#supervisorApproval').change(function() {
    if ($('#supervisorApproval').val() == 'yes') {
      $('#labSupervisor').show();
      $('#participantSupervisor').val('');
      $('#participantSupervisor').show();
    } else {
      $('#labSupervisor').hide();
      $('#participantSupervisor').val('');
      $('#participantSupervisor').hide();
    }
  });

  function clearDate(id) {
    if ($("input[name='ableToEnterResults']:checked").val() === "yes") {
      $("#" + id).val('');
    }
  }

  function checkQcStatus(){
    var radioValue = $("input[name='qcDone']:checked"). val();
    if (radioValue == "yes") {
      $("#qcSection").show();
      $("#qcDate").addClass("isRequired");
      $("#qcDoneBy").addClass("isRequired");
    } else {
      $("#qcSection").hide();
      $("#qcDate").val("");
      $("#qcDoneBy").val("");
      $("#qcDate").removeClass("isRequired");
      $("#qcDoneBy").removeClass("isRequired");
    }
  }

  function changeInstrument(details) {
    $("#" + details.serialTextFieldId).val(details.serial);
    $("#" + details.dropDownId + " a span.dropdownText").text(details.serial);
    return false;
  }

  function changeMtbDetected(resultNumber) {
    var mtbDetected = $("#mtbDetected" + resultNumber).val();
    var errorCodeInput = $("#errorCode" + resultNumber);
    var rifResistanceSelect = $("#rifResistance" + resultNumber);
    if (mtbDetected === "error") {
      errorCodeInput.removeAttr("disabled");
      errorCodeInput.removeAttr("readonly");
    } else {
      errorCodeInput.attr("disabled", "");
      errorCodeInput.attr("readonly", "");
      errorCodeInput.val('')
    }
    if (["detected", "high", "medium", "low", "veryLow"].includes(mtbDetected)) {
      rifResistanceSelect.removeAttr("disabled");
      rifResistanceSelect.removeAttr("readonly");
    } else if (mtbDetected === "trace") {
      rifResistanceSelect.attr("disabled", "");
      rifResistanceSelect.attr("readonly", "");
      rifResistanceSelect.val('indeterminate')
    } else {
      rifResistanceSelect.attr("disabled", "");
      rifResistanceSelect.attr("readonly", "");
      rifResistanceSelect.val('na')
    }
  }

  var newInstrumentIndex = <?php echo count($this->instruments) ?>;
  var instrumentsMap = {
<?php
    $instrumentsListIndex = 0;
foreach ($this->instruments as $id => $instrument_details) { ?>
    '<?php echo $instrumentsListIndex ?>': {
      id: <?php echo $id; ?>,
      serial: "<?php echo $instrument_details['instrument_serial'] ?>",
      installed: "<?php echo $this->dateFormat($instrument_details['instrument_installed_on']); ?>",
      calibrated: "<?php echo $this->dateFormat($instrument_details['instrument_last_calibrated_on']); ?>"
    },
<?php
  $instrumentsListIndex++;
} ?>
  };

  function addInstrumentRow(obj) {
    if ($("input[name='ableToEnterResults']:checked").val() === "yes") {
      $(obj.parentNode.parentNode).after('<tr id="instrumentRow' + newInstrumentIndex + '">\
      <td>\
        <input type="hidden" name="headerInstrumentIndex[' + newInstrumentIndex + ']"\
          class="instrumentIndex" value="' + newInstrumentIndex + '" />\
        <input type="text" name="headerInstrumentSerial[' + newInstrumentIndex + ']"\
          class="form-control input-sm" onblur="updateInstrumentLists()"\
          title="Please enter the instrument serial number" />\
      </td>\
      <td>\
        <input type="text" class="form-control datepicker input-sm new-instrument-date-picker" readonly="readonly"\
          name="headerInstrumentInstalledOn[' + newInstrumentIndex + ']"\
          title="Please enter the instrument installation date" />\
      </td>\
      <td>\
        <input type="text" class="form-control datepicker input-sm new-instrument-date-picker" readonly="readonly"\
            name="headerInstrumentLastCalibratedOn[' + newInstrumentIndex + ']"\
            title="Please enter the date that the instrument was last calibrated" />\
      </td>\
      <td>\
        <a href="javascript:void(0);" onclick="addInstrumentRow(this);" class="btn btn-xs btn-info">\
          <i class="icon-plus"></i>\
        </a>&nbsp;&nbsp;\
        <a href="javascript:void(0);" onclick="removeInstrumentRow(this)" class="btn btn-xs btn-danger"\
          title="Remove this instrument" alt="Remove this instrument">\
          <i class="icon-minus"></i>\
        </a>\
      </td>\
    </tr>');
      instrumentsMap[newInstrumentIndex + ''] = {
        serial: "",
        installed: "",
        calibrated: ""
      };
      $(".new-instrument-date-picker").datepicker({
        dateFormat: '<?php echo $dtFormat;?>',
        onSelect: updateInstrumentLists
      });
      newInstrumentIndex++;
    }
  }

  function removeInstrumentRow(obj) {
    if ($("input[name='ableToEnterResults']:checked").val() === "yes") {
      if (Object.keys(instrumentsMap).length == 1) {
        addInstrumentRow(obj);
      }
      var removeInstrumentIndex = $(obj.parentNode.parentNode).find('.instrumentIndex').val();
      $(obj.parentNode.parentNode).fadeOut("normal", function () {
        $(this).remove();
      });
      delete instrumentsMap[removeInstrumentIndex];
      updateInstrumentLists();
    }
  }

  function updateInstrumentLists() {
    var instrumentIndices = Object.keys(instrumentsMap);
    instrumentIndices.forEach(function (instrumentIndex) {
      var instrumentSerial = $('[name="headerInstrumentSerial[' + instrumentIndex + ']"]').val();
      var installed = $('[name="headerInstrumentInstalledOn[' + instrumentIndex + ']"]').val();
      var calibrated = $('[name="headerInstrumentLastCalibratedOn[' + instrumentIndex + ']"]').val();
      var instrumentId = undefined;
      var instrumentIdField = $('[name="headerInstrumentId['+ instrumentIndex + ']"]');
      if (instrumentIdField) {
        instrumentId = instrumentIdField.val();
      }
      instrumentsMap[instrumentIndex] = {
        id: instrumentId,
        serial: instrumentSerial,
        installed: installed,
        calibrated: calibrated
      }
    });
    $('.instrument-list-item').remove();
    instrumentIndices = Object.keys(instrumentsMap);
    $('.instrument-list').each(function (elementIndex, instrumentUl) {
      var sampleNumber = $(instrumentUl).parent().attr('id').replace('instrumentDropDown', '');
      instrumentIndices.reverse().forEach(function (instrumentIndex) {
        $(instrumentUl).prepend('<li class="instrument-list-item">\
  <a href="" onClick="return changeInstrument({serial: \'' + instrumentsMap[instrumentIndex].serial + '\', installedOn: \'' + instrumentsMap[instrumentIndex].installed + '\', lastCalibratedOn: \'' + instrumentsMap[instrumentIndex].calibrated + '\', dropDownId: \'instrumentDropDown' + sampleNumber + '\', serialTextFieldId: \'instrumentSerial' + sampleNumber + '\', installedOnTextFieldId: \'instrumentInstalledOn' + sampleNumber + '\', lastCalibratedOnTextFieldId: \'instrumentLastCalibratedOn' + sampleNumber + '\'})">\
    ' + instrumentsMap[instrumentIndex].serial + '\
  </a>\
</li>');
      });
    });
  }
</script>
