<?php
$shipmentListSession = new Zend_Session_Namespace('shipmentList');
$urlListArray = $shipmentListSession->viewUrlList;
$this->currentUrl;
$pos = array_search($this->currentUrl, $urlListArray);
$prev = $pos - 1;
$next = $pos + 1;
$previousLink = $nextLink = "";
if ($prev >= 0) {
    $previousLink = $urlListArray[$prev];
}
if ($next < count($urlListArray)) {
    $nextLink = $urlListArray[$next];
}
?>
<br/>
<legend>Participant Result Summary</legend>
<?php
$reportDate = explode(" ", $this->evaluateData['shipment']['shipment_test_report_date'])
?>
<h5 style="padding-bottom:10px;">
<span class="pull-left">
  <strong>Participant Code:</strong> <?php echo $this->evaluateData['participant']['unique_identifier']; ?>
  &nbsp;&nbsp;&nbsp;&nbsp;
</span>
<span class="pull-left">
    <strong>Participant/Lab Name:</strong> <?php echo $this->evaluateData['participant']['lab_name']; ?>
</span>
<span class="pull-right">
    <strong>Reported on:</strong> <?php echo $this->dateFormat($reportDate[0]); ?>
</span>
</h5>
<input type="hidden" name="shipmentId" id="shipmentId" value="<?php echo $this->evaluateData['shipment']['shipment_id']; ?>" />
<input type="hidden" name="participantId" id="participantId" value="<?php echo $this->evaluateData['shipment']['participant_id']; ?>" />
<input type="hidden" name="smid" id="smid" value="<?php echo $this->evaluateData['shipment']['map_id']; ?>" />
<input type="hidden" name="scheme" id="scheme" value="<?php echo $this->scheme; ?>" />
<?php $correctiveActions = array();
    if ($this->scheme == 'tb') {
    $attributes = json_decode($this->evaluateData['shipment']['attributes'], true);
    if (isset($attributes['corrective_actions'])) {
        $correctiveActions = $attributes['corrective_actions'];
    } ?>
    <table class="table table-bordered table-striped" style="width:100%;margin:0 auto 10px auto;">
        <tr>
            <th style="width:20%;"><label>Submission Score</label></th>
            <td style="width:80%;" colspan="3">
                <h4 style="padding: 0; margin: 0 1em 0 0; width: auto; display: inline;">
                    <sup>
                        <?php echo ($this->evaluateData['shipment']['documentation_score'] + $this->evaluateData['shipment']['shipment_score']); ?>
                    </sup>
                    &frasl;
                    <sub>
                        <?php echo ($this->evaluateData['shipment']['max_documentation_score'] + $this->evaluateData['shipment']['max_shipment_score']); ?>
                    </sub>
                </h4>
                <?php
                if (isset($this->evaluateData['shipment']['calculated_score'])) {
                    $labelType = 'default';
                    $submissionSatisfactory = "Satisfactory";
                    switch ($this->evaluateData['shipment']['calculated_score'])
                    {
                        case 'pass':
                            $labelType = 'success';
                            break;
                        case 'partial':
                        case 'noresult':
                            $submissionSatisfactory = 'Unsatisfactory';
                            $labelType = 'warning';
                            break;
                        case 'fail':
                            $submissionSatisfactory = 'Unsatisfactory';
                            $labelType = 'danger';
                            break;
                        case 'concern':
                            $labelType = 'success';
                            break;
                    }
                    echo '<h4 style="padding: 0; margin: 0; width: auto; display: inline;"><span class="label label-'.$labelType.'">'.$submissionSatisfactory.'</span></h4>';
                } else {
                    echo '<h4 style="padding: 0; margin: 0; width: auto; display: inline;"><span class="label label-default">N/A</span></h4>';
                }
                ?>
            </td>
        </tr>
        <tr>
            <th>Shipment Code</th>
            <td style="width:30%;"><?php echo $this->evaluateData['shipment']['shipment_code']; ?></td>
            <th style="width:20%;">Scheme Type</th>
            <td style="width:30%;"><?php echo strtoupper($this->evaluateData['shipment']['scheme_type']); ?></td>
        </tr>
        <tr>
            <th>Shipment Date</th>
            <td><?php echo $this->dateFormat($this->evaluateData['shipment']['shipment_date']); ?></td>
            <th>Result Due Date</th>
            <td><?php echo $this->dateFormat($this->evaluateData['shipment']['lastdate_response']); ?></td>
        </tr>
        <tr>
            <th>Shipment Received on</th>
            <td>
                <?php echo $this->dateFormat($this->evaluateData['shipment']["shipment_receipt_date"]); ?>
            </td>
            <td><label>Assay</label></td>
            <td>
                <?php
                if(isset($attributes['assay'])) {
                    foreach($this->assays as $id => $definition) {
                        if($attributes['assay'] == $id) {
                            echo $definition['name'];
                        }
                    }
                } ?>
            </td>
        </tr>
        <tr>
            <th><label>Cartridge Kit Lot No</label></th>
            <td>
                <?php echo $attributes['cartridge_lot_no'];?>
            </td>
            <td><label>Expiration date of Cartridge:</label></td>
            <td>
                <?php echo $this->dateFormat($attributes['expiry_date']); ?>
            </td>
        </tr>
        <tr>
            <th><label>Response Date</label></th>
            <td>
                <?php echo $this->dateFormat($reportDate[0]); ?>
            </td>
        </tr>
        <tr>
            <td><label>How many Xpert MTB/RIF and MTB Ultra tests have been conducted by this site in the last full month?</label></td>
            <td>
                <?php if(isset($attributes['count_tests_conducted_over_month'])) {
                    echo $attributes['count_tests_conducted_over_month'];
                }?>
            </td>
            <td><label>How many errors occurred during testing in the last full month?</label></td>
            <td>
                <?php if(isset($attributes['count_errors_encountered_over_month'])) {
                    echo $attributes['count_errors_encountered_over_month'];
                }?>
            </td>
        </tr>
        <tr>
            <td><label>What were the error codes?</label></td>
            <td colspan="3">
                <?php if(isset($attributes['error_codes_encountered_over_month'])) {
                    echo $attributes['error_codes_encountered_over_month'];
                }?>
            </td>
        </tr>
        <tr>
            <th><label>Monthly Maintenance Done</label></th>
            <td>
                <?php echo ($this->evaluateData['shipment']['qc_done'] == "yes") ? "Yes" : "No"; ?>
            </td>
        </tr>
        <?php if (isset($this->evaluateData['shipment']['qc_done']) && $this->evaluateData['shipment']['qc_done'] == "yes") { ?>
        <tr>
            <td>
                <label>Maintenance Date</label>
            </td>
            <td>
                <?php echo $this->dateFormat($this->evaluateData['shipment']["qc_date"]); ?>
            </td>
            <td>
                <label>Maintenance Done By</label>
            </td>
            <td>
                <?php echo $this->evaluateData['shipment']["qc_done_by"]; ?>
            </td>
        </tr>
        <?php } ?>
        <tr>
            <th>Supervisor Review</th>
            <td>
                <?php echo $this->evaluateData['shipment']['supervisor_approval'] == "yes" ? "Yes" : "No"; ?>
            </td>
            <th>Supervisor Name</th>
            <td>
                <?php echo $this->evaluateData['shipment']['participant_supervisor']; ?>
            </td>
        </tr>
        <tr>
            <td colspan="4">
                <label>Instruments at Facility:</label>
                <table class="table table-bordered table-striped" style="width:100%;margin:10px auto;">
                    <thead>
                    <tr>
                        <td>
                            <label>Serial Number</label>
                        </td>
                        <td>
                            <label>Installed</label>
                        </td>
                        <td>
                            <label>Last Calibrated</label>
                        </td>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    $instrumentCount = 0;
                    $instrumentIndex = 0;
                    foreach ($this->instruments as $id => $instrument_details) {
                        $instrumentCount++; ?>
                        <tr>
                            <td>
                                <?php echo $instrument_details['instrument_serial']; ?>
                            </td>
                            <td>
                                <?php echo $this->dateFormat($instrument_details['instrument_installed_on']); ?>
                            </td>
                            <td>
                                <?php echo $this->dateFormat($instrument_details['instrument_last_calibrated_on']); ?>
                            </td>
                        </tr>
                        <?php
                        $instrumentIndex++;
                    } ?>
                    </tbody>
                </table>
            </td>
        </tr>
        <tr>
            <th>User Comments</th>
            <td colspan="3"><?php echo $this->evaluateData['shipment']['user_comment']; ?></td>
        </tr>
    </table>
    <br/>
    <table class="table table-bordered table-striped table-hover" style="width:100%;margin:0 auto;">
        <caption>
            <legend>Samples</legend>
        </caption>
    <?php
        $total = 0;
        $counter = 1;
        foreach ($this->evaluateData['results'] as $result) {
            if (($counter % 2) == 0) {
                $class = "evenResult";
            } else {
                $class = "oddResult";
            }
        ?>
        <tr class="<?php echo $class ?>">
            <td>
                <table class="table" style="background-color: transparent;">
                    <tr>
                        <th colspan="11" style="white-space: nowrap;background-color: transparent;">
                            <?php echo $result['sample_label']; ?>
                        </th>
                    </tr>
                    <tr style="background-color: transparent;">
                        <th style="background-color: transparent;">Date Tested</th>
                        <th style="background-color: transparent;">MTB Detected</th>
                        <th style="background-color: transparent;">Error Code</th>
                        <th style="background-color: transparent;">Rif Resistance</th>
                        <th style="background-color: transparent;">
                            <?php echo $this->evaluateData['shipment']['analyte1Label']; ?>
                        </th>
                        <th style="background-color: transparent;">
                            <?php echo $this->evaluateData['shipment']['analyte2Label']; ?>
                        </th>
                        <th style="background-color: transparent;">
                            <?php echo $this->evaluateData['shipment']['analyte3Label']; ?>
                        </th>
                        <th style="background-color: transparent;">
                            <?php echo $this->evaluateData['shipment']['analyte4Label']; ?>
                        </th>
                        <th style="background-color: transparent;">
                            <?php echo $this->evaluateData['shipment']['analyte5Label']; ?>
                        </th>
                        <th style="background-color: transparent;">
                            <?php echo $this->evaluateData['shipment']['analyte6Label']; ?>
                        </th>
                        <th style="text-align: center;font-size:17px;">Score</th>
                    </tr>
                    <tr>
                        <td style="vertical-align: middle;text-align: center;width: 14%;background-color: transparent;">
                            <?php echo $this->dateFormat($result['res_date_tested']); ?>
                        </td>
                        <td style="vertical-align: middle;text-align: center;width: 13%;background-color: transparent;">
                            <?php
                            switch ($result['res_mtb_detected']) {
                                case "detected":
                                    echo "Detected";
                                    break;
                                case "high":
                                    echo "High";
                                    break;
                                case "medium":
                                    echo "Medium";
                                    break;
                                case "low":
                                    echo "Low";
                                    break;
                                case "veryLow":
                                    echo "Very Low";
                                    break;
                                case "trace":
                                    echo "Trace";
                                    break;
                                case "notDetected":
                                    echo "Not Detected";
                                    break;
                                case "noResult":
                                    echo "No Result";
                                    break;
                                case "invalid":
                                    echo "Invalid";
                                    break;
                                case "error":
                                    echo "Error";
                                    break;
                                default:
                                    echo "Unknown";
                            }
                            ?>
                        </td>
                        <td style="vertical-align: middle;text-align: center;width: 11%;">
                            <?php echo $result['res_error_code']; ?>
                        </td>
                        <td style="vertical-align: middle;text-align:center;width: 13%;">
                            <?php
                            switch ($result['res_rif_resistance']) {
                                case "detected":
                                    echo "Detected";
                                    break;
                                case "notDetected":
                                    echo "Not Detected";
                                    break;
                                case "indeterminate":
                                    echo "RIF Indeterminate";
                                    break;
                                case "na":
                                    echo "N/A";
                                    break;
                                default:
                                    echo "Unknown";
                            }
                            ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;width: 7%;">
                            <?php echo $result['res_probe_1']; ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;width: 7%;">
                            <?php echo $result['res_probe_2']; ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;width: 7%;">
                            <?php echo $result['res_probe_3']; ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;width: 7%;">
                            <?php echo $result['res_probe_4']; ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;width: 7%;">
                            <?php echo $result['res_probe_5']; ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;width: 7%;">
                            <?php echo $result['res_probe_6']; ?>
                        </td>
                        <td style="vertical-align: middle;text-align: center;width: 7%;font-weight: bold;">
                            <?php
                            if (isset($result['calculated_score'])) {
                                $labelType = 'default';
                                switch ($result['calculated_score'])
                                {
                                    case 'pass':
                                        $labelType = 'success';
                                        break;
                                    case 'fail':
                                        $labelType = 'danger';
                                        break;
                                    case 'partial':
                                    case 'noresult':
                                    case 'concern':
                                        $labelType = 'warning';
                                        break;
                                }
                                echo '<span class="label label-'.$labelType.'">'.ucfirst($result['calculated_score']).'</span>';
                            } else {
                                echo "N/A";
                            }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="vertical-align: middle;text-align: right;">Reference Values:</td>
                        <td style="vertical-align: middle;text-align: center;">
                            <?php
                            if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB/RIF') {
                                switch ($result['ref_mtb_rif_mtb_detected']) {
                                    case "high":
                                        echo "High";
                                        break;
                                    case "medium":
                                        echo "Medium";
                                        break;
                                    case "low":
                                        echo "Low";
                                        break;
                                    case "veryLow":
                                        echo "Very Low";
                                        break;
                                    case "notDetected":
                                        echo "Not Detected";
                                        break;
                                    case "noResult":
                                        echo "No Result";
                                        break;
                                    case "invalid":
                                        echo "Invalid";
                                        break;
                                    case "error":
                                        echo "Error";
                                        break;
                                    default:
                                        echo "Unknown";
                                }
                            } else if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB Ultra') {
                                switch ($result['ref_ultra_mtb_detected']) {
                                    case "high":
                                        echo "High";
                                        break;
                                    case "medium":
                                        echo "Medium";
                                        break;
                                    case "low":
                                        echo "Low";
                                        break;
                                    case "veryLow":
                                        echo "Very Low";
                                        break;
                                    case "trace":
                                        echo "Trace";
                                        break;
                                    case "notDetected":
                                        echo "Not Detected";
                                        break;
                                    case "noResult":
                                        echo "No Result";
                                        break;
                                    case "invalid":
                                        echo "Invalid";
                                        break;
                                    case "error":
                                        echo "Error";
                                        break;
                                    default:
                                        echo "Unknown";
                                }
                            }
                            ?>
                        </td>
                        <td></td>
                        <td style="vertical-align: middle;text-align:center;">
                            <?php
                            if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB/RIF') {
                                switch ($result['ref_mtb_rif_rif_resistance']) {
                                    case "detected":
                                        echo "Detected";
                                        break;
                                    case "notDetected":
                                        echo "Not Detected";
                                        break;
                                    case "na":
                                        echo "N/A";
                                        break;
                                    default:
                                        echo "Unknown";
                                }
                            } else if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB Ultra') {
                                switch ($result['ref_ultra_rif_resistance']) {
                                    case "detected":
                                        echo "Detected";
                                        break;
                                    case "notDetected":
                                        echo "Not Detected";
                                        break;
                                    case "na":
                                        echo "N/A";
                                        break;
                                    default:
                                        echo "Unknown";
                                }
                            }
                            ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;">
                            <?php
                                if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB/RIF') {
                                    echo $result['ref_mtb_rif_probe_d'];
                                } else if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB Ultra') {
                                    echo $result['ref_ultra_probe_spc'];
                                }
                            ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;">
                            <?php
                                if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB/RIF') {
                                    echo $result['ref_mtb_rif_probe_c'];
                                } else if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB Ultra') {
                                    echo $result['ref_ultra_probe_is1081_is6110'];
                                }
                            ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;">
                            <?php
                                if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB/RIF') {
                                    echo $result['ref_mtb_rif_probe_e'];
                                } else if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB Ultra') {
                                    echo $result['ref_ultra_probe_rpo_b1'];
                                }
                            ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;">
                            <?php
                                if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB/RIF') {
                                    echo $result['ref_mtb_rif_probe_b'];
                                } else if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB Ultra') {
                                    echo $result['ref_ultra_probe_rpo_b2'];
                                }
                            ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;">
                            <?php
                                if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB/RIF') {
                                    echo $result['ref_mtb_rif_probe_spc'];
                                } else if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB Ultra') {
                                    echo $result['ref_ultra_probe_rpo_b3'];
                                }
                            ?>
                        </td>
                        <td style="vertical-align: middle;text-align: right;">
                            <?php
                                if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB/RIF') {
                                    echo $result['ref_mtb_rif_probe_a'];
                                } else if ($this->evaluateData['shipment']['assay_name'] == 'Xpert MTB Ultra') {
                                    echo $result['ref_ultra_probe_rpo_b4'];
                                }
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <th colspan="2" style="vertical-align: bottom;">Serial Number</th>
                        <th style="vertical-align: bottom;">Module Number</th>
                        <th colspan="2" style="vertical-align: bottom;">Instrument User</th>
                        <th colspan="2" style="vertical-align: bottom;"></th>
                        <th colspan="2" style="vertical-align: bottom;"></th>
                    </tr>
                    <tr style="background-color: transparent;">
                        <th colspan="2" style="white-space: nowrap;background-color: transparent;">
                            <?php echo $result['res_instrument_serial']; ?>
                        </th>
                        <th style="white-space: nowrap;background-color: transparent;">
                            <?php echo $result['res_module_name']; ?>
                        </th>
                        <th colspan="2" style="white-space: nowrap;background-color: transparent;">
                            <?php echo $result['res_instrument_user']; ?>
                        </th>
                        <td colspan="2" style="background-color: transparent;"></td>
                        <th colspan="2" style="white-space: nowrap;background-color: transparent;"></th>
                    </tr>
                </table>
            </td>
        </tr>
        <?php
            $counter++;
        } ?>
    </table>
<?php
} else {
    echo "<br/><br/><br/><h4 style='text-align:center;'>Evaluation for this scheme is not yet implemented</h4><br/><br/><br/>";
} ?>
<?php
$evalComments = array();
if (isset($this->evaluateData['evalComments'])) {
    foreach ($this->evaluateData['evalComments'] as $ec) {
        $evalComments[$ec['comment_id']] = $ec['comment'];
    }
}
?>
<table class="table table-bordered table-striped" style="width:80%;margin:0 auto;">
    <tr>
        <td style="width:25%;vertical-align: middle">Notes</td>
        <td>
			<?php
            if(isset($this->evaluateData['shipment']['failure_reason']) && $this->evaluateData['shipment']['failure_reason'] != "[]"){
                $warnings = json_decode($this->evaluateData['shipment']['failure_reason'],true);
                if($warnings != "" && $warnings != null){
                    echo "<table class='table table-bordered'>";
                    echo "<tr><th>Failure Reasons (or) Warnings</th><th>Corrective Actions (if any)</th></tr>";
                    foreach($warnings as $warning){
                        ?>
                        <tr>
                           <td><?php echo (isset($warning['warning']) ? $warning['warning'] : ""); ?></td>
                           <td><?php echo (isset($warning['correctiveAction']) ? $warning['correctiveAction'] : ""); ?></td>
                        </tr>
                        <?php
                    }
                    echo "</table>";
                }else{
                    echo " No Warnings or Corrective Actions ";
                }
            }else{
                echo " No Warnings or Corrective Actions ";
            }
            ?>
		</td>
    </tr>
    <tr>
        <td style="width:25%;vertical-align: middle">Corrective Actions</td>
        <td>
            <ul id="correctiveActionsList" class="list-unstyled">
            <?php for ($i = 0; $i < count($correctiveActions); $i++) { ?>
                <li id="correctiveActionItem<?php echo $i ?>">
                    <?php echo $correctiveActions[$i] ?>
                </li>
            <?php } ?>
            </ul>
        </td>
    </tr>
    <tr>
        <td style="width:25%;vertical-align: middle">Evaluation Comment</td>
        <td>
            <?php echo $this->dropdownSelectedText($evalComments, $this->evaluateData['shipment']['evaluation_comment'], true); ?>
        </td>
    </tr>
    <tr>
        <td style="vertical-align: middle;">
            Optional Extra Comments
        </td>
        <td style="text-align:left;"><?php echo $this->evaluateData['shipment']['optional_eval_comment']; ?></td>
    </tr>
</table>
<?php if(isset($this->haveCustom) && $this->haveCustom == 'yes') { ?>
<fieldset>
    <legend>Custom Fields</legend>
    <table>
        <tr>
            <th style="width:250px;padding:5px;"><?php echo $this->customField1; ?> </th>
            <td style="padding:5px;"><?php echo  $this->evaluateData['shipment']['custom_field_1']; ?></td>
        </tr>
        <?php if(isset($this->customField2) && $this->customField2 != "") { ?>
        <tr>
            <th style="width:250px;padding:5px;"><?php echo $this->customField2; ?> </th>
            <td style="padding:5px;"><?php echo  $this->evaluateData['shipment']['custom_field_1']; ?>/></td>
        </tr>
        <?php } ?>
    </table>
</fieldset>
<?php } ?>
<?php $config = new Zend_Config_Ini(APPLICATION_PATH . DIRECTORY_SEPARATOR . "configs" . DIRECTORY_SEPARATOR . "config.ini", APPLICATION_ENV); ?>
<br/>
<?php if (isset($this->evaluateData['shipment']['shipment_comment']) && $this->evaluateData['shipment']['shipment_comment'] != "") { ?>
    <legend>Comment from PE Admin</legend>
    <p class="well">
    <?php echo $this->evaluateData['shipment']['shipment_comment']; ?>
    </p>
<?php } ?>
<div id="respond" style="margin: 10px auto 10px auto; text-align: center;" align="center">
    <h5>Currently viewing result <?php echo $pos + 1 . " of " . count($urlListArray); ?> </h5>
    <?php
    if (isset($previousLink) && $previousLink != "") {
        ?>
            <a href="javascript:void(0)" class="btn btn-primary" onclick="$.blockUI();
                                        document.location.href = '<?php echo $previousLink; ?>';"><span><i class="icon-chevron-left"></i> View Previous Result</span></a>
        <?php
    }
    if (isset($nextLink) && $nextLink != "") {
        ?>
            <a href="javascript:void(0)" class="btn btn-primary" onclick="$.blockUI();
                 document.location.href = '<?php echo $nextLink; ?>';"><span>View Next Result <i class="icon-chevron-right"></i></span></a>
        <?php
    }
    ?>
    <input class="btn btn-danger" type="button" onclick="document.location = '/admin/evaluate/shipment/sid/<?php echo base64_encode($this->evaluateData['shipment']['shipment_id']); ?>'" value="Back to Listing"/>
</div>
