<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
	<div style="font-size:22.5px;line-height:36px;color:#333;float:left;">
        PE Surveys
    </div>
	<div style="margin-top:10px;">
		<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'distributions', 'action' => 'add'), 'default', true); ?>" class="btn btn-primary" style="float:right;">
            <i class="icon-plus"></i>
            &nbsp;&nbsp;Add New PE Survey
        </a>
	</div>
</h4>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="distributionsTable">
    <thead>
        <tr>
            <th>See Shipments</th>
            <th>PE Survey Date</th>
            <th>PE Survey Code</th>
            <th>Shipment Code(s)</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="10" class="dataTables_empty">Loading data from server</td>
        </tr>
    </tbody>
</table>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div><!-- /.modal -->
<script type="text/javascript" charset="utf-8">
	$('#myModal').on('hidden.bs.modal', function () {
	    $(this).removeData('bs.modal');
	});

    /* Table initialisation */
    var oTable = null;

    $(document).ready(function() {
        drawTable();
    });

	function shipDistribution(did) {
		var choice = confirm("Are you sure you want to ship this PE Survey ? \n You cannot undo this !");
		if (!choice) {
			return false;
		}
		$.blockUI();
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'distributions', 'action' => 'ship-distribution')); ?>", { did: did, format: "html" },
            function (data) {
                alert(data);
			    oTable.fnDraw();
			    $.unblockUI();
            });
	}

    function removeDistribution(didEncoded, did) {
      if (window.confirm("Are you sure you wish to delete? This cannot be undone!")) {
        $.blockUI();
        $.post("<?php echo $this->url(array('module' => 'admin', 'controller' => 'distributions', 'action' => 'remove')); ?>", {did: didEncoded, format: "html"},
          function (data) {
            if (data) {
                alert(data);
            }
            drawTable();
            $.unblockUI();
          });
      }
    }

    function drawTable() {
      oTable = $('#distributionsTable').dataTable({
        "oLanguage": {
          "sLengthMenu": "_MENU_ records per page",
          "sEmptyTable": "No surveys have been created yet"
        },
        "bJQueryUI": false,
        "bAutoWidth": false,
        "bInfo": true,
        "bScrollCollapse": true,
        "sPaginationType": "bootstrap",
        "bRetrieve": false,
        "bDestroy": true,
        "aoColumns": [
          {"sClass":"center","bSortable":false},
          {"sClass":"center"},
          {"sClass":"center"},
          {"sClass":"center"},
          {"sClass":"center"},
          {"sClass":"center","bSortable":false}
        ],
        "aaSorting": [[ 1, "desc" ]],
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'distributions', 'action' => 'index', 'format' => 'html')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
          $.ajax({
            "dataType": 'json',
            "type": "POST",
            "url": sSource,
            "data": aoData,
            "success": fnCallback
          });
        }, "fnRowCallback": function (nRow, aData, iDisplayIndex) {
          $('td.sorting_1').addClass('goga');
        },
      });
    <?php
      if (isset($this->searchData) && $this->searchData != '') { ?>
        oTable.fnFilter('<?php echo $this->searchData;?>');
      <?php
      } ?>
    }
</script>