<?php
$authNameSpace = new Zend_Session_Namespace('administrators');
?>
<h4 style="width:100%;height:60px;border-bottom:1px solid #777;">
    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">
        Proficiency Testing Country Coordinators
    </div>
    <div style="margin-top:10px; float: right;">
        <?php if (!$authNameSpace->is_ptcc_coordinator) { ?>
        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'ptcc-profiles', 'action' => 'edit'), 'default', true); ?>" class="btn btn-primary">
            <i class="icon-user"></i>&nbsp;&nbsp;Add New PTCC
        </a>
        <!--<a id="importPtccsExcelAnchor" href="#" class="btn btn-success" style="margin-left: 10px;"><i class="icon-table"></i>&nbsp;&nbsp;Import PTCCs</a>-->
        <?php } ?>
    </div>
</h4>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="usersTable">
    <thead>
        <tr>
            <th style="width: 18%;">First Name</th>
            <th style="width: 18%;">Last Name</th>
            <th style="width: 18%;">Email</th>
            <th style="width: 18%;">Phone</th>
            <th style="width: 18%;">Countries</th>
            <th style="width: 10%;">Action</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="10" class="dataTables_empty">Loading data from server</td>
        </tr>
    </tbody>
</table>
<?php
if ($authNameSpace->is_ptcc_coordinator == 0) { ?>
    <form name="ptccsImportForm" id="ptccsImportForm" enctype="multipart/form-data" action="<?php echo $this->url(array("module" => "admin", "controller" => "ptcc-profiles", "action" => "import"), 'default', true) ?>" method="post">
        <input type="file" id="importPtccsExcelFile" name="importPtccsExcelFile" style="visibility: hidden; width: 1px; height: 1px; display: none;" accept=".xlsx,.xls" />
    </form>
    <?php
} ?>
<script type="text/javascript" charset="utf-8">
    /* Table initialisation */
    var oTable = null;
    $(document).ready(function() {
        oTable = $('#usersTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": true,
            "aoColumns": [
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":""},
                {"sClass":"center","bSortable":false}
            ],
            "aaSorting": [[ 0, "asc" ]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'admin', 'controller' => 'ptcc-profiles', 'action' => 'index', 'format' => 'html')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
        <?php
        if ($authNameSpace->is_ptcc_coordinator == 0) { ?>
        $('#importPtccsExcelAnchor').on('click', function() {
            $('#importPtccsExcelFile').trigger('click');
        });
        $('#importPtccsExcelFile').on('change', function () {
            $.blockUI();
            $('#ptccsImportForm').submit();
        });
        <?php
        } ?>
    });
</script>